/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.ENUMS;





/**
 * 1-pending, 2-approved, 3-rejected, 4- cancel
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum BookingHistoryStatusStatus{

    _1("1"),

    _2("2"),

    _3("3"),

    _4("4");

    private final String literal;

    private BookingHistoryStatusStatus(String literal) {
        this.literal = literal;
    }

}
