/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.ENUMS;

/**
 * 1-passenger, 2- driver, 3- other
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum CustomerCustomerType {

	_1("1"),

	_2("2"),

	_3("3");

	private final String literal;

	private CustomerCustomerType(String literal) {
		this.literal = literal;
	}

}
