/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.ENUMS;




/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum EnquiryEnquiryType  {

    Website("Website"),

    Mobile("Mobile");

    private final String literal;

    private EnquiryEnquiryType(String literal) {
        this.literal = literal;
    }


}
