#------------ Port Number --------------#
server:
  port: 8083
#------------Eureka registry -------------#
eureka:
  client:
    serviceUri:
      defaultZone: http://localhost:8761/eureka


#------------Application Name -----------#
spring:
  application:
    name: invopay-web-service
  #----------Database Configuration -------#
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/invopay?zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/oauth2/jwks
          issuer-uri: http://localhost:8080

emailBaseUrl: http://localhost:8084/