/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.DTO;


import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Data
@NoArgsConstructor
@Getter
@Setter
public class AccountsCodeDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       accountsCodeId;
    private String        accountsCodeName;
    private Integer       refAccountsTransactionCategoryId;
    private Integer       refAccountsGroupId;
    private Integer       refUserId;
    private Integer       deleteStatus;
    private Integer       transactionId;
    private LocalDateTime addedDate;

    public AccountsCodeDTO(Integer accountsCodeId,String accountsCodeName){
        this.accountsCodeId=accountsCodeId;
        this.accountsCodeName=accountsCodeName;
    }

}
