/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.DTO;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppointmentFeedbackDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       appointmentFeedbackId;
    private String        appointmentFeedbackName;
    private Integer       deleteStatus;
    private Integer       userId;
    private Integer       transactionId;
    private LocalDateTime addedDate;

    public AppointmentFeedbackDTO() {}

    public AppointmentFeedbackDTO(AppointmentFeedbackDTO value) {
        this.appointmentFeedbackId = value.appointmentFeedbackId;
        this.appointmentFeedbackName = value.appointmentFeedbackName;
        this.deleteStatus = value.deleteStatus;
        this.userId = value.userId;
        this.transactionId = value.transactionId;
        this.addedDate = value.addedDate;
    }

    public AppointmentFeedbackDTO(
        Integer       appointmentFeedbackId,
        String        appointmentFeedbackName,
        Integer       deleteStatus,
        Integer       userId,
        Integer       transactionId,
        LocalDateTime addedDate
    ) {
        this.appointmentFeedbackId = appointmentFeedbackId;
        this.appointmentFeedbackName = appointmentFeedbackName;
        this.deleteStatus = deleteStatus;
        this.userId = userId;
        this.transactionId = transactionId;
        this.addedDate = addedDate;
    }

    /**
     * Getter for <code>invopay.appointment_feedback.appointment_feedback_id</code>.
     */
    public Integer getAppointmentFeedbackId() {
        return this.appointmentFeedbackId;
    }

    /**
     * Setter for <code>invopay.appointment_feedback.appointment_feedback_id</code>.
     */
    public AppointmentFeedbackDTO setAppointmentFeedbackId(Integer appointmentFeedbackId) {
        this.appointmentFeedbackId = appointmentFeedbackId;
        return this;
    }

    /**
     * Getter for <code>invopay.appointment_feedback.appointment_feedback_name</code>.
     */
    public String getAppointmentFeedbackName() {
        return this.appointmentFeedbackName;
    }

    /**
     * Setter for <code>invopay.appointment_feedback.appointment_feedback_name</code>.
     */
    public AppointmentFeedbackDTO setAppointmentFeedbackName(String appointmentFeedbackName) {
        this.appointmentFeedbackName = appointmentFeedbackName;
        return this;
    }

    /**
     * Getter for <code>invopay.appointment_feedback.delete_status</code>.
     */
    public Integer getDeleteStatus() {
        return this.deleteStatus;
    }

    /**
     * Setter for <code>invopay.appointment_feedback.delete_status</code>.
     */
    public AppointmentFeedbackDTO setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.appointment_feedback.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>invopay.appointment_feedback.user_id</code>.
     */
    public AppointmentFeedbackDTO setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>invopay.appointment_feedback.transaction_id</code>.
     */
    public Integer getTransactionId() {
        return this.transactionId;
    }

    /**
     * Setter for <code>invopay.appointment_feedback.transaction_id</code>.
     */
    public AppointmentFeedbackDTO setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
        return this;
    }

    /**
     * Getter for <code>invopay.appointment_feedback.added_date</code>.
     */
    public LocalDateTime getAddedDate() {
        return this.addedDate;
    }

    /**
     * Setter for <code>invopay.appointment_feedback.added_date</code>.
     */
    public AppointmentFeedbackDTO setAddedDate(LocalDateTime addedDate) {
        this.addedDate = addedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AppointmentFeedbackDTO other = (AppointmentFeedbackDTO) obj;
        if (appointmentFeedbackId == null) {
            if (other.appointmentFeedbackId != null)
                return false;
        }
        else if (!appointmentFeedbackId.equals(other.appointmentFeedbackId))
            return false;
        if (appointmentFeedbackName == null) {
            if (other.appointmentFeedbackName != null)
                return false;
        }
        else if (!appointmentFeedbackName.equals(other.appointmentFeedbackName))
            return false;
        if (deleteStatus == null) {
            if (other.deleteStatus != null)
                return false;
        }
        else if (!deleteStatus.equals(other.deleteStatus))
            return false;
        if (userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!userId.equals(other.userId))
            return false;
        if (transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!transactionId.equals(other.transactionId))
            return false;
        if (addedDate == null) {
            if (other.addedDate != null)
                return false;
        }
        else if (!addedDate.equals(other.addedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.appointmentFeedbackId == null) ? 0 : this.appointmentFeedbackId.hashCode());
        result = prime * result + ((this.appointmentFeedbackName == null) ? 0 : this.appointmentFeedbackName.hashCode());
        result = prime * result + ((this.deleteStatus == null) ? 0 : this.deleteStatus.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.addedDate == null) ? 0 : this.addedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AppointmentFeedback (");

        sb.append(appointmentFeedbackId);
        sb.append(", ").append(appointmentFeedbackName);
        sb.append(", ").append(deleteStatus);
        sb.append(", ").append(userId);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(addedDate);

        sb.append(")");
        return sb.toString();
    }
}
