/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.DTO;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApproveStatusDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       approveStatusId;
    private String        approveStatusName;
    private Integer       refUserId;
    private Integer       deleteStatus;
    private Integer       transactionId;
    private LocalDateTime addedDate;

    public ApproveStatusDTO() {}

    public ApproveStatusDTO(ApproveStatusDTO value) {
        this.approveStatusId = value.approveStatusId;
        this.approveStatusName = value.approveStatusName;
        this.refUserId = value.refUserId;
        this.deleteStatus = value.deleteStatus;
        this.transactionId = value.transactionId;
        this.addedDate = value.addedDate;
    }

    public ApproveStatusDTO(
        Integer       approveStatusId,
        String        approveStatusName,
        Integer       refUserId,
        Integer       deleteStatus,
        Integer       transactionId,
        LocalDateTime addedDate
    ) {
        this.approveStatusId = approveStatusId;
        this.approveStatusName = approveStatusName;
        this.refUserId = refUserId;
        this.deleteStatus = deleteStatus;
        this.transactionId = transactionId;
        this.addedDate = addedDate;
    }

    /**
     * Getter for <code>invopay.approve_status.approve_status_id</code>.
     */
    public Integer getApproveStatusId() {
        return this.approveStatusId;
    }

    /**
     * Setter for <code>invopay.approve_status.approve_status_id</code>.
     */
    public ApproveStatusDTO setApproveStatusId(Integer approveStatusId) {
        this.approveStatusId = approveStatusId;
        return this;
    }

    /**
     * Getter for <code>invopay.approve_status.approve_status_name</code>. Approve Status
     */
    public String getApproveStatusName() {
        return this.approveStatusName;
    }

    /**
     * Setter for <code>invopay.approve_status.approve_status_name</code>. Approve Status
     */
    public ApproveStatusDTO setApproveStatusName(String approveStatusName) {
        this.approveStatusName = approveStatusName;
        return this;
    }

    /**
     * Getter for <code>invopay.approve_status.ref_user_id</code>.
     */
    public Integer getRefUserId() {
        return this.refUserId;
    }

    /**
     * Setter for <code>invopay.approve_status.ref_user_id</code>.
     */
    public ApproveStatusDTO setRefUserId(Integer refUserId) {
        this.refUserId = refUserId;
        return this;
    }

    /**
     * Getter for <code>invopay.approve_status.delete_status</code>.
     */
    public Integer getDeleteStatus() {
        return this.deleteStatus;
    }

    /**
     * Setter for <code>invopay.approve_status.delete_status</code>.
     */
    public ApproveStatusDTO setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.approve_status.transaction_id</code>.
     */
    public Integer getTransactionId() {
        return this.transactionId;
    }

    /**
     * Setter for <code>invopay.approve_status.transaction_id</code>.
     */
    public ApproveStatusDTO setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
        return this;
    }

    /**
     * Getter for <code>invopay.approve_status.added_date</code>.
     */
    public LocalDateTime getAddedDate() {
        return this.addedDate;
    }

    /**
     * Setter for <code>invopay.approve_status.added_date</code>.
     */
    public ApproveStatusDTO setAddedDate(LocalDateTime addedDate) {
        this.addedDate = addedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ApproveStatusDTO other = (ApproveStatusDTO) obj;
        if (approveStatusId == null) {
            if (other.approveStatusId != null)
                return false;
        }
        else if (!approveStatusId.equals(other.approveStatusId))
            return false;
        if (approveStatusName == null) {
            if (other.approveStatusName != null)
                return false;
        }
        else if (!approveStatusName.equals(other.approveStatusName))
            return false;
        if (refUserId == null) {
            if (other.refUserId != null)
                return false;
        }
        else if (!refUserId.equals(other.refUserId))
            return false;
        if (deleteStatus == null) {
            if (other.deleteStatus != null)
                return false;
        }
        else if (!deleteStatus.equals(other.deleteStatus))
            return false;
        if (transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!transactionId.equals(other.transactionId))
            return false;
        if (addedDate == null) {
            if (other.addedDate != null)
                return false;
        }
        else if (!addedDate.equals(other.addedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.approveStatusId == null) ? 0 : this.approveStatusId.hashCode());
        result = prime * result + ((this.approveStatusName == null) ? 0 : this.approveStatusName.hashCode());
        result = prime * result + ((this.refUserId == null) ? 0 : this.refUserId.hashCode());
        result = prime * result + ((this.deleteStatus == null) ? 0 : this.deleteStatus.hashCode());
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.addedDate == null) ? 0 : this.addedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ApproveStatus (");

        sb.append(approveStatusId);
        sb.append(", ").append(approveStatusName);
        sb.append(", ").append(refUserId);
        sb.append(", ").append(deleteStatus);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(addedDate);

        sb.append(")");
        return sb.toString();
    }
}
