/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.DTO;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClientCallFeedbackDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       clientCallFeedbackId;
    private String        clientCallFeedbackName;
    private Integer       deleteStatus;
    private Integer       userId;
    private Integer       transactionId;
    private LocalDateTime addedDate;

    public ClientCallFeedbackDTO() {}

    public ClientCallFeedbackDTO(ClientCallFeedbackDTO value) {
        this.clientCallFeedbackId = value.clientCallFeedbackId;
        this.clientCallFeedbackName = value.clientCallFeedbackName;
        this.deleteStatus = value.deleteStatus;
        this.userId = value.userId;
        this.transactionId = value.transactionId;
        this.addedDate = value.addedDate;
    }

    public ClientCallFeedbackDTO(
        Integer       clientCallFeedbackId,
        String        clientCallFeedbackName,
        Integer       deleteStatus,
        Integer       userId,
        Integer       transactionId,
        LocalDateTime addedDate
    ) {
        this.clientCallFeedbackId = clientCallFeedbackId;
        this.clientCallFeedbackName = clientCallFeedbackName;
        this.deleteStatus = deleteStatus;
        this.userId = userId;
        this.transactionId = transactionId;
        this.addedDate = addedDate;
    }

    /**
     * Getter for <code>invopay.client_call_feedback.client_call_feedback_id</code>.
     */
    public Integer getClientCallFeedbackId() {
        return this.clientCallFeedbackId;
    }

    /**
     * Setter for <code>invopay.client_call_feedback.client_call_feedback_id</code>.
     */
    public ClientCallFeedbackDTO setClientCallFeedbackId(Integer clientCallFeedbackId) {
        this.clientCallFeedbackId = clientCallFeedbackId;
        return this;
    }

    /**
     * Getter for <code>invopay.client_call_feedback.client_call_feedback_name</code>.
     */
    public String getClientCallFeedbackName() {
        return this.clientCallFeedbackName;
    }

    /**
     * Setter for <code>invopay.client_call_feedback.client_call_feedback_name</code>.
     */
    public ClientCallFeedbackDTO setClientCallFeedbackName(String clientCallFeedbackName) {
        this.clientCallFeedbackName = clientCallFeedbackName;
        return this;
    }

    /**
     * Getter for <code>invopay.client_call_feedback.delete_status</code>.
     */
    public Integer getDeleteStatus() {
        return this.deleteStatus;
    }

    /**
     * Setter for <code>invopay.client_call_feedback.delete_status</code>.
     */
    public ClientCallFeedbackDTO setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.client_call_feedback.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>invopay.client_call_feedback.user_id</code>.
     */
    public ClientCallFeedbackDTO setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>invopay.client_call_feedback.transaction_id</code>.
     */
    public Integer getTransactionId() {
        return this.transactionId;
    }

    /**
     * Setter for <code>invopay.client_call_feedback.transaction_id</code>.
     */
    public ClientCallFeedbackDTO setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
        return this;
    }

    /**
     * Getter for <code>invopay.client_call_feedback.added_date</code>.
     */
    public LocalDateTime getAddedDate() {
        return this.addedDate;
    }

    /**
     * Setter for <code>invopay.client_call_feedback.added_date</code>.
     */
    public ClientCallFeedbackDTO setAddedDate(LocalDateTime addedDate) {
        this.addedDate = addedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ClientCallFeedbackDTO other = (ClientCallFeedbackDTO) obj;
        if (clientCallFeedbackId == null) {
            if (other.clientCallFeedbackId != null)
                return false;
        }
        else if (!clientCallFeedbackId.equals(other.clientCallFeedbackId))
            return false;
        if (clientCallFeedbackName == null) {
            if (other.clientCallFeedbackName != null)
                return false;
        }
        else if (!clientCallFeedbackName.equals(other.clientCallFeedbackName))
            return false;
        if (deleteStatus == null) {
            if (other.deleteStatus != null)
                return false;
        }
        else if (!deleteStatus.equals(other.deleteStatus))
            return false;
        if (userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!userId.equals(other.userId))
            return false;
        if (transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!transactionId.equals(other.transactionId))
            return false;
        if (addedDate == null) {
            if (other.addedDate != null)
                return false;
        }
        else if (!addedDate.equals(other.addedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.clientCallFeedbackId == null) ? 0 : this.clientCallFeedbackId.hashCode());
        result = prime * result + ((this.clientCallFeedbackName == null) ? 0 : this.clientCallFeedbackName.hashCode());
        result = prime * result + ((this.deleteStatus == null) ? 0 : this.deleteStatus.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.addedDate == null) ? 0 : this.addedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ClientCallFeedback (");

        sb.append(clientCallFeedbackId);
        sb.append(", ").append(clientCallFeedbackName);
        sb.append(", ").append(deleteStatus);
        sb.append(", ").append(userId);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(addedDate);

        sb.append(")");
        return sb.toString();
    }
}
