/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.DTO;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerOrderProductDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       customerOrderProductId;
    private Integer       refProductId;
    private Integer       refCustomerOrderId;
    private Integer       quantity;
    private Double        price;
    private Double        productTotal;
    private Double        gstPercentage;
    private Double        gstAmount;
    private Integer       refUserId;
    private Integer       deleteStatus;
    private Integer       transactionId;
    private LocalDateTime addedDate;

    public CustomerOrderProductDTO() {}

    public CustomerOrderProductDTO(CustomerOrderProductDTO value) {
        this.customerOrderProductId = value.customerOrderProductId;
        this.refProductId = value.refProductId;
        this.refCustomerOrderId = value.refCustomerOrderId;
        this.quantity = value.quantity;
        this.price = value.price;
        this.productTotal = value.productTotal;
        this.gstPercentage = value.gstPercentage;
        this.gstAmount = value.gstAmount;
        this.refUserId = value.refUserId;
        this.deleteStatus = value.deleteStatus;
        this.transactionId = value.transactionId;
        this.addedDate = value.addedDate;
    }

    public CustomerOrderProductDTO(
        Integer       customerOrderProductId,
        Integer       refProductId,
        Integer       refCustomerOrderId,
        Integer       quantity,
        Double        price,
        Double        productTotal,
        Double        gstPercentage,
        Double        gstAmount,
        Integer       refUserId,
        Integer       deleteStatus,
        Integer       transactionId,
        LocalDateTime addedDate
    ) {
        this.customerOrderProductId = customerOrderProductId;
        this.refProductId = refProductId;
        this.refCustomerOrderId = refCustomerOrderId;
        this.quantity = quantity;
        this.price = price;
        this.productTotal = productTotal;
        this.gstPercentage = gstPercentage;
        this.gstAmount = gstAmount;
        this.refUserId = refUserId;
        this.deleteStatus = deleteStatus;
        this.transactionId = transactionId;
        this.addedDate = addedDate;
    }

    /**
     * Getter for <code>invopay.customer_order_product.customer_order_product_id</code>.
     */
    public Integer getCustomerOrderProductId() {
        return this.customerOrderProductId;
    }

    /**
     * Setter for <code>invopay.customer_order_product.customer_order_product_id</code>.
     */
    public CustomerOrderProductDTO setCustomerOrderProductId(Integer customerOrderProductId) {
        this.customerOrderProductId = customerOrderProductId;
        return this;
    }

    /**
     * Getter for <code>invopay.customer_order_product.ref_product_id</code>.
     */
    public Integer getRefProductId() {
        return this.refProductId;
    }

    /**
     * Setter for <code>invopay.customer_order_product.ref_product_id</code>.
     */
    public CustomerOrderProductDTO setRefProductId(Integer refProductId) {
        this.refProductId = refProductId;
        return this;
    }

    /**
     * Getter for <code>invopay.customer_order_product.ref_customer_order_id</code>.
     */
    public Integer getRefCustomerOrderId() {
        return this.refCustomerOrderId;
    }

    /**
     * Setter for <code>invopay.customer_order_product.ref_customer_order_id</code>.
     */
    public CustomerOrderProductDTO setRefCustomerOrderId(Integer refCustomerOrderId) {
        this.refCustomerOrderId = refCustomerOrderId;
        return this;
    }

    /**
     * Getter for <code>invopay.customer_order_product.quantity</code>.
     */
    public Integer getQuantity() {
        return this.quantity;
    }

    /**
     * Setter for <code>invopay.customer_order_product.quantity</code>.
     */
    public CustomerOrderProductDTO setQuantity(Integer quantity) {
        this.quantity = quantity;
        return this;
    }

    /**
     * Getter for <code>invopay.customer_order_product.price</code>.
     */
    public Double getPrice() {
        return this.price;
    }

    /**
     * Setter for <code>invopay.customer_order_product.price</code>.
     */
    public CustomerOrderProductDTO setPrice(Double price) {
        this.price = price;
        return this;
    }

    /**
     * Getter for <code>invopay.customer_order_product.product_total</code>.
     */
    public Double getProductTotal() {
        return this.productTotal;
    }

    /**
     * Setter for <code>invopay.customer_order_product.product_total</code>.
     */
    public CustomerOrderProductDTO setProductTotal(Double productTotal) {
        this.productTotal = productTotal;
        return this;
    }

    /**
     * Getter for <code>invopay.customer_order_product.gst_percentage</code>.
     */
    public Double getGstPercentage() {
        return this.gstPercentage;
    }

    /**
     * Setter for <code>invopay.customer_order_product.gst_percentage</code>.
     */
    public CustomerOrderProductDTO setGstPercentage(Double gstPercentage) {
        this.gstPercentage = gstPercentage;
        return this;
    }

    /**
     * Getter for <code>invopay.customer_order_product.gst_amount</code>.
     */
    public Double getGstAmount() {
        return this.gstAmount;
    }

    /**
     * Setter for <code>invopay.customer_order_product.gst_amount</code>.
     */
    public CustomerOrderProductDTO setGstAmount(Double gstAmount) {
        this.gstAmount = gstAmount;
        return this;
    }

    /**
     * Getter for <code>invopay.customer_order_product.ref_user_id</code>.
     */
    public Integer getRefUserId() {
        return this.refUserId;
    }

    /**
     * Setter for <code>invopay.customer_order_product.ref_user_id</code>.
     */
    public CustomerOrderProductDTO setRefUserId(Integer refUserId) {
        this.refUserId = refUserId;
        return this;
    }

    /**
     * Getter for <code>invopay.customer_order_product.delete_status</code>.
     */
    public Integer getDeleteStatus() {
        return this.deleteStatus;
    }

    /**
     * Setter for <code>invopay.customer_order_product.delete_status</code>.
     */
    public CustomerOrderProductDTO setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.customer_order_product.transaction_id</code>.
     */
    public Integer getTransactionId() {
        return this.transactionId;
    }

    /**
     * Setter for <code>invopay.customer_order_product.transaction_id</code>.
     */
    public CustomerOrderProductDTO setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
        return this;
    }

    /**
     * Getter for <code>invopay.customer_order_product.added_date</code>.
     */
    public LocalDateTime getAddedDate() {
        return this.addedDate;
    }

    /**
     * Setter for <code>invopay.customer_order_product.added_date</code>.
     */
    public CustomerOrderProductDTO setAddedDate(LocalDateTime addedDate) {
        this.addedDate = addedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CustomerOrderProductDTO other = (CustomerOrderProductDTO) obj;
        if (customerOrderProductId == null) {
            if (other.customerOrderProductId != null)
                return false;
        }
        else if (!customerOrderProductId.equals(other.customerOrderProductId))
            return false;
        if (refProductId == null) {
            if (other.refProductId != null)
                return false;
        }
        else if (!refProductId.equals(other.refProductId))
            return false;
        if (refCustomerOrderId == null) {
            if (other.refCustomerOrderId != null)
                return false;
        }
        else if (!refCustomerOrderId.equals(other.refCustomerOrderId))
            return false;
        if (quantity == null) {
            if (other.quantity != null)
                return false;
        }
        else if (!quantity.equals(other.quantity))
            return false;
        if (price == null) {
            if (other.price != null)
                return false;
        }
        else if (!price.equals(other.price))
            return false;
        if (productTotal == null) {
            if (other.productTotal != null)
                return false;
        }
        else if (!productTotal.equals(other.productTotal))
            return false;
        if (gstPercentage == null) {
            if (other.gstPercentage != null)
                return false;
        }
        else if (!gstPercentage.equals(other.gstPercentage))
            return false;
        if (gstAmount == null) {
            if (other.gstAmount != null)
                return false;
        }
        else if (!gstAmount.equals(other.gstAmount))
            return false;
        if (refUserId == null) {
            if (other.refUserId != null)
                return false;
        }
        else if (!refUserId.equals(other.refUserId))
            return false;
        if (deleteStatus == null) {
            if (other.deleteStatus != null)
                return false;
        }
        else if (!deleteStatus.equals(other.deleteStatus))
            return false;
        if (transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!transactionId.equals(other.transactionId))
            return false;
        if (addedDate == null) {
            if (other.addedDate != null)
                return false;
        }
        else if (!addedDate.equals(other.addedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.customerOrderProductId == null) ? 0 : this.customerOrderProductId.hashCode());
        result = prime * result + ((this.refProductId == null) ? 0 : this.refProductId.hashCode());
        result = prime * result + ((this.refCustomerOrderId == null) ? 0 : this.refCustomerOrderId.hashCode());
        result = prime * result + ((this.quantity == null) ? 0 : this.quantity.hashCode());
        result = prime * result + ((this.price == null) ? 0 : this.price.hashCode());
        result = prime * result + ((this.productTotal == null) ? 0 : this.productTotal.hashCode());
        result = prime * result + ((this.gstPercentage == null) ? 0 : this.gstPercentage.hashCode());
        result = prime * result + ((this.gstAmount == null) ? 0 : this.gstAmount.hashCode());
        result = prime * result + ((this.refUserId == null) ? 0 : this.refUserId.hashCode());
        result = prime * result + ((this.deleteStatus == null) ? 0 : this.deleteStatus.hashCode());
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.addedDate == null) ? 0 : this.addedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CustomerOrderProduct (");

        sb.append(customerOrderProductId);
        sb.append(", ").append(refProductId);
        sb.append(", ").append(refCustomerOrderId);
        sb.append(", ").append(quantity);
        sb.append(", ").append(price);
        sb.append(", ").append(productTotal);
        sb.append(", ").append(gstPercentage);
        sb.append(", ").append(gstAmount);
        sb.append(", ").append(refUserId);
        sb.append(", ").append(deleteStatus);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(addedDate);

        sb.append(")");
        return sb.toString();
    }
}
