/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.DTO;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeliveryPointDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       deliveryPointId;
    private String        deliveryPointName;
    private Integer       deleteStatus;
    private Integer       refUserId;
    private Integer       transactionId;
    private LocalDateTime addedDate;

    public DeliveryPointDTO() {}

    public DeliveryPointDTO(DeliveryPointDTO value) {
        this.deliveryPointId = value.deliveryPointId;
        this.deliveryPointName = value.deliveryPointName;
        this.deleteStatus = value.deleteStatus;
        this.refUserId = value.refUserId;
        this.transactionId = value.transactionId;
        this.addedDate = value.addedDate;
    }

    public DeliveryPointDTO(
        Integer       deliveryPointId,
        String        deliveryPointName,
        Integer       deleteStatus,
        Integer       refUserId,
        Integer       transactionId,
        LocalDateTime addedDate
    ) {
        this.deliveryPointId = deliveryPointId;
        this.deliveryPointName = deliveryPointName;
        this.deleteStatus = deleteStatus;
        this.refUserId = refUserId;
        this.transactionId = transactionId;
        this.addedDate = addedDate;
    }

    /**
     * Getter for <code>invopay.delivery_point.delivery_point_id</code>.
     */
    public Integer getDeliveryPointId() {
        return this.deliveryPointId;
    }

    /**
     * Setter for <code>invopay.delivery_point.delivery_point_id</code>.
     */
    public DeliveryPointDTO setDeliveryPointId(Integer deliveryPointId) {
        this.deliveryPointId = deliveryPointId;
        return this;
    }

    /**
     * Getter for <code>invopay.delivery_point.delivery_point_name</code>. Delivery Point
     */
    public String getDeliveryPointName() {
        return this.deliveryPointName;
    }

    /**
     * Setter for <code>invopay.delivery_point.delivery_point_name</code>. Delivery Point
     */
    public DeliveryPointDTO setDeliveryPointName(String deliveryPointName) {
        this.deliveryPointName = deliveryPointName;
        return this;
    }

    /**
     * Getter for <code>invopay.delivery_point.delete_status</code>.
     */
    public Integer getDeleteStatus() {
        return this.deleteStatus;
    }

    /**
     * Setter for <code>invopay.delivery_point.delete_status</code>.
     */
    public DeliveryPointDTO setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.delivery_point.ref_user_id</code>.
     */
    public Integer getRefUserId() {
        return this.refUserId;
    }

    /**
     * Setter for <code>invopay.delivery_point.ref_user_id</code>.
     */
    public DeliveryPointDTO setRefUserId(Integer refUserId) {
        this.refUserId = refUserId;
        return this;
    }

    /**
     * Getter for <code>invopay.delivery_point.transaction_id</code>.
     */
    public Integer getTransactionId() {
        return this.transactionId;
    }

    /**
     * Setter for <code>invopay.delivery_point.transaction_id</code>.
     */
    public DeliveryPointDTO setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
        return this;
    }

    /**
     * Getter for <code>invopay.delivery_point.added_date</code>.
     */
    public LocalDateTime getAddedDate() {
        return this.addedDate;
    }

    /**
     * Setter for <code>invopay.delivery_point.added_date</code>.
     */
    public DeliveryPointDTO setAddedDate(LocalDateTime addedDate) {
        this.addedDate = addedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final DeliveryPointDTO other = (DeliveryPointDTO) obj;
        if (deliveryPointId == null) {
            if (other.deliveryPointId != null)
                return false;
        }
        else if (!deliveryPointId.equals(other.deliveryPointId))
            return false;
        if (deliveryPointName == null) {
            if (other.deliveryPointName != null)
                return false;
        }
        else if (!deliveryPointName.equals(other.deliveryPointName))
            return false;
        if (deleteStatus == null) {
            if (other.deleteStatus != null)
                return false;
        }
        else if (!deleteStatus.equals(other.deleteStatus))
            return false;
        if (refUserId == null) {
            if (other.refUserId != null)
                return false;
        }
        else if (!refUserId.equals(other.refUserId))
            return false;
        if (transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!transactionId.equals(other.transactionId))
            return false;
        if (addedDate == null) {
            if (other.addedDate != null)
                return false;
        }
        else if (!addedDate.equals(other.addedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.deliveryPointId == null) ? 0 : this.deliveryPointId.hashCode());
        result = prime * result + ((this.deliveryPointName == null) ? 0 : this.deliveryPointName.hashCode());
        result = prime * result + ((this.deleteStatus == null) ? 0 : this.deleteStatus.hashCode());
        result = prime * result + ((this.refUserId == null) ? 0 : this.refUserId.hashCode());
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.addedDate == null) ? 0 : this.addedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DeliveryPoint (");

        sb.append(deliveryPointId);
        sb.append(", ").append(deliveryPointName);
        sb.append(", ").append(deleteStatus);
        sb.append(", ").append(refUserId);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(addedDate);

        sb.append(")");
        return sb.toString();
    }
}
