/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.DTO;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DietproductDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer dietproductId;
    private Integer refDietCategoryId;
    private String  dietproductName;
    private Integer refUserId;
    private Integer deleteStatus;
    private Integer transactionId;
    private Integer addedDate;

    public DietproductDTO() {}

    public DietproductDTO(DietproductDTO value) {
        this.dietproductId = value.dietproductId;
        this.refDietCategoryId = value.refDietCategoryId;
        this.dietproductName = value.dietproductName;
        this.refUserId = value.refUserId;
        this.deleteStatus = value.deleteStatus;
        this.transactionId = value.transactionId;
        this.addedDate = value.addedDate;
    }

    public DietproductDTO(
        Integer dietproductId,
        Integer refDietCategoryId,
        String  dietproductName,
        Integer refUserId,
        Integer deleteStatus,
        Integer transactionId,
        Integer addedDate
    ) {
        this.dietproductId = dietproductId;
        this.refDietCategoryId = refDietCategoryId;
        this.dietproductName = dietproductName;
        this.refUserId = refUserId;
        this.deleteStatus = deleteStatus;
        this.transactionId = transactionId;
        this.addedDate = addedDate;
    }

    /**
     * Getter for <code>invopay.dietproduct.dietproduct_id</code>.
     */
    public Integer getDietproductId() {
        return this.dietproductId;
    }

    /**
     * Setter for <code>invopay.dietproduct.dietproduct_id</code>.
     */
    public DietproductDTO setDietproductId(Integer dietproductId) {
        this.dietproductId = dietproductId;
        return this;
    }

    /**
     * Getter for <code>invopay.dietproduct.ref_diet_category_id</code>.
     */
    public Integer getRefDietCategoryId() {
        return this.refDietCategoryId;
    }

    /**
     * Setter for <code>invopay.dietproduct.ref_diet_category_id</code>.
     */
    public DietproductDTO setRefDietCategoryId(Integer refDietCategoryId) {
        this.refDietCategoryId = refDietCategoryId;
        return this;
    }

    /**
     * Getter for <code>invopay.dietproduct.dietproduct_name</code>. Diet Product Name
     */
    public String getDietproductName() {
        return this.dietproductName;
    }

    /**
     * Setter for <code>invopay.dietproduct.dietproduct_name</code>. Diet Product Name
     */
    public DietproductDTO setDietproductName(String dietproductName) {
        this.dietproductName = dietproductName;
        return this;
    }

    /**
     * Getter for <code>invopay.dietproduct.ref_user_id</code>.
     */
    public Integer getRefUserId() {
        return this.refUserId;
    }

    /**
     * Setter for <code>invopay.dietproduct.ref_user_id</code>.
     */
    public DietproductDTO setRefUserId(Integer refUserId) {
        this.refUserId = refUserId;
        return this;
    }

    /**
     * Getter for <code>invopay.dietproduct.delete_status</code>.
     */
    public Integer getDeleteStatus() {
        return this.deleteStatus;
    }

    /**
     * Setter for <code>invopay.dietproduct.delete_status</code>.
     */
    public DietproductDTO setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.dietproduct.transaction_id</code>.
     */
    public Integer getTransactionId() {
        return this.transactionId;
    }

    /**
     * Setter for <code>invopay.dietproduct.transaction_id</code>.
     */
    public DietproductDTO setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
        return this;
    }

    /**
     * Getter for <code>invopay.dietproduct.added_date</code>.
     */
    public Integer getAddedDate() {
        return this.addedDate;
    }

    /**
     * Setter for <code>invopay.dietproduct.added_date</code>.
     */
    public DietproductDTO setAddedDate(Integer addedDate) {
        this.addedDate = addedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final DietproductDTO other = (DietproductDTO) obj;
        if (dietproductId == null) {
            if (other.dietproductId != null)
                return false;
        }
        else if (!dietproductId.equals(other.dietproductId))
            return false;
        if (refDietCategoryId == null) {
            if (other.refDietCategoryId != null)
                return false;
        }
        else if (!refDietCategoryId.equals(other.refDietCategoryId))
            return false;
        if (dietproductName == null) {
            if (other.dietproductName != null)
                return false;
        }
        else if (!dietproductName.equals(other.dietproductName))
            return false;
        if (refUserId == null) {
            if (other.refUserId != null)
                return false;
        }
        else if (!refUserId.equals(other.refUserId))
            return false;
        if (deleteStatus == null) {
            if (other.deleteStatus != null)
                return false;
        }
        else if (!deleteStatus.equals(other.deleteStatus))
            return false;
        if (transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!transactionId.equals(other.transactionId))
            return false;
        if (addedDate == null) {
            if (other.addedDate != null)
                return false;
        }
        else if (!addedDate.equals(other.addedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.dietproductId == null) ? 0 : this.dietproductId.hashCode());
        result = prime * result + ((this.refDietCategoryId == null) ? 0 : this.refDietCategoryId.hashCode());
        result = prime * result + ((this.dietproductName == null) ? 0 : this.dietproductName.hashCode());
        result = prime * result + ((this.refUserId == null) ? 0 : this.refUserId.hashCode());
        result = prime * result + ((this.deleteStatus == null) ? 0 : this.deleteStatus.hashCode());
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.addedDate == null) ? 0 : this.addedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Dietproduct (");

        sb.append(dietproductId);
        sb.append(", ").append(refDietCategoryId);
        sb.append(", ").append(dietproductName);
        sb.append(", ").append(refUserId);
        sb.append(", ").append(deleteStatus);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(addedDate);

        sb.append(")");
        return sb.toString();
    }
}
