/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.DTO;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DueTypeDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       dueTypeId;
    private String        dueTypeName;
    private Integer       refUserId;
    private Integer       deleteStatus;
    private Integer       transactionId;
    private LocalDateTime addedDate;

    public DueTypeDTO() {}

    public DueTypeDTO(DueTypeDTO value) {
        this.dueTypeId = value.dueTypeId;
        this.dueTypeName = value.dueTypeName;
        this.refUserId = value.refUserId;
        this.deleteStatus = value.deleteStatus;
        this.transactionId = value.transactionId;
        this.addedDate = value.addedDate;
    }

    public DueTypeDTO(
        Integer       dueTypeId,
        String        dueTypeName,
        Integer       refUserId,
        Integer       deleteStatus,
        Integer       transactionId,
        LocalDateTime addedDate
    ) {
        this.dueTypeId = dueTypeId;
        this.dueTypeName = dueTypeName;
        this.refUserId = refUserId;
        this.deleteStatus = deleteStatus;
        this.transactionId = transactionId;
        this.addedDate = addedDate;
    }

    /**
     * Getter for <code>invopay.due_type.due_type_id</code>.
     */
    public Integer getDueTypeId() {
        return this.dueTypeId;
    }

    /**
     * Setter for <code>invopay.due_type.due_type_id</code>.
     */
    public DueTypeDTO setDueTypeId(Integer dueTypeId) {
        this.dueTypeId = dueTypeId;
        return this;
    }

    /**
     * Getter for <code>invopay.due_type.due_type_name</code>.
     */
    public String getDueTypeName() {
        return this.dueTypeName;
    }

    /**
     * Setter for <code>invopay.due_type.due_type_name</code>.
     */
    public DueTypeDTO setDueTypeName(String dueTypeName) {
        this.dueTypeName = dueTypeName;
        return this;
    }

    /**
     * Getter for <code>invopay.due_type.ref_user_id</code>.
     */
    public Integer getRefUserId() {
        return this.refUserId;
    }

    /**
     * Setter for <code>invopay.due_type.ref_user_id</code>.
     */
    public DueTypeDTO setRefUserId(Integer refUserId) {
        this.refUserId = refUserId;
        return this;
    }

    /**
     * Getter for <code>invopay.due_type.delete_status</code>.
     */
    public Integer getDeleteStatus() {
        return this.deleteStatus;
    }

    /**
     * Setter for <code>invopay.due_type.delete_status</code>.
     */
    public DueTypeDTO setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.due_type.transaction_id</code>.
     */
    public Integer getTransactionId() {
        return this.transactionId;
    }

    /**
     * Setter for <code>invopay.due_type.transaction_id</code>.
     */
    public DueTypeDTO setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
        return this;
    }

    /**
     * Getter for <code>invopay.due_type.added_date</code>.
     */
    public LocalDateTime getAddedDate() {
        return this.addedDate;
    }

    /**
     * Setter for <code>invopay.due_type.added_date</code>.
     */
    public DueTypeDTO setAddedDate(LocalDateTime addedDate) {
        this.addedDate = addedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final DueTypeDTO other = (DueTypeDTO) obj;
        if (dueTypeId == null) {
            if (other.dueTypeId != null)
                return false;
        }
        else if (!dueTypeId.equals(other.dueTypeId))
            return false;
        if (dueTypeName == null) {
            if (other.dueTypeName != null)
                return false;
        }
        else if (!dueTypeName.equals(other.dueTypeName))
            return false;
        if (refUserId == null) {
            if (other.refUserId != null)
                return false;
        }
        else if (!refUserId.equals(other.refUserId))
            return false;
        if (deleteStatus == null) {
            if (other.deleteStatus != null)
                return false;
        }
        else if (!deleteStatus.equals(other.deleteStatus))
            return false;
        if (transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!transactionId.equals(other.transactionId))
            return false;
        if (addedDate == null) {
            if (other.addedDate != null)
                return false;
        }
        else if (!addedDate.equals(other.addedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.dueTypeId == null) ? 0 : this.dueTypeId.hashCode());
        result = prime * result + ((this.dueTypeName == null) ? 0 : this.dueTypeName.hashCode());
        result = prime * result + ((this.refUserId == null) ? 0 : this.refUserId.hashCode());
        result = prime * result + ((this.deleteStatus == null) ? 0 : this.deleteStatus.hashCode());
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.addedDate == null) ? 0 : this.addedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DueType (");

        sb.append(dueTypeId);
        sb.append(", ").append(dueTypeName);
        sb.append(", ").append(refUserId);
        sb.append(", ").append(deleteStatus);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(addedDate);

        sb.append(")");
        return sb.toString();
    }
}
