/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.DTO;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DummyProductDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        allValues;
    private LocalDateTime addedDate;

    public DummyProductDTO() {}

    public DummyProductDTO(DummyProductDTO value) {
        this.id = value.id;
        this.allValues = value.allValues;
        this.addedDate = value.addedDate;
    }

    public DummyProductDTO(
        Integer       id,
        String        allValues,
        LocalDateTime addedDate
    ) {
        this.id = id;
        this.allValues = allValues;
        this.addedDate = addedDate;
    }

    /**
     * Getter for <code>invopay.dummy_product.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>invopay.dummy_product.id</code>.
     */
    public DummyProductDTO setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>invopay.dummy_product.all_values</code>.
     */
    public String getAllValues() {
        return this.allValues;
    }

    /**
     * Setter for <code>invopay.dummy_product.all_values</code>.
     */
    public DummyProductDTO setAllValues(String allValues) {
        this.allValues = allValues;
        return this;
    }

    /**
     * Getter for <code>invopay.dummy_product.added_date</code>.
     */
    public LocalDateTime getAddedDate() {
        return this.addedDate;
    }

    /**
     * Setter for <code>invopay.dummy_product.added_date</code>.
     */
    public DummyProductDTO setAddedDate(LocalDateTime addedDate) {
        this.addedDate = addedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final DummyProductDTO other = (DummyProductDTO) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (allValues == null) {
            if (other.allValues != null)
                return false;
        }
        else if (!allValues.equals(other.allValues))
            return false;
        if (addedDate == null) {
            if (other.addedDate != null)
                return false;
        }
        else if (!addedDate.equals(other.addedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.allValues == null) ? 0 : this.allValues.hashCode());
        result = prime * result + ((this.addedDate == null) ? 0 : this.addedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DummyProduct (");

        sb.append(id);
        sb.append(", ").append(allValues);
        sb.append(", ").append(addedDate);

        sb.append(")");
        return sb.toString();
    }
}
