/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.DTO;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeedbackDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       feedbackId;
    private String        feedbackName;
    private Integer       deleteStatus;
    private Integer       refUserId;
    private Integer       transactionId;
    private LocalDateTime addedDate;

    public FeedbackDTO() {}

    public FeedbackDTO(FeedbackDTO value) {
        this.feedbackId = value.feedbackId;
        this.feedbackName = value.feedbackName;
        this.deleteStatus = value.deleteStatus;
        this.refUserId = value.refUserId;
        this.transactionId = value.transactionId;
        this.addedDate = value.addedDate;
    }

    public FeedbackDTO(
        Integer       feedbackId,
        String        feedbackName,
        Integer       deleteStatus,
        Integer       refUserId,
        Integer       transactionId,
        LocalDateTime addedDate
    ) {
        this.feedbackId = feedbackId;
        this.feedbackName = feedbackName;
        this.deleteStatus = deleteStatus;
        this.refUserId = refUserId;
        this.transactionId = transactionId;
        this.addedDate = addedDate;
    }

    /**
     * Getter for <code>invopay.feedback.feedback_id</code>.
     */
    public Integer getFeedbackId() {
        return this.feedbackId;
    }

    /**
     * Setter for <code>invopay.feedback.feedback_id</code>.
     */
    public FeedbackDTO setFeedbackId(Integer feedbackId) {
        this.feedbackId = feedbackId;
        return this;
    }

    /**
     * Getter for <code>invopay.feedback.feedback_name</code>.
     */
    public String getFeedbackName() {
        return this.feedbackName;
    }

    /**
     * Setter for <code>invopay.feedback.feedback_name</code>.
     */
    public FeedbackDTO setFeedbackName(String feedbackName) {
        this.feedbackName = feedbackName;
        return this;
    }

    /**
     * Getter for <code>invopay.feedback.delete_status</code>.
     */
    public Integer getDeleteStatus() {
        return this.deleteStatus;
    }

    /**
     * Setter for <code>invopay.feedback.delete_status</code>.
     */
    public FeedbackDTO setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.feedback.ref_user_id</code>.
     */
    public Integer getRefUserId() {
        return this.refUserId;
    }

    /**
     * Setter for <code>invopay.feedback.ref_user_id</code>.
     */
    public FeedbackDTO setRefUserId(Integer refUserId) {
        this.refUserId = refUserId;
        return this;
    }

    /**
     * Getter for <code>invopay.feedback.transaction_id</code>.
     */
    public Integer getTransactionId() {
        return this.transactionId;
    }

    /**
     * Setter for <code>invopay.feedback.transaction_id</code>.
     */
    public FeedbackDTO setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
        return this;
    }

    /**
     * Getter for <code>invopay.feedback.added_date</code>.
     */
    public LocalDateTime getAddedDate() {
        return this.addedDate;
    }

    /**
     * Setter for <code>invopay.feedback.added_date</code>.
     */
    public FeedbackDTO setAddedDate(LocalDateTime addedDate) {
        this.addedDate = addedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final FeedbackDTO other = (FeedbackDTO) obj;
        if (feedbackId == null) {
            if (other.feedbackId != null)
                return false;
        }
        else if (!feedbackId.equals(other.feedbackId))
            return false;
        if (feedbackName == null) {
            if (other.feedbackName != null)
                return false;
        }
        else if (!feedbackName.equals(other.feedbackName))
            return false;
        if (deleteStatus == null) {
            if (other.deleteStatus != null)
                return false;
        }
        else if (!deleteStatus.equals(other.deleteStatus))
            return false;
        if (refUserId == null) {
            if (other.refUserId != null)
                return false;
        }
        else if (!refUserId.equals(other.refUserId))
            return false;
        if (transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!transactionId.equals(other.transactionId))
            return false;
        if (addedDate == null) {
            if (other.addedDate != null)
                return false;
        }
        else if (!addedDate.equals(other.addedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.feedbackId == null) ? 0 : this.feedbackId.hashCode());
        result = prime * result + ((this.feedbackName == null) ? 0 : this.feedbackName.hashCode());
        result = prime * result + ((this.deleteStatus == null) ? 0 : this.deleteStatus.hashCode());
        result = prime * result + ((this.refUserId == null) ? 0 : this.refUserId.hashCode());
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.addedDate == null) ? 0 : this.addedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Feedback (");

        sb.append(feedbackId);
        sb.append(", ").append(feedbackName);
        sb.append(", ").append(deleteStatus);
        sb.append(", ").append(refUserId);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(addedDate);

        sb.append(")");
        return sb.toString();
    }
}
