/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.DTO;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilterOprationDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer filterOprationId;
    private String  filterOperationDetails;

    public FilterOprationDTO() {}

    public FilterOprationDTO(FilterOprationDTO value) {
        this.filterOprationId = value.filterOprationId;
        this.filterOperationDetails = value.filterOperationDetails;
    }

    public FilterOprationDTO(
        Integer filterOprationId,
        String  filterOperationDetails
    ) {
        this.filterOprationId = filterOprationId;
        this.filterOperationDetails = filterOperationDetails;
    }

    /**
     * Getter for <code>invopay.filter_opration.filter_opration_id</code>.
     */
    public Integer getFilterOprationId() {
        return this.filterOprationId;
    }

    /**
     * Setter for <code>invopay.filter_opration.filter_opration_id</code>.
     */
    public FilterOprationDTO setFilterOprationId(Integer filterOprationId) {
        this.filterOprationId = filterOprationId;
        return this;
    }

    /**
     * Getter for <code>invopay.filter_opration.filter_operation_details</code>.
     */
    public String getFilterOperationDetails() {
        return this.filterOperationDetails;
    }

    /**
     * Setter for <code>invopay.filter_opration.filter_operation_details</code>.
     */
    public FilterOprationDTO setFilterOperationDetails(String filterOperationDetails) {
        this.filterOperationDetails = filterOperationDetails;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final FilterOprationDTO other = (FilterOprationDTO) obj;
        if (filterOprationId == null) {
            if (other.filterOprationId != null)
                return false;
        }
        else if (!filterOprationId.equals(other.filterOprationId))
            return false;
        if (filterOperationDetails == null) {
            if (other.filterOperationDetails != null)
                return false;
        }
        else if (!filterOperationDetails.equals(other.filterOperationDetails))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.filterOprationId == null) ? 0 : this.filterOprationId.hashCode());
        result = prime * result + ((this.filterOperationDetails == null) ? 0 : this.filterOperationDetails.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FilterOpration (");

        sb.append(filterOprationId);
        sb.append(", ").append(filterOperationDetails);

        sb.append(")");
        return sb.toString();
    }
}
