/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.DTO;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GstTypeDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       gstTypeId;
    private String        gstTypeName;
    private Integer       gstPerc;
    private Integer       refUserId;
    private Integer       deleteStatus;
    private Integer       transactionId;
    private LocalDateTime addedDate;

    public GstTypeDTO() {}

    public GstTypeDTO(GstTypeDTO value) {
        this.gstTypeId = value.gstTypeId;
        this.gstTypeName = value.gstTypeName;
        this.gstPerc = value.gstPerc;
        this.refUserId = value.refUserId;
        this.deleteStatus = value.deleteStatus;
        this.transactionId = value.transactionId;
        this.addedDate = value.addedDate;
    }

    public GstTypeDTO(
        Integer       gstTypeId,
        String        gstTypeName,
        Integer       gstPerc,
        Integer       refUserId,
        Integer       deleteStatus,
        Integer       transactionId,
        LocalDateTime addedDate
    ) {
        this.gstTypeId = gstTypeId;
        this.gstTypeName = gstTypeName;
        this.gstPerc = gstPerc;
        this.refUserId = refUserId;
        this.deleteStatus = deleteStatus;
        this.transactionId = transactionId;
        this.addedDate = addedDate;
    }

    /**
     * Getter for <code>invopay.gst_type.gst_type_id</code>.
     */
    public Integer getGstTypeId() {
        return this.gstTypeId;
    }

    /**
     * Setter for <code>invopay.gst_type.gst_type_id</code>.
     */
    public GstTypeDTO setGstTypeId(Integer gstTypeId) {
        this.gstTypeId = gstTypeId;
        return this;
    }

    /**
     * Getter for <code>invopay.gst_type.gst_type_name</code>.
     */
    public String getGstTypeName() {
        return this.gstTypeName;
    }

    /**
     * Setter for <code>invopay.gst_type.gst_type_name</code>.
     */
    public GstTypeDTO setGstTypeName(String gstTypeName) {
        this.gstTypeName = gstTypeName;
        return this;
    }

    /**
     * Getter for <code>invopay.gst_type.gst_perc</code>.
     */
    public Integer getGstPerc() {
        return this.gstPerc;
    }

    /**
     * Setter for <code>invopay.gst_type.gst_perc</code>.
     */
    public GstTypeDTO setGstPerc(Integer gstPerc) {
        this.gstPerc = gstPerc;
        return this;
    }

    /**
     * Getter for <code>invopay.gst_type.ref_user_id</code>.
     */
    public Integer getRefUserId() {
        return this.refUserId;
    }

    /**
     * Setter for <code>invopay.gst_type.ref_user_id</code>.
     */
    public GstTypeDTO setRefUserId(Integer refUserId) {
        this.refUserId = refUserId;
        return this;
    }

    /**
     * Getter for <code>invopay.gst_type.delete_status</code>.
     */
    public Integer getDeleteStatus() {
        return this.deleteStatus;
    }

    /**
     * Setter for <code>invopay.gst_type.delete_status</code>.
     */
    public GstTypeDTO setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.gst_type.transaction_id</code>.
     */
    public Integer getTransactionId() {
        return this.transactionId;
    }

    /**
     * Setter for <code>invopay.gst_type.transaction_id</code>.
     */
    public GstTypeDTO setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
        return this;
    }

    /**
     * Getter for <code>invopay.gst_type.added_date</code>.
     */
    public LocalDateTime getAddedDate() {
        return this.addedDate;
    }

    /**
     * Setter for <code>invopay.gst_type.added_date</code>.
     */
    public GstTypeDTO setAddedDate(LocalDateTime addedDate) {
        this.addedDate = addedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final GstTypeDTO other = (GstTypeDTO) obj;
        if (gstTypeId == null) {
            if (other.gstTypeId != null)
                return false;
        }
        else if (!gstTypeId.equals(other.gstTypeId))
            return false;
        if (gstTypeName == null) {
            if (other.gstTypeName != null)
                return false;
        }
        else if (!gstTypeName.equals(other.gstTypeName))
            return false;
        if (gstPerc == null) {
            if (other.gstPerc != null)
                return false;
        }
        else if (!gstPerc.equals(other.gstPerc))
            return false;
        if (refUserId == null) {
            if (other.refUserId != null)
                return false;
        }
        else if (!refUserId.equals(other.refUserId))
            return false;
        if (deleteStatus == null) {
            if (other.deleteStatus != null)
                return false;
        }
        else if (!deleteStatus.equals(other.deleteStatus))
            return false;
        if (transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!transactionId.equals(other.transactionId))
            return false;
        if (addedDate == null) {
            if (other.addedDate != null)
                return false;
        }
        else if (!addedDate.equals(other.addedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.gstTypeId == null) ? 0 : this.gstTypeId.hashCode());
        result = prime * result + ((this.gstTypeName == null) ? 0 : this.gstTypeName.hashCode());
        result = prime * result + ((this.gstPerc == null) ? 0 : this.gstPerc.hashCode());
        result = prime * result + ((this.refUserId == null) ? 0 : this.refUserId.hashCode());
        result = prime * result + ((this.deleteStatus == null) ? 0 : this.deleteStatus.hashCode());
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.addedDate == null) ? 0 : this.addedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GstType (");

        sb.append(gstTypeId);
        sb.append(", ").append(gstTypeName);
        sb.append(", ").append(gstPerc);
        sb.append(", ").append(refUserId);
        sb.append(", ").append(deleteStatus);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(addedDate);

        sb.append(")");
        return sb.toString();
    }
}
