/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.DTO;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InvoiceParticularsDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       invoiceParticularsId;
    private String        invoiceParticularsName;
    private Integer       refInvoiceId;
    private Integer       refProductId;
    private String        productName;
    private String        productDescription;
    private Integer       refProductBatchId;
    private Double        price;
    private Integer       refDiscountTypeId;
    private Long          discountValue;
    private Double        discountTotal;
    private Integer       qty;
    private Integer       refQuantityTypeId;
    private Double        gstPerc;
    private Double        subTotal;
    private Double        gst;
    private Double        total;
    private Integer       refUserId;
    private Integer       deleteStatus;
    private Integer       transactionId;
    private LocalDateTime addedDate;
    private Long          supplierCommPerc;
    private Long          supplierCommTotal;

    public InvoiceParticularsDTO() {}

    public InvoiceParticularsDTO(InvoiceParticularsDTO value) {
        this.invoiceParticularsId = value.invoiceParticularsId;
        this.invoiceParticularsName = value.invoiceParticularsName;
        this.refInvoiceId = value.refInvoiceId;
        this.refProductId = value.refProductId;
        this.productName = value.productName;
        this.productDescription = value.productDescription;
        this.refProductBatchId = value.refProductBatchId;
        this.price = value.price;
        this.refDiscountTypeId = value.refDiscountTypeId;
        this.discountValue = value.discountValue;
        this.discountTotal = value.discountTotal;
        this.qty = value.qty;
        this.refQuantityTypeId = value.refQuantityTypeId;
        this.gstPerc = value.gstPerc;
        this.subTotal = value.subTotal;
        this.gst = value.gst;
        this.total = value.total;
        this.refUserId = value.refUserId;
        this.deleteStatus = value.deleteStatus;
        this.transactionId = value.transactionId;
        this.addedDate = value.addedDate;
        this.supplierCommPerc = value.supplierCommPerc;
        this.supplierCommTotal = value.supplierCommTotal;
    }

    public InvoiceParticularsDTO(
        Integer       invoiceParticularsId,
        String        invoiceParticularsName,
        Integer       refInvoiceId,
        Integer       refProductId,
        String        productName,
        String        productDescription,
        Integer       refProductBatchId,
        Double        price,
        Integer       refDiscountTypeId,
        Long          discountValue,
        Double        discountTotal,
        Integer       qty,
        Integer       refQuantityTypeId,
        Double        gstPerc,
        Double        subTotal,
        Double        gst,
        Double        total,
        Integer       refUserId,
        Integer       deleteStatus,
        Integer       transactionId,
        LocalDateTime addedDate,
        Long          supplierCommPerc,
        Long          supplierCommTotal
    ) {
        this.invoiceParticularsId = invoiceParticularsId;
        this.invoiceParticularsName = invoiceParticularsName;
        this.refInvoiceId = refInvoiceId;
        this.refProductId = refProductId;
        this.productName = productName;
        this.productDescription = productDescription;
        this.refProductBatchId = refProductBatchId;
        this.price = price;
        this.refDiscountTypeId = refDiscountTypeId;
        this.discountValue = discountValue;
        this.discountTotal = discountTotal;
        this.qty = qty;
        this.refQuantityTypeId = refQuantityTypeId;
        this.gstPerc = gstPerc;
        this.subTotal = subTotal;
        this.gst = gst;
        this.total = total;
        this.refUserId = refUserId;
        this.deleteStatus = deleteStatus;
        this.transactionId = transactionId;
        this.addedDate = addedDate;
        this.supplierCommPerc = supplierCommPerc;
        this.supplierCommTotal = supplierCommTotal;
    }

    /**
     * Getter for <code>invopay.invoice_particulars.invoice_particulars_id</code>.
     */
    public Integer getInvoiceParticularsId() {
        return this.invoiceParticularsId;
    }

    /**
     * Setter for <code>invopay.invoice_particulars.invoice_particulars_id</code>.
     */
    public InvoiceParticularsDTO setInvoiceParticularsId(Integer invoiceParticularsId) {
        this.invoiceParticularsId = invoiceParticularsId;
        return this;
    }

    /**
     * Getter for <code>invopay.invoice_particulars.invoice_particulars_name</code>.
     */
    public String getInvoiceParticularsName() {
        return this.invoiceParticularsName;
    }

    /**
     * Setter for <code>invopay.invoice_particulars.invoice_particulars_name</code>.
     */
    public InvoiceParticularsDTO setInvoiceParticularsName(String invoiceParticularsName) {
        this.invoiceParticularsName = invoiceParticularsName;
        return this;
    }

    /**
     * Getter for <code>invopay.invoice_particulars.ref_invoice_id</code>.
     */
    public Integer getRefInvoiceId() {
        return this.refInvoiceId;
    }

    /**
     * Setter for <code>invopay.invoice_particulars.ref_invoice_id</code>.
     */
    public InvoiceParticularsDTO setRefInvoiceId(Integer refInvoiceId) {
        this.refInvoiceId = refInvoiceId;
        return this;
    }

    /**
     * Getter for <code>invopay.invoice_particulars.ref_product_id</code>.
     */
    public Integer getRefProductId() {
        return this.refProductId;
    }

    /**
     * Setter for <code>invopay.invoice_particulars.ref_product_id</code>.
     */
    public InvoiceParticularsDTO setRefProductId(Integer refProductId) {
        this.refProductId = refProductId;
        return this;
    }

    /**
     * Getter for <code>invopay.invoice_particulars.product_name</code>.
     */
    public String getProductName() {
        return this.productName;
    }

    /**
     * Setter for <code>invopay.invoice_particulars.product_name</code>.
     */
    public InvoiceParticularsDTO setProductName(String productName) {
        this.productName = productName;
        return this;
    }

    /**
     * Getter for <code>invopay.invoice_particulars.product_description</code>.
     */
    public String getProductDescription() {
        return this.productDescription;
    }

    /**
     * Setter for <code>invopay.invoice_particulars.product_description</code>.
     */
    public InvoiceParticularsDTO setProductDescription(String productDescription) {
        this.productDescription = productDescription;
        return this;
    }

    /**
     * Getter for <code>invopay.invoice_particulars.ref_product_batch_id</code>.
     */
    public Integer getRefProductBatchId() {
        return this.refProductBatchId;
    }

    /**
     * Setter for <code>invopay.invoice_particulars.ref_product_batch_id</code>.
     */
    public InvoiceParticularsDTO setRefProductBatchId(Integer refProductBatchId) {
        this.refProductBatchId = refProductBatchId;
        return this;
    }

    /**
     * Getter for <code>invopay.invoice_particulars.price</code>.
     */
    public Double getPrice() {
        return this.price;
    }

    /**
     * Setter for <code>invopay.invoice_particulars.price</code>.
     */
    public InvoiceParticularsDTO setPrice(Double price) {
        this.price = price;
        return this;
    }

    /**
     * Getter for <code>invopay.invoice_particulars.ref_discount_type_id</code>.
     */
    public Integer getRefDiscountTypeId() {
        return this.refDiscountTypeId;
    }

    /**
     * Setter for <code>invopay.invoice_particulars.ref_discount_type_id</code>.
     */
    public InvoiceParticularsDTO setRefDiscountTypeId(Integer refDiscountTypeId) {
        this.refDiscountTypeId = refDiscountTypeId;
        return this;
    }

    /**
     * Getter for <code>invopay.invoice_particulars.discount_value</code>.
     */
    public Long getDiscountValue() {
        return this.discountValue;
    }

    /**
     * Setter for <code>invopay.invoice_particulars.discount_value</code>.
     */
    public InvoiceParticularsDTO setDiscountValue(Long discountValue) {
        this.discountValue = discountValue;
        return this;
    }

    /**
     * Getter for <code>invopay.invoice_particulars.discount_total</code>.
     */
    public Double getDiscountTotal() {
        return this.discountTotal;
    }

    /**
     * Setter for <code>invopay.invoice_particulars.discount_total</code>.
     */
    public InvoiceParticularsDTO setDiscountTotal(Double discountTotal) {
        this.discountTotal = discountTotal;
        return this;
    }

    /**
     * Getter for <code>invopay.invoice_particulars.qty</code>.
     */
    public Integer getQty() {
        return this.qty;
    }

    /**
     * Setter for <code>invopay.invoice_particulars.qty</code>.
     */
    public InvoiceParticularsDTO setQty(Integer qty) {
        this.qty = qty;
        return this;
    }

    /**
     * Getter for <code>invopay.invoice_particulars.ref_quantity_type_id</code>.
     */
    public Integer getRefQuantityTypeId() {
        return this.refQuantityTypeId;
    }

    /**
     * Setter for <code>invopay.invoice_particulars.ref_quantity_type_id</code>.
     */
    public InvoiceParticularsDTO setRefQuantityTypeId(Integer refQuantityTypeId) {
        this.refQuantityTypeId = refQuantityTypeId;
        return this;
    }

    /**
     * Getter for <code>invopay.invoice_particulars.gst_perc</code>.
     */
    public Double getGstPerc() {
        return this.gstPerc;
    }

    /**
     * Setter for <code>invopay.invoice_particulars.gst_perc</code>.
     */
    public InvoiceParticularsDTO setGstPerc(Double gstPerc) {
        this.gstPerc = gstPerc;
        return this;
    }

    /**
     * Getter for <code>invopay.invoice_particulars.sub_total</code>.
     */
    public Double getSubTotal() {
        return this.subTotal;
    }

    /**
     * Setter for <code>invopay.invoice_particulars.sub_total</code>.
     */
    public InvoiceParticularsDTO setSubTotal(Double subTotal) {
        this.subTotal = subTotal;
        return this;
    }

    /**
     * Getter for <code>invopay.invoice_particulars.gst</code>.
     */
    public Double getGst() {
        return this.gst;
    }

    /**
     * Setter for <code>invopay.invoice_particulars.gst</code>.
     */
    public InvoiceParticularsDTO setGst(Double gst) {
        this.gst = gst;
        return this;
    }

    /**
     * Getter for <code>invopay.invoice_particulars.total</code>.
     */
    public Double getTotal() {
        return this.total;
    }

    /**
     * Setter for <code>invopay.invoice_particulars.total</code>.
     */
    public InvoiceParticularsDTO setTotal(Double total) {
        this.total = total;
        return this;
    }

    /**
     * Getter for <code>invopay.invoice_particulars.ref_user_id</code>. User
     */
    public Integer getRefUserId() {
        return this.refUserId;
    }

    /**
     * Setter for <code>invopay.invoice_particulars.ref_user_id</code>. User
     */
    public InvoiceParticularsDTO setRefUserId(Integer refUserId) {
        this.refUserId = refUserId;
        return this;
    }

    /**
     * Getter for <code>invopay.invoice_particulars.delete_status</code>.
     */
    public Integer getDeleteStatus() {
        return this.deleteStatus;
    }

    /**
     * Setter for <code>invopay.invoice_particulars.delete_status</code>.
     */
    public InvoiceParticularsDTO setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.invoice_particulars.transaction_id</code>.
     */
    public Integer getTransactionId() {
        return this.transactionId;
    }

    /**
     * Setter for <code>invopay.invoice_particulars.transaction_id</code>.
     */
    public InvoiceParticularsDTO setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
        return this;
    }

    /**
     * Getter for <code>invopay.invoice_particulars.added_date</code>. Added Date
     */
    public LocalDateTime getAddedDate() {
        return this.addedDate;
    }

    /**
     * Setter for <code>invopay.invoice_particulars.added_date</code>. Added Date
     */
    public InvoiceParticularsDTO setAddedDate(LocalDateTime addedDate) {
        this.addedDate = addedDate;
        return this;
    }

    /**
     * Getter for <code>invopay.invoice_particulars.supplier_comm_perc</code>.
     */
    public Long getSupplierCommPerc() {
        return this.supplierCommPerc;
    }

    /**
     * Setter for <code>invopay.invoice_particulars.supplier_comm_perc</code>.
     */
    public InvoiceParticularsDTO setSupplierCommPerc(Long supplierCommPerc) {
        this.supplierCommPerc = supplierCommPerc;
        return this;
    }

    /**
     * Getter for <code>invopay.invoice_particulars.supplier_comm_total</code>.
     */
    public Long getSupplierCommTotal() {
        return this.supplierCommTotal;
    }

    /**
     * Setter for <code>invopay.invoice_particulars.supplier_comm_total</code>.
     */
    public InvoiceParticularsDTO setSupplierCommTotal(Long supplierCommTotal) {
        this.supplierCommTotal = supplierCommTotal;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final InvoiceParticularsDTO other = (InvoiceParticularsDTO) obj;
        if (invoiceParticularsId == null) {
            if (other.invoiceParticularsId != null)
                return false;
        }
        else if (!invoiceParticularsId.equals(other.invoiceParticularsId))
            return false;
        if (invoiceParticularsName == null) {
            if (other.invoiceParticularsName != null)
                return false;
        }
        else if (!invoiceParticularsName.equals(other.invoiceParticularsName))
            return false;
        if (refInvoiceId == null) {
            if (other.refInvoiceId != null)
                return false;
        }
        else if (!refInvoiceId.equals(other.refInvoiceId))
            return false;
        if (refProductId == null) {
            if (other.refProductId != null)
                return false;
        }
        else if (!refProductId.equals(other.refProductId))
            return false;
        if (productName == null) {
            if (other.productName != null)
                return false;
        }
        else if (!productName.equals(other.productName))
            return false;
        if (productDescription == null) {
            if (other.productDescription != null)
                return false;
        }
        else if (!productDescription.equals(other.productDescription))
            return false;
        if (refProductBatchId == null) {
            if (other.refProductBatchId != null)
                return false;
        }
        else if (!refProductBatchId.equals(other.refProductBatchId))
            return false;
        if (price == null) {
            if (other.price != null)
                return false;
        }
        else if (!price.equals(other.price))
            return false;
        if (refDiscountTypeId == null) {
            if (other.refDiscountTypeId != null)
                return false;
        }
        else if (!refDiscountTypeId.equals(other.refDiscountTypeId))
            return false;
        if (discountValue == null) {
            if (other.discountValue != null)
                return false;
        }
        else if (!discountValue.equals(other.discountValue))
            return false;
        if (discountTotal == null) {
            if (other.discountTotal != null)
                return false;
        }
        else if (!discountTotal.equals(other.discountTotal))
            return false;
        if (qty == null) {
            if (other.qty != null)
                return false;
        }
        else if (!qty.equals(other.qty))
            return false;
        if (refQuantityTypeId == null) {
            if (other.refQuantityTypeId != null)
                return false;
        }
        else if (!refQuantityTypeId.equals(other.refQuantityTypeId))
            return false;
        if (gstPerc == null) {
            if (other.gstPerc != null)
                return false;
        }
        else if (!gstPerc.equals(other.gstPerc))
            return false;
        if (subTotal == null) {
            if (other.subTotal != null)
                return false;
        }
        else if (!subTotal.equals(other.subTotal))
            return false;
        if (gst == null) {
            if (other.gst != null)
                return false;
        }
        else if (!gst.equals(other.gst))
            return false;
        if (total == null) {
            if (other.total != null)
                return false;
        }
        else if (!total.equals(other.total))
            return false;
        if (refUserId == null) {
            if (other.refUserId != null)
                return false;
        }
        else if (!refUserId.equals(other.refUserId))
            return false;
        if (deleteStatus == null) {
            if (other.deleteStatus != null)
                return false;
        }
        else if (!deleteStatus.equals(other.deleteStatus))
            return false;
        if (transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!transactionId.equals(other.transactionId))
            return false;
        if (addedDate == null) {
            if (other.addedDate != null)
                return false;
        }
        else if (!addedDate.equals(other.addedDate))
            return false;
        if (supplierCommPerc == null) {
            if (other.supplierCommPerc != null)
                return false;
        }
        else if (!supplierCommPerc.equals(other.supplierCommPerc))
            return false;
        if (supplierCommTotal == null) {
            if (other.supplierCommTotal != null)
                return false;
        }
        else if (!supplierCommTotal.equals(other.supplierCommTotal))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.invoiceParticularsId == null) ? 0 : this.invoiceParticularsId.hashCode());
        result = prime * result + ((this.invoiceParticularsName == null) ? 0 : this.invoiceParticularsName.hashCode());
        result = prime * result + ((this.refInvoiceId == null) ? 0 : this.refInvoiceId.hashCode());
        result = prime * result + ((this.refProductId == null) ? 0 : this.refProductId.hashCode());
        result = prime * result + ((this.productName == null) ? 0 : this.productName.hashCode());
        result = prime * result + ((this.productDescription == null) ? 0 : this.productDescription.hashCode());
        result = prime * result + ((this.refProductBatchId == null) ? 0 : this.refProductBatchId.hashCode());
        result = prime * result + ((this.price == null) ? 0 : this.price.hashCode());
        result = prime * result + ((this.refDiscountTypeId == null) ? 0 : this.refDiscountTypeId.hashCode());
        result = prime * result + ((this.discountValue == null) ? 0 : this.discountValue.hashCode());
        result = prime * result + ((this.discountTotal == null) ? 0 : this.discountTotal.hashCode());
        result = prime * result + ((this.qty == null) ? 0 : this.qty.hashCode());
        result = prime * result + ((this.refQuantityTypeId == null) ? 0 : this.refQuantityTypeId.hashCode());
        result = prime * result + ((this.gstPerc == null) ? 0 : this.gstPerc.hashCode());
        result = prime * result + ((this.subTotal == null) ? 0 : this.subTotal.hashCode());
        result = prime * result + ((this.gst == null) ? 0 : this.gst.hashCode());
        result = prime * result + ((this.total == null) ? 0 : this.total.hashCode());
        result = prime * result + ((this.refUserId == null) ? 0 : this.refUserId.hashCode());
        result = prime * result + ((this.deleteStatus == null) ? 0 : this.deleteStatus.hashCode());
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.addedDate == null) ? 0 : this.addedDate.hashCode());
        result = prime * result + ((this.supplierCommPerc == null) ? 0 : this.supplierCommPerc.hashCode());
        result = prime * result + ((this.supplierCommTotal == null) ? 0 : this.supplierCommTotal.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InvoiceParticulars (");

        sb.append(invoiceParticularsId);
        sb.append(", ").append(invoiceParticularsName);
        sb.append(", ").append(refInvoiceId);
        sb.append(", ").append(refProductId);
        sb.append(", ").append(productName);
        sb.append(", ").append(productDescription);
        sb.append(", ").append(refProductBatchId);
        sb.append(", ").append(price);
        sb.append(", ").append(refDiscountTypeId);
        sb.append(", ").append(discountValue);
        sb.append(", ").append(discountTotal);
        sb.append(", ").append(qty);
        sb.append(", ").append(refQuantityTypeId);
        sb.append(", ").append(gstPerc);
        sb.append(", ").append(subTotal);
        sb.append(", ").append(gst);
        sb.append(", ").append(total);
        sb.append(", ").append(refUserId);
        sb.append(", ").append(deleteStatus);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(addedDate);
        sb.append(", ").append(supplierCommPerc);
        sb.append(", ").append(supplierCommTotal);

        sb.append(")");
        return sb.toString();
    }
}
