/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.DTO;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LeadRemarkDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       leadRemarkId;
    private Integer       refLeadId;
    private LocalDateTime leadRemarkDateAndTime;
    private String        leadRemarkType;
    private String        leadRemarkDetails;
    private Integer       refUserId;
    private Integer       deleteStatus;
    private Integer       transactionId;
    private LocalDateTime addedDate;

    public LeadRemarkDTO() {}

    public LeadRemarkDTO(LeadRemarkDTO value) {
        this.leadRemarkId = value.leadRemarkId;
        this.refLeadId = value.refLeadId;
        this.leadRemarkDateAndTime = value.leadRemarkDateAndTime;
        this.leadRemarkType = value.leadRemarkType;
        this.leadRemarkDetails = value.leadRemarkDetails;
        this.refUserId = value.refUserId;
        this.deleteStatus = value.deleteStatus;
        this.transactionId = value.transactionId;
        this.addedDate = value.addedDate;
    }

    public LeadRemarkDTO(
        Integer       leadRemarkId,
        Integer       refLeadId,
        LocalDateTime leadRemarkDateAndTime,
        String        leadRemarkType,
        String        leadRemarkDetails,
        Integer       refUserId,
        Integer       deleteStatus,
        Integer       transactionId,
        LocalDateTime addedDate
    ) {
        this.leadRemarkId = leadRemarkId;
        this.refLeadId = refLeadId;
        this.leadRemarkDateAndTime = leadRemarkDateAndTime;
        this.leadRemarkType = leadRemarkType;
        this.leadRemarkDetails = leadRemarkDetails;
        this.refUserId = refUserId;
        this.deleteStatus = deleteStatus;
        this.transactionId = transactionId;
        this.addedDate = addedDate;
    }

    /**
     * Getter for <code>invopay.lead_remark.lead_remark_id</code>.
     */
    public Integer getLeadRemarkId() {
        return this.leadRemarkId;
    }

    /**
     * Setter for <code>invopay.lead_remark.lead_remark_id</code>.
     */
    public LeadRemarkDTO setLeadRemarkId(Integer leadRemarkId) {
        this.leadRemarkId = leadRemarkId;
        return this;
    }

    /**
     * Getter for <code>invopay.lead_remark.ref_lead_id</code>. Lead
     */
    public Integer getRefLeadId() {
        return this.refLeadId;
    }

    /**
     * Setter for <code>invopay.lead_remark.ref_lead_id</code>. Lead
     */
    public LeadRemarkDTO setRefLeadId(Integer refLeadId) {
        this.refLeadId = refLeadId;
        return this;
    }

    /**
     * Getter for <code>invopay.lead_remark.lead_remark_date_and_time</code>. Date
     */
    public LocalDateTime getLeadRemarkDateAndTime() {
        return this.leadRemarkDateAndTime;
    }

    /**
     * Setter for <code>invopay.lead_remark.lead_remark_date_and_time</code>. Date
     */
    public LeadRemarkDTO setLeadRemarkDateAndTime(LocalDateTime leadRemarkDateAndTime) {
        this.leadRemarkDateAndTime = leadRemarkDateAndTime;
        return this;
    }

    /**
     * Getter for <code>invopay.lead_remark.lead_remark_type</code>. Remark Type
     */
    public String getLeadRemarkType() {
        return this.leadRemarkType;
    }

    /**
     * Setter for <code>invopay.lead_remark.lead_remark_type</code>. Remark Type
     */
    public LeadRemarkDTO setLeadRemarkType(String leadRemarkType) {
        this.leadRemarkType = leadRemarkType;
        return this;
    }

    /**
     * Getter for <code>invopay.lead_remark.lead_remark_details</code>. Remark Details
     */
    public String getLeadRemarkDetails() {
        return this.leadRemarkDetails;
    }

    /**
     * Setter for <code>invopay.lead_remark.lead_remark_details</code>. Remark Details
     */
    public LeadRemarkDTO setLeadRemarkDetails(String leadRemarkDetails) {
        this.leadRemarkDetails = leadRemarkDetails;
        return this;
    }

    /**
     * Getter for <code>invopay.lead_remark.ref_user_id</code>.
     */
    public Integer getRefUserId() {
        return this.refUserId;
    }

    /**
     * Setter for <code>invopay.lead_remark.ref_user_id</code>.
     */
    public LeadRemarkDTO setRefUserId(Integer refUserId) {
        this.refUserId = refUserId;
        return this;
    }

    /**
     * Getter for <code>invopay.lead_remark.delete_status</code>.
     */
    public Integer getDeleteStatus() {
        return this.deleteStatus;
    }

    /**
     * Setter for <code>invopay.lead_remark.delete_status</code>.
     */
    public LeadRemarkDTO setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.lead_remark.transaction_id</code>.
     */
    public Integer getTransactionId() {
        return this.transactionId;
    }

    /**
     * Setter for <code>invopay.lead_remark.transaction_id</code>.
     */
    public LeadRemarkDTO setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
        return this;
    }

    /**
     * Getter for <code>invopay.lead_remark.added_date</code>.
     */
    public LocalDateTime getAddedDate() {
        return this.addedDate;
    }

    /**
     * Setter for <code>invopay.lead_remark.added_date</code>.
     */
    public LeadRemarkDTO setAddedDate(LocalDateTime addedDate) {
        this.addedDate = addedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final LeadRemarkDTO other = (LeadRemarkDTO) obj;
        if (leadRemarkId == null) {
            if (other.leadRemarkId != null)
                return false;
        }
        else if (!leadRemarkId.equals(other.leadRemarkId))
            return false;
        if (refLeadId == null) {
            if (other.refLeadId != null)
                return false;
        }
        else if (!refLeadId.equals(other.refLeadId))
            return false;
        if (leadRemarkDateAndTime == null) {
            if (other.leadRemarkDateAndTime != null)
                return false;
        }
        else if (!leadRemarkDateAndTime.equals(other.leadRemarkDateAndTime))
            return false;
        if (leadRemarkType == null) {
            if (other.leadRemarkType != null)
                return false;
        }
        else if (!leadRemarkType.equals(other.leadRemarkType))
            return false;
        if (leadRemarkDetails == null) {
            if (other.leadRemarkDetails != null)
                return false;
        }
        else if (!leadRemarkDetails.equals(other.leadRemarkDetails))
            return false;
        if (refUserId == null) {
            if (other.refUserId != null)
                return false;
        }
        else if (!refUserId.equals(other.refUserId))
            return false;
        if (deleteStatus == null) {
            if (other.deleteStatus != null)
                return false;
        }
        else if (!deleteStatus.equals(other.deleteStatus))
            return false;
        if (transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!transactionId.equals(other.transactionId))
            return false;
        if (addedDate == null) {
            if (other.addedDate != null)
                return false;
        }
        else if (!addedDate.equals(other.addedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.leadRemarkId == null) ? 0 : this.leadRemarkId.hashCode());
        result = prime * result + ((this.refLeadId == null) ? 0 : this.refLeadId.hashCode());
        result = prime * result + ((this.leadRemarkDateAndTime == null) ? 0 : this.leadRemarkDateAndTime.hashCode());
        result = prime * result + ((this.leadRemarkType == null) ? 0 : this.leadRemarkType.hashCode());
        result = prime * result + ((this.leadRemarkDetails == null) ? 0 : this.leadRemarkDetails.hashCode());
        result = prime * result + ((this.refUserId == null) ? 0 : this.refUserId.hashCode());
        result = prime * result + ((this.deleteStatus == null) ? 0 : this.deleteStatus.hashCode());
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.addedDate == null) ? 0 : this.addedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LeadRemark (");

        sb.append(leadRemarkId);
        sb.append(", ").append(refLeadId);
        sb.append(", ").append(leadRemarkDateAndTime);
        sb.append(", ").append(leadRemarkType);
        sb.append(", ").append(leadRemarkDetails);
        sb.append(", ").append(refUserId);
        sb.append(", ").append(deleteStatus);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(addedDate);

        sb.append(")");
        return sb.toString();
    }
}
