/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.DTO;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LineItemDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       lineItemId;
    private String        lineItemName;
    private Integer       deleteStatus;
    private Integer       refUserId;
    private Integer       transactionId;
    private LocalDateTime addedDate;

    public LineItemDTO() {}

    public LineItemDTO(LineItemDTO value) {
        this.lineItemId = value.lineItemId;
        this.lineItemName = value.lineItemName;
        this.deleteStatus = value.deleteStatus;
        this.refUserId = value.refUserId;
        this.transactionId = value.transactionId;
        this.addedDate = value.addedDate;
    }

    public LineItemDTO(
        Integer       lineItemId,
        String        lineItemName,
        Integer       deleteStatus,
        Integer       refUserId,
        Integer       transactionId,
        LocalDateTime addedDate
    ) {
        this.lineItemId = lineItemId;
        this.lineItemName = lineItemName;
        this.deleteStatus = deleteStatus;
        this.refUserId = refUserId;
        this.transactionId = transactionId;
        this.addedDate = addedDate;
    }

    /**
     * Getter for <code>invopay.line_item.line_item_id</code>.
     */
    public Integer getLineItemId() {
        return this.lineItemId;
    }

    /**
     * Setter for <code>invopay.line_item.line_item_id</code>.
     */
    public LineItemDTO setLineItemId(Integer lineItemId) {
        this.lineItemId = lineItemId;
        return this;
    }

    /**
     * Getter for <code>invopay.line_item.line_item_name</code>.
     */
    public String getLineItemName() {
        return this.lineItemName;
    }

    /**
     * Setter for <code>invopay.line_item.line_item_name</code>.
     */
    public LineItemDTO setLineItemName(String lineItemName) {
        this.lineItemName = lineItemName;
        return this;
    }

    /**
     * Getter for <code>invopay.line_item.delete_status</code>.
     */
    public Integer getDeleteStatus() {
        return this.deleteStatus;
    }

    /**
     * Setter for <code>invopay.line_item.delete_status</code>.
     */
    public LineItemDTO setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.line_item.ref_user_id</code>.
     */
    public Integer getRefUserId() {
        return this.refUserId;
    }

    /**
     * Setter for <code>invopay.line_item.ref_user_id</code>.
     */
    public LineItemDTO setRefUserId(Integer refUserId) {
        this.refUserId = refUserId;
        return this;
    }

    /**
     * Getter for <code>invopay.line_item.transaction_id</code>.
     */
    public Integer getTransactionId() {
        return this.transactionId;
    }

    /**
     * Setter for <code>invopay.line_item.transaction_id</code>.
     */
    public LineItemDTO setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
        return this;
    }

    /**
     * Getter for <code>invopay.line_item.added_date</code>.
     */
    public LocalDateTime getAddedDate() {
        return this.addedDate;
    }

    /**
     * Setter for <code>invopay.line_item.added_date</code>.
     */
    public LineItemDTO setAddedDate(LocalDateTime addedDate) {
        this.addedDate = addedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final LineItemDTO other = (LineItemDTO) obj;
        if (lineItemId == null) {
            if (other.lineItemId != null)
                return false;
        }
        else if (!lineItemId.equals(other.lineItemId))
            return false;
        if (lineItemName == null) {
            if (other.lineItemName != null)
                return false;
        }
        else if (!lineItemName.equals(other.lineItemName))
            return false;
        if (deleteStatus == null) {
            if (other.deleteStatus != null)
                return false;
        }
        else if (!deleteStatus.equals(other.deleteStatus))
            return false;
        if (refUserId == null) {
            if (other.refUserId != null)
                return false;
        }
        else if (!refUserId.equals(other.refUserId))
            return false;
        if (transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!transactionId.equals(other.transactionId))
            return false;
        if (addedDate == null) {
            if (other.addedDate != null)
                return false;
        }
        else if (!addedDate.equals(other.addedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.lineItemId == null) ? 0 : this.lineItemId.hashCode());
        result = prime * result + ((this.lineItemName == null) ? 0 : this.lineItemName.hashCode());
        result = prime * result + ((this.deleteStatus == null) ? 0 : this.deleteStatus.hashCode());
        result = prime * result + ((this.refUserId == null) ? 0 : this.refUserId.hashCode());
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.addedDate == null) ? 0 : this.addedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LineItem (");

        sb.append(lineItemId);
        sb.append(", ").append(lineItemName);
        sb.append(", ").append(deleteStatus);
        sb.append(", ").append(refUserId);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(addedDate);

        sb.append(")");
        return sb.toString();
    }
}
