/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.DTO;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MachineToClientDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       machineToClientId;
    private Integer       refClientId;
    private Integer       refMachineId;
    private Integer       refMakeId;
    private Integer       refModelId;
    private Integer       noOfMachine;
    private Integer       noOfSpindles;
    private Integer       noOfDrums;
    private Integer       noOfRotors;
    private String        beltId;
    private Integer       refTapeSizeId;
    private Integer       refTopApronId;
    private Integer       refBottomApronId;
    private Integer       refFrontCotId;
    private Integer       refBackCotId;
    private Integer       refCompactCotSmallId;
    private Integer       refCompactCotBigId;
    private Integer       totalSpindles;
    private Integer       totalDrums;
    private Integer       totalRotors;
    private Integer       refUserId;
    private Integer       deleteStatus;
    private Integer       transactionId;
    private LocalDateTime addedDate;

    public MachineToClientDTO() {}

    public MachineToClientDTO(MachineToClientDTO value) {
        this.machineToClientId = value.machineToClientId;
        this.refClientId = value.refClientId;
        this.refMachineId = value.refMachineId;
        this.refMakeId = value.refMakeId;
        this.refModelId = value.refModelId;
        this.noOfMachine = value.noOfMachine;
        this.noOfSpindles = value.noOfSpindles;
        this.noOfDrums = value.noOfDrums;
        this.noOfRotors = value.noOfRotors;
        this.beltId = value.beltId;
        this.refTapeSizeId = value.refTapeSizeId;
        this.refTopApronId = value.refTopApronId;
        this.refBottomApronId = value.refBottomApronId;
        this.refFrontCotId = value.refFrontCotId;
        this.refBackCotId = value.refBackCotId;
        this.refCompactCotSmallId = value.refCompactCotSmallId;
        this.refCompactCotBigId = value.refCompactCotBigId;
        this.totalSpindles = value.totalSpindles;
        this.totalDrums = value.totalDrums;
        this.totalRotors = value.totalRotors;
        this.refUserId = value.refUserId;
        this.deleteStatus = value.deleteStatus;
        this.transactionId = value.transactionId;
        this.addedDate = value.addedDate;
    }

    public MachineToClientDTO(
        Integer       machineToClientId,
        Integer       refClientId,
        Integer       refMachineId,
        Integer       refMakeId,
        Integer       refModelId,
        Integer       noOfMachine,
        Integer       noOfSpindles,
        Integer       noOfDrums,
        Integer       noOfRotors,
        String        beltId,
        Integer       refTapeSizeId,
        Integer       refTopApronId,
        Integer       refBottomApronId,
        Integer       refFrontCotId,
        Integer       refBackCotId,
        Integer       refCompactCotSmallId,
        Integer       refCompactCotBigId,
        Integer       totalSpindles,
        Integer       totalDrums,
        Integer       totalRotors,
        Integer       refUserId,
        Integer       deleteStatus,
        Integer       transactionId,
        LocalDateTime addedDate
    ) {
        this.machineToClientId = machineToClientId;
        this.refClientId = refClientId;
        this.refMachineId = refMachineId;
        this.refMakeId = refMakeId;
        this.refModelId = refModelId;
        this.noOfMachine = noOfMachine;
        this.noOfSpindles = noOfSpindles;
        this.noOfDrums = noOfDrums;
        this.noOfRotors = noOfRotors;
        this.beltId = beltId;
        this.refTapeSizeId = refTapeSizeId;
        this.refTopApronId = refTopApronId;
        this.refBottomApronId = refBottomApronId;
        this.refFrontCotId = refFrontCotId;
        this.refBackCotId = refBackCotId;
        this.refCompactCotSmallId = refCompactCotSmallId;
        this.refCompactCotBigId = refCompactCotBigId;
        this.totalSpindles = totalSpindles;
        this.totalDrums = totalDrums;
        this.totalRotors = totalRotors;
        this.refUserId = refUserId;
        this.deleteStatus = deleteStatus;
        this.transactionId = transactionId;
        this.addedDate = addedDate;
    }

    /**
     * Getter for <code>invopay.machine_to_client.machine_to_client_id</code>.
     */
    public Integer getMachineToClientId() {
        return this.machineToClientId;
    }

    /**
     * Setter for <code>invopay.machine_to_client.machine_to_client_id</code>.
     */
    public MachineToClientDTO setMachineToClientId(Integer machineToClientId) {
        this.machineToClientId = machineToClientId;
        return this;
    }

    /**
     * Getter for <code>invopay.machine_to_client.ref_client_id</code>.
     */
    public Integer getRefClientId() {
        return this.refClientId;
    }

    /**
     * Setter for <code>invopay.machine_to_client.ref_client_id</code>.
     */
    public MachineToClientDTO setRefClientId(Integer refClientId) {
        this.refClientId = refClientId;
        return this;
    }

    /**
     * Getter for <code>invopay.machine_to_client.ref_machine_id</code>.
     */
    public Integer getRefMachineId() {
        return this.refMachineId;
    }

    /**
     * Setter for <code>invopay.machine_to_client.ref_machine_id</code>.
     */
    public MachineToClientDTO setRefMachineId(Integer refMachineId) {
        this.refMachineId = refMachineId;
        return this;
    }

    /**
     * Getter for <code>invopay.machine_to_client.ref_make_id</code>.
     */
    public Integer getRefMakeId() {
        return this.refMakeId;
    }

    /**
     * Setter for <code>invopay.machine_to_client.ref_make_id</code>.
     */
    public MachineToClientDTO setRefMakeId(Integer refMakeId) {
        this.refMakeId = refMakeId;
        return this;
    }

    /**
     * Getter for <code>invopay.machine_to_client.ref_model_id</code>.
     */
    public Integer getRefModelId() {
        return this.refModelId;
    }

    /**
     * Setter for <code>invopay.machine_to_client.ref_model_id</code>.
     */
    public MachineToClientDTO setRefModelId(Integer refModelId) {
        this.refModelId = refModelId;
        return this;
    }

    /**
     * Getter for <code>invopay.machine_to_client.no_of_machine</code>.
     */
    public Integer getNoOfMachine() {
        return this.noOfMachine;
    }

    /**
     * Setter for <code>invopay.machine_to_client.no_of_machine</code>.
     */
    public MachineToClientDTO setNoOfMachine(Integer noOfMachine) {
        this.noOfMachine = noOfMachine;
        return this;
    }

    /**
     * Getter for <code>invopay.machine_to_client.no_of_spindles</code>.
     */
    public Integer getNoOfSpindles() {
        return this.noOfSpindles;
    }

    /**
     * Setter for <code>invopay.machine_to_client.no_of_spindles</code>.
     */
    public MachineToClientDTO setNoOfSpindles(Integer noOfSpindles) {
        this.noOfSpindles = noOfSpindles;
        return this;
    }

    /**
     * Getter for <code>invopay.machine_to_client.no_of_drums</code>.
     */
    public Integer getNoOfDrums() {
        return this.noOfDrums;
    }

    /**
     * Setter for <code>invopay.machine_to_client.no_of_drums</code>.
     */
    public MachineToClientDTO setNoOfDrums(Integer noOfDrums) {
        this.noOfDrums = noOfDrums;
        return this;
    }

    /**
     * Getter for <code>invopay.machine_to_client.no_of_rotors</code>.
     */
    public Integer getNoOfRotors() {
        return this.noOfRotors;
    }

    /**
     * Setter for <code>invopay.machine_to_client.no_of_rotors</code>.
     */
    public MachineToClientDTO setNoOfRotors(Integer noOfRotors) {
        this.noOfRotors = noOfRotors;
        return this;
    }

    /**
     * Getter for <code>invopay.machine_to_client.belt_id</code>.
     */
    public String getBeltId() {
        return this.beltId;
    }

    /**
     * Setter for <code>invopay.machine_to_client.belt_id</code>.
     */
    public MachineToClientDTO setBeltId(String beltId) {
        this.beltId = beltId;
        return this;
    }

    /**
     * Getter for <code>invopay.machine_to_client.ref_tape_size_id</code>.
     */
    public Integer getRefTapeSizeId() {
        return this.refTapeSizeId;
    }

    /**
     * Setter for <code>invopay.machine_to_client.ref_tape_size_id</code>.
     */
    public MachineToClientDTO setRefTapeSizeId(Integer refTapeSizeId) {
        this.refTapeSizeId = refTapeSizeId;
        return this;
    }

    /**
     * Getter for <code>invopay.machine_to_client.ref_top_apron_id</code>.
     */
    public Integer getRefTopApronId() {
        return this.refTopApronId;
    }

    /**
     * Setter for <code>invopay.machine_to_client.ref_top_apron_id</code>.
     */
    public MachineToClientDTO setRefTopApronId(Integer refTopApronId) {
        this.refTopApronId = refTopApronId;
        return this;
    }

    /**
     * Getter for <code>invopay.machine_to_client.ref_bottom_apron_id</code>.
     */
    public Integer getRefBottomApronId() {
        return this.refBottomApronId;
    }

    /**
     * Setter for <code>invopay.machine_to_client.ref_bottom_apron_id</code>.
     */
    public MachineToClientDTO setRefBottomApronId(Integer refBottomApronId) {
        this.refBottomApronId = refBottomApronId;
        return this;
    }

    /**
     * Getter for <code>invopay.machine_to_client.ref_front_cot_id</code>.
     */
    public Integer getRefFrontCotId() {
        return this.refFrontCotId;
    }

    /**
     * Setter for <code>invopay.machine_to_client.ref_front_cot_id</code>.
     */
    public MachineToClientDTO setRefFrontCotId(Integer refFrontCotId) {
        this.refFrontCotId = refFrontCotId;
        return this;
    }

    /**
     * Getter for <code>invopay.machine_to_client.ref_back_cot_id</code>.
     */
    public Integer getRefBackCotId() {
        return this.refBackCotId;
    }

    /**
     * Setter for <code>invopay.machine_to_client.ref_back_cot_id</code>.
     */
    public MachineToClientDTO setRefBackCotId(Integer refBackCotId) {
        this.refBackCotId = refBackCotId;
        return this;
    }

    /**
     * Getter for <code>invopay.machine_to_client.ref_compact_cot_small_id</code>.
     */
    public Integer getRefCompactCotSmallId() {
        return this.refCompactCotSmallId;
    }

    /**
     * Setter for <code>invopay.machine_to_client.ref_compact_cot_small_id</code>.
     */
    public MachineToClientDTO setRefCompactCotSmallId(Integer refCompactCotSmallId) {
        this.refCompactCotSmallId = refCompactCotSmallId;
        return this;
    }

    /**
     * Getter for <code>invopay.machine_to_client.ref_compact_cot_big_id</code>.
     */
    public Integer getRefCompactCotBigId() {
        return this.refCompactCotBigId;
    }

    /**
     * Setter for <code>invopay.machine_to_client.ref_compact_cot_big_id</code>.
     */
    public MachineToClientDTO setRefCompactCotBigId(Integer refCompactCotBigId) {
        this.refCompactCotBigId = refCompactCotBigId;
        return this;
    }

    /**
     * Getter for <code>invopay.machine_to_client.total_spindles</code>.
     */
    public Integer getTotalSpindles() {
        return this.totalSpindles;
    }

    /**
     * Setter for <code>invopay.machine_to_client.total_spindles</code>.
     */
    public MachineToClientDTO setTotalSpindles(Integer totalSpindles) {
        this.totalSpindles = totalSpindles;
        return this;
    }

    /**
     * Getter for <code>invopay.machine_to_client.total_drums</code>.
     */
    public Integer getTotalDrums() {
        return this.totalDrums;
    }

    /**
     * Setter for <code>invopay.machine_to_client.total_drums</code>.
     */
    public MachineToClientDTO setTotalDrums(Integer totalDrums) {
        this.totalDrums = totalDrums;
        return this;
    }

    /**
     * Getter for <code>invopay.machine_to_client.total_rotors</code>.
     */
    public Integer getTotalRotors() {
        return this.totalRotors;
    }

    /**
     * Setter for <code>invopay.machine_to_client.total_rotors</code>.
     */
    public MachineToClientDTO setTotalRotors(Integer totalRotors) {
        this.totalRotors = totalRotors;
        return this;
    }

    /**
     * Getter for <code>invopay.machine_to_client.ref_user_id</code>.
     */
    public Integer getRefUserId() {
        return this.refUserId;
    }

    /**
     * Setter for <code>invopay.machine_to_client.ref_user_id</code>.
     */
    public MachineToClientDTO setRefUserId(Integer refUserId) {
        this.refUserId = refUserId;
        return this;
    }

    /**
     * Getter for <code>invopay.machine_to_client.delete_status</code>.
     */
    public Integer getDeleteStatus() {
        return this.deleteStatus;
    }

    /**
     * Setter for <code>invopay.machine_to_client.delete_status</code>.
     */
    public MachineToClientDTO setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.machine_to_client.transaction_id</code>.
     */
    public Integer getTransactionId() {
        return this.transactionId;
    }

    /**
     * Setter for <code>invopay.machine_to_client.transaction_id</code>.
     */
    public MachineToClientDTO setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
        return this;
    }

    /**
     * Getter for <code>invopay.machine_to_client.added_date</code>.
     */
    public LocalDateTime getAddedDate() {
        return this.addedDate;
    }

    /**
     * Setter for <code>invopay.machine_to_client.added_date</code>.
     */
    public MachineToClientDTO setAddedDate(LocalDateTime addedDate) {
        this.addedDate = addedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final MachineToClientDTO other = (MachineToClientDTO) obj;
        if (machineToClientId == null) {
            if (other.machineToClientId != null)
                return false;
        }
        else if (!machineToClientId.equals(other.machineToClientId))
            return false;
        if (refClientId == null) {
            if (other.refClientId != null)
                return false;
        }
        else if (!refClientId.equals(other.refClientId))
            return false;
        if (refMachineId == null) {
            if (other.refMachineId != null)
                return false;
        }
        else if (!refMachineId.equals(other.refMachineId))
            return false;
        if (refMakeId == null) {
            if (other.refMakeId != null)
                return false;
        }
        else if (!refMakeId.equals(other.refMakeId))
            return false;
        if (refModelId == null) {
            if (other.refModelId != null)
                return false;
        }
        else if (!refModelId.equals(other.refModelId))
            return false;
        if (noOfMachine == null) {
            if (other.noOfMachine != null)
                return false;
        }
        else if (!noOfMachine.equals(other.noOfMachine))
            return false;
        if (noOfSpindles == null) {
            if (other.noOfSpindles != null)
                return false;
        }
        else if (!noOfSpindles.equals(other.noOfSpindles))
            return false;
        if (noOfDrums == null) {
            if (other.noOfDrums != null)
                return false;
        }
        else if (!noOfDrums.equals(other.noOfDrums))
            return false;
        if (noOfRotors == null) {
            if (other.noOfRotors != null)
                return false;
        }
        else if (!noOfRotors.equals(other.noOfRotors))
            return false;
        if (beltId == null) {
            if (other.beltId != null)
                return false;
        }
        else if (!beltId.equals(other.beltId))
            return false;
        if (refTapeSizeId == null) {
            if (other.refTapeSizeId != null)
                return false;
        }
        else if (!refTapeSizeId.equals(other.refTapeSizeId))
            return false;
        if (refTopApronId == null) {
            if (other.refTopApronId != null)
                return false;
        }
        else if (!refTopApronId.equals(other.refTopApronId))
            return false;
        if (refBottomApronId == null) {
            if (other.refBottomApronId != null)
                return false;
        }
        else if (!refBottomApronId.equals(other.refBottomApronId))
            return false;
        if (refFrontCotId == null) {
            if (other.refFrontCotId != null)
                return false;
        }
        else if (!refFrontCotId.equals(other.refFrontCotId))
            return false;
        if (refBackCotId == null) {
            if (other.refBackCotId != null)
                return false;
        }
        else if (!refBackCotId.equals(other.refBackCotId))
            return false;
        if (refCompactCotSmallId == null) {
            if (other.refCompactCotSmallId != null)
                return false;
        }
        else if (!refCompactCotSmallId.equals(other.refCompactCotSmallId))
            return false;
        if (refCompactCotBigId == null) {
            if (other.refCompactCotBigId != null)
                return false;
        }
        else if (!refCompactCotBigId.equals(other.refCompactCotBigId))
            return false;
        if (totalSpindles == null) {
            if (other.totalSpindles != null)
                return false;
        }
        else if (!totalSpindles.equals(other.totalSpindles))
            return false;
        if (totalDrums == null) {
            if (other.totalDrums != null)
                return false;
        }
        else if (!totalDrums.equals(other.totalDrums))
            return false;
        if (totalRotors == null) {
            if (other.totalRotors != null)
                return false;
        }
        else if (!totalRotors.equals(other.totalRotors))
            return false;
        if (refUserId == null) {
            if (other.refUserId != null)
                return false;
        }
        else if (!refUserId.equals(other.refUserId))
            return false;
        if (deleteStatus == null) {
            if (other.deleteStatus != null)
                return false;
        }
        else if (!deleteStatus.equals(other.deleteStatus))
            return false;
        if (transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!transactionId.equals(other.transactionId))
            return false;
        if (addedDate == null) {
            if (other.addedDate != null)
                return false;
        }
        else if (!addedDate.equals(other.addedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.machineToClientId == null) ? 0 : this.machineToClientId.hashCode());
        result = prime * result + ((this.refClientId == null) ? 0 : this.refClientId.hashCode());
        result = prime * result + ((this.refMachineId == null) ? 0 : this.refMachineId.hashCode());
        result = prime * result + ((this.refMakeId == null) ? 0 : this.refMakeId.hashCode());
        result = prime * result + ((this.refModelId == null) ? 0 : this.refModelId.hashCode());
        result = prime * result + ((this.noOfMachine == null) ? 0 : this.noOfMachine.hashCode());
        result = prime * result + ((this.noOfSpindles == null) ? 0 : this.noOfSpindles.hashCode());
        result = prime * result + ((this.noOfDrums == null) ? 0 : this.noOfDrums.hashCode());
        result = prime * result + ((this.noOfRotors == null) ? 0 : this.noOfRotors.hashCode());
        result = prime * result + ((this.beltId == null) ? 0 : this.beltId.hashCode());
        result = prime * result + ((this.refTapeSizeId == null) ? 0 : this.refTapeSizeId.hashCode());
        result = prime * result + ((this.refTopApronId == null) ? 0 : this.refTopApronId.hashCode());
        result = prime * result + ((this.refBottomApronId == null) ? 0 : this.refBottomApronId.hashCode());
        result = prime * result + ((this.refFrontCotId == null) ? 0 : this.refFrontCotId.hashCode());
        result = prime * result + ((this.refBackCotId == null) ? 0 : this.refBackCotId.hashCode());
        result = prime * result + ((this.refCompactCotSmallId == null) ? 0 : this.refCompactCotSmallId.hashCode());
        result = prime * result + ((this.refCompactCotBigId == null) ? 0 : this.refCompactCotBigId.hashCode());
        result = prime * result + ((this.totalSpindles == null) ? 0 : this.totalSpindles.hashCode());
        result = prime * result + ((this.totalDrums == null) ? 0 : this.totalDrums.hashCode());
        result = prime * result + ((this.totalRotors == null) ? 0 : this.totalRotors.hashCode());
        result = prime * result + ((this.refUserId == null) ? 0 : this.refUserId.hashCode());
        result = prime * result + ((this.deleteStatus == null) ? 0 : this.deleteStatus.hashCode());
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.addedDate == null) ? 0 : this.addedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MachineToClient (");

        sb.append(machineToClientId);
        sb.append(", ").append(refClientId);
        sb.append(", ").append(refMachineId);
        sb.append(", ").append(refMakeId);
        sb.append(", ").append(refModelId);
        sb.append(", ").append(noOfMachine);
        sb.append(", ").append(noOfSpindles);
        sb.append(", ").append(noOfDrums);
        sb.append(", ").append(noOfRotors);
        sb.append(", ").append(beltId);
        sb.append(", ").append(refTapeSizeId);
        sb.append(", ").append(refTopApronId);
        sb.append(", ").append(refBottomApronId);
        sb.append(", ").append(refFrontCotId);
        sb.append(", ").append(refBackCotId);
        sb.append(", ").append(refCompactCotSmallId);
        sb.append(", ").append(refCompactCotBigId);
        sb.append(", ").append(totalSpindles);
        sb.append(", ").append(totalDrums);
        sb.append(", ").append(totalRotors);
        sb.append(", ").append(refUserId);
        sb.append(", ").append(deleteStatus);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(addedDate);

        sb.append(")");
        return sb.toString();
    }
}
