/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.DTO;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MachineDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       machineId;
    private String        machineName;
    private Integer       modelStatus;
    private Integer       makeStatus;
    private Integer       noOfMachineStatus;
    private Integer       noOfSpindlesStatus;
    private Integer       noOfDrumsStatus;
    private Integer       noOfRotorsStatus;
    private Integer       tapeSizeStatus;
    private Integer       topApronStatus;
    private Integer       bottomApronStatus;
    private Integer       frontCotStatus;
    private Integer       backCotStatus;
    private Integer       compactCotSmallStatus;
    private Integer       compactCotBigStatus;
    private Integer       beltStatus;
    private Integer       sortOrder;
    private Integer       refUserId;
    private Integer       deleteStatus;
    private Integer       transactionId;
    private LocalDateTime addedDate;

    public MachineDTO() {}

    public MachineDTO(MachineDTO value) {
        this.machineId = value.machineId;
        this.machineName = value.machineName;
        this.modelStatus = value.modelStatus;
        this.makeStatus = value.makeStatus;
        this.noOfMachineStatus = value.noOfMachineStatus;
        this.noOfSpindlesStatus = value.noOfSpindlesStatus;
        this.noOfDrumsStatus = value.noOfDrumsStatus;
        this.noOfRotorsStatus = value.noOfRotorsStatus;
        this.tapeSizeStatus = value.tapeSizeStatus;
        this.topApronStatus = value.topApronStatus;
        this.bottomApronStatus = value.bottomApronStatus;
        this.frontCotStatus = value.frontCotStatus;
        this.backCotStatus = value.backCotStatus;
        this.compactCotSmallStatus = value.compactCotSmallStatus;
        this.compactCotBigStatus = value.compactCotBigStatus;
        this.beltStatus = value.beltStatus;
        this.sortOrder = value.sortOrder;
        this.refUserId = value.refUserId;
        this.deleteStatus = value.deleteStatus;
        this.transactionId = value.transactionId;
        this.addedDate = value.addedDate;
    }

    public MachineDTO(
        Integer       machineId,
        String        machineName,
        Integer       modelStatus,
        Integer       makeStatus,
        Integer       noOfMachineStatus,
        Integer       noOfSpindlesStatus,
        Integer       noOfDrumsStatus,
        Integer       noOfRotorsStatus,
        Integer       tapeSizeStatus,
        Integer       topApronStatus,
        Integer       bottomApronStatus,
        Integer       frontCotStatus,
        Integer       backCotStatus,
        Integer       compactCotSmallStatus,
        Integer       compactCotBigStatus,
        Integer       beltStatus,
        Integer       sortOrder,
        Integer       refUserId,
        Integer       deleteStatus,
        Integer       transactionId,
        LocalDateTime addedDate
    ) {
        this.machineId = machineId;
        this.machineName = machineName;
        this.modelStatus = modelStatus;
        this.makeStatus = makeStatus;
        this.noOfMachineStatus = noOfMachineStatus;
        this.noOfSpindlesStatus = noOfSpindlesStatus;
        this.noOfDrumsStatus = noOfDrumsStatus;
        this.noOfRotorsStatus = noOfRotorsStatus;
        this.tapeSizeStatus = tapeSizeStatus;
        this.topApronStatus = topApronStatus;
        this.bottomApronStatus = bottomApronStatus;
        this.frontCotStatus = frontCotStatus;
        this.backCotStatus = backCotStatus;
        this.compactCotSmallStatus = compactCotSmallStatus;
        this.compactCotBigStatus = compactCotBigStatus;
        this.beltStatus = beltStatus;
        this.sortOrder = sortOrder;
        this.refUserId = refUserId;
        this.deleteStatus = deleteStatus;
        this.transactionId = transactionId;
        this.addedDate = addedDate;
    }

    /**
     * Getter for <code>invopay.machine.machine_id</code>.
     */
    public Integer getMachineId() {
        return this.machineId;
    }

    /**
     * Setter for <code>invopay.machine.machine_id</code>.
     */
    public MachineDTO setMachineId(Integer machineId) {
        this.machineId = machineId;
        return this;
    }

    /**
     * Getter for <code>invopay.machine.machine_name</code>. Name
     */
    public String getMachineName() {
        return this.machineName;
    }

    /**
     * Setter for <code>invopay.machine.machine_name</code>. Name
     */
    public MachineDTO setMachineName(String machineName) {
        this.machineName = machineName;
        return this;
    }

    /**
     * Getter for <code>invopay.machine.model_status</code>.
     */
    public Integer getModelStatus() {
        return this.modelStatus;
    }

    /**
     * Setter for <code>invopay.machine.model_status</code>.
     */
    public MachineDTO setModelStatus(Integer modelStatus) {
        this.modelStatus = modelStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.machine.make_status</code>.
     */
    public Integer getMakeStatus() {
        return this.makeStatus;
    }

    /**
     * Setter for <code>invopay.machine.make_status</code>.
     */
    public MachineDTO setMakeStatus(Integer makeStatus) {
        this.makeStatus = makeStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.machine.no_of_machine_status</code>.
     */
    public Integer getNoOfMachineStatus() {
        return this.noOfMachineStatus;
    }

    /**
     * Setter for <code>invopay.machine.no_of_machine_status</code>.
     */
    public MachineDTO setNoOfMachineStatus(Integer noOfMachineStatus) {
        this.noOfMachineStatus = noOfMachineStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.machine.no_of_spindles_status</code>.
     */
    public Integer getNoOfSpindlesStatus() {
        return this.noOfSpindlesStatus;
    }

    /**
     * Setter for <code>invopay.machine.no_of_spindles_status</code>.
     */
    public MachineDTO setNoOfSpindlesStatus(Integer noOfSpindlesStatus) {
        this.noOfSpindlesStatus = noOfSpindlesStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.machine.no_of_drums_status</code>.
     */
    public Integer getNoOfDrumsStatus() {
        return this.noOfDrumsStatus;
    }

    /**
     * Setter for <code>invopay.machine.no_of_drums_status</code>.
     */
    public MachineDTO setNoOfDrumsStatus(Integer noOfDrumsStatus) {
        this.noOfDrumsStatus = noOfDrumsStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.machine.no_of_rotors_status</code>.
     */
    public Integer getNoOfRotorsStatus() {
        return this.noOfRotorsStatus;
    }

    /**
     * Setter for <code>invopay.machine.no_of_rotors_status</code>.
     */
    public MachineDTO setNoOfRotorsStatus(Integer noOfRotorsStatus) {
        this.noOfRotorsStatus = noOfRotorsStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.machine.tape_size_status</code>.
     */
    public Integer getTapeSizeStatus() {
        return this.tapeSizeStatus;
    }

    /**
     * Setter for <code>invopay.machine.tape_size_status</code>.
     */
    public MachineDTO setTapeSizeStatus(Integer tapeSizeStatus) {
        this.tapeSizeStatus = tapeSizeStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.machine.top_apron_status</code>.
     */
    public Integer getTopApronStatus() {
        return this.topApronStatus;
    }

    /**
     * Setter for <code>invopay.machine.top_apron_status</code>.
     */
    public MachineDTO setTopApronStatus(Integer topApronStatus) {
        this.topApronStatus = topApronStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.machine.bottom_apron_status</code>.
     */
    public Integer getBottomApronStatus() {
        return this.bottomApronStatus;
    }

    /**
     * Setter for <code>invopay.machine.bottom_apron_status</code>.
     */
    public MachineDTO setBottomApronStatus(Integer bottomApronStatus) {
        this.bottomApronStatus = bottomApronStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.machine.front_cot_status</code>.
     */
    public Integer getFrontCotStatus() {
        return this.frontCotStatus;
    }

    /**
     * Setter for <code>invopay.machine.front_cot_status</code>.
     */
    public MachineDTO setFrontCotStatus(Integer frontCotStatus) {
        this.frontCotStatus = frontCotStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.machine.back_cot_status</code>.
     */
    public Integer getBackCotStatus() {
        return this.backCotStatus;
    }

    /**
     * Setter for <code>invopay.machine.back_cot_status</code>.
     */
    public MachineDTO setBackCotStatus(Integer backCotStatus) {
        this.backCotStatus = backCotStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.machine.compact_cot_small_status</code>.
     */
    public Integer getCompactCotSmallStatus() {
        return this.compactCotSmallStatus;
    }

    /**
     * Setter for <code>invopay.machine.compact_cot_small_status</code>.
     */
    public MachineDTO setCompactCotSmallStatus(Integer compactCotSmallStatus) {
        this.compactCotSmallStatus = compactCotSmallStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.machine.compact_cot_big_status</code>.
     */
    public Integer getCompactCotBigStatus() {
        return this.compactCotBigStatus;
    }

    /**
     * Setter for <code>invopay.machine.compact_cot_big_status</code>.
     */
    public MachineDTO setCompactCotBigStatus(Integer compactCotBigStatus) {
        this.compactCotBigStatus = compactCotBigStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.machine.belt_status</code>.
     */
    public Integer getBeltStatus() {
        return this.beltStatus;
    }

    /**
     * Setter for <code>invopay.machine.belt_status</code>.
     */
    public MachineDTO setBeltStatus(Integer beltStatus) {
        this.beltStatus = beltStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.machine.sort_order</code>.
     */
    public Integer getSortOrder() {
        return this.sortOrder;
    }

    /**
     * Setter for <code>invopay.machine.sort_order</code>.
     */
    public MachineDTO setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
        return this;
    }

    /**
     * Getter for <code>invopay.machine.ref_user_id</code>.
     */
    public Integer getRefUserId() {
        return this.refUserId;
    }

    /**
     * Setter for <code>invopay.machine.ref_user_id</code>.
     */
    public MachineDTO setRefUserId(Integer refUserId) {
        this.refUserId = refUserId;
        return this;
    }

    /**
     * Getter for <code>invopay.machine.delete_status</code>.
     */
    public Integer getDeleteStatus() {
        return this.deleteStatus;
    }

    /**
     * Setter for <code>invopay.machine.delete_status</code>.
     */
    public MachineDTO setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.machine.transaction_id</code>.
     */
    public Integer getTransactionId() {
        return this.transactionId;
    }

    /**
     * Setter for <code>invopay.machine.transaction_id</code>.
     */
    public MachineDTO setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
        return this;
    }

    /**
     * Getter for <code>invopay.machine.added_date</code>.
     */
    public LocalDateTime getAddedDate() {
        return this.addedDate;
    }

    /**
     * Setter for <code>invopay.machine.added_date</code>.
     */
    public MachineDTO setAddedDate(LocalDateTime addedDate) {
        this.addedDate = addedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final MachineDTO other = (MachineDTO) obj;
        if (machineId == null) {
            if (other.machineId != null)
                return false;
        }
        else if (!machineId.equals(other.machineId))
            return false;
        if (machineName == null) {
            if (other.machineName != null)
                return false;
        }
        else if (!machineName.equals(other.machineName))
            return false;
        if (modelStatus == null) {
            if (other.modelStatus != null)
                return false;
        }
        else if (!modelStatus.equals(other.modelStatus))
            return false;
        if (makeStatus == null) {
            if (other.makeStatus != null)
                return false;
        }
        else if (!makeStatus.equals(other.makeStatus))
            return false;
        if (noOfMachineStatus == null) {
            if (other.noOfMachineStatus != null)
                return false;
        }
        else if (!noOfMachineStatus.equals(other.noOfMachineStatus))
            return false;
        if (noOfSpindlesStatus == null) {
            if (other.noOfSpindlesStatus != null)
                return false;
        }
        else if (!noOfSpindlesStatus.equals(other.noOfSpindlesStatus))
            return false;
        if (noOfDrumsStatus == null) {
            if (other.noOfDrumsStatus != null)
                return false;
        }
        else if (!noOfDrumsStatus.equals(other.noOfDrumsStatus))
            return false;
        if (noOfRotorsStatus == null) {
            if (other.noOfRotorsStatus != null)
                return false;
        }
        else if (!noOfRotorsStatus.equals(other.noOfRotorsStatus))
            return false;
        if (tapeSizeStatus == null) {
            if (other.tapeSizeStatus != null)
                return false;
        }
        else if (!tapeSizeStatus.equals(other.tapeSizeStatus))
            return false;
        if (topApronStatus == null) {
            if (other.topApronStatus != null)
                return false;
        }
        else if (!topApronStatus.equals(other.topApronStatus))
            return false;
        if (bottomApronStatus == null) {
            if (other.bottomApronStatus != null)
                return false;
        }
        else if (!bottomApronStatus.equals(other.bottomApronStatus))
            return false;
        if (frontCotStatus == null) {
            if (other.frontCotStatus != null)
                return false;
        }
        else if (!frontCotStatus.equals(other.frontCotStatus))
            return false;
        if (backCotStatus == null) {
            if (other.backCotStatus != null)
                return false;
        }
        else if (!backCotStatus.equals(other.backCotStatus))
            return false;
        if (compactCotSmallStatus == null) {
            if (other.compactCotSmallStatus != null)
                return false;
        }
        else if (!compactCotSmallStatus.equals(other.compactCotSmallStatus))
            return false;
        if (compactCotBigStatus == null) {
            if (other.compactCotBigStatus != null)
                return false;
        }
        else if (!compactCotBigStatus.equals(other.compactCotBigStatus))
            return false;
        if (beltStatus == null) {
            if (other.beltStatus != null)
                return false;
        }
        else if (!beltStatus.equals(other.beltStatus))
            return false;
        if (sortOrder == null) {
            if (other.sortOrder != null)
                return false;
        }
        else if (!sortOrder.equals(other.sortOrder))
            return false;
        if (refUserId == null) {
            if (other.refUserId != null)
                return false;
        }
        else if (!refUserId.equals(other.refUserId))
            return false;
        if (deleteStatus == null) {
            if (other.deleteStatus != null)
                return false;
        }
        else if (!deleteStatus.equals(other.deleteStatus))
            return false;
        if (transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!transactionId.equals(other.transactionId))
            return false;
        if (addedDate == null) {
            if (other.addedDate != null)
                return false;
        }
        else if (!addedDate.equals(other.addedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.machineId == null) ? 0 : this.machineId.hashCode());
        result = prime * result + ((this.machineName == null) ? 0 : this.machineName.hashCode());
        result = prime * result + ((this.modelStatus == null) ? 0 : this.modelStatus.hashCode());
        result = prime * result + ((this.makeStatus == null) ? 0 : this.makeStatus.hashCode());
        result = prime * result + ((this.noOfMachineStatus == null) ? 0 : this.noOfMachineStatus.hashCode());
        result = prime * result + ((this.noOfSpindlesStatus == null) ? 0 : this.noOfSpindlesStatus.hashCode());
        result = prime * result + ((this.noOfDrumsStatus == null) ? 0 : this.noOfDrumsStatus.hashCode());
        result = prime * result + ((this.noOfRotorsStatus == null) ? 0 : this.noOfRotorsStatus.hashCode());
        result = prime * result + ((this.tapeSizeStatus == null) ? 0 : this.tapeSizeStatus.hashCode());
        result = prime * result + ((this.topApronStatus == null) ? 0 : this.topApronStatus.hashCode());
        result = prime * result + ((this.bottomApronStatus == null) ? 0 : this.bottomApronStatus.hashCode());
        result = prime * result + ((this.frontCotStatus == null) ? 0 : this.frontCotStatus.hashCode());
        result = prime * result + ((this.backCotStatus == null) ? 0 : this.backCotStatus.hashCode());
        result = prime * result + ((this.compactCotSmallStatus == null) ? 0 : this.compactCotSmallStatus.hashCode());
        result = prime * result + ((this.compactCotBigStatus == null) ? 0 : this.compactCotBigStatus.hashCode());
        result = prime * result + ((this.beltStatus == null) ? 0 : this.beltStatus.hashCode());
        result = prime * result + ((this.sortOrder == null) ? 0 : this.sortOrder.hashCode());
        result = prime * result + ((this.refUserId == null) ? 0 : this.refUserId.hashCode());
        result = prime * result + ((this.deleteStatus == null) ? 0 : this.deleteStatus.hashCode());
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.addedDate == null) ? 0 : this.addedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Machine (");

        sb.append(machineId);
        sb.append(", ").append(machineName);
        sb.append(", ").append(modelStatus);
        sb.append(", ").append(makeStatus);
        sb.append(", ").append(noOfMachineStatus);
        sb.append(", ").append(noOfSpindlesStatus);
        sb.append(", ").append(noOfDrumsStatus);
        sb.append(", ").append(noOfRotorsStatus);
        sb.append(", ").append(tapeSizeStatus);
        sb.append(", ").append(topApronStatus);
        sb.append(", ").append(bottomApronStatus);
        sb.append(", ").append(frontCotStatus);
        sb.append(", ").append(backCotStatus);
        sb.append(", ").append(compactCotSmallStatus);
        sb.append(", ").append(compactCotBigStatus);
        sb.append(", ").append(beltStatus);
        sb.append(", ").append(sortOrder);
        sb.append(", ").append(refUserId);
        sb.append(", ").append(deleteStatus);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(addedDate);

        sb.append(")");
        return sb.toString();
    }
}
