/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.DTO;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PatientReferenceDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       patientReferenceId;
    private String        patientReferenceName;
    private Integer       refUserId;
    private Integer       deleteStatus;
    private Integer       transactionId;
    private LocalDateTime addedDate;

    public PatientReferenceDTO() {}

    public PatientReferenceDTO(PatientReferenceDTO value) {
        this.patientReferenceId = value.patientReferenceId;
        this.patientReferenceName = value.patientReferenceName;
        this.refUserId = value.refUserId;
        this.deleteStatus = value.deleteStatus;
        this.transactionId = value.transactionId;
        this.addedDate = value.addedDate;
    }

    public PatientReferenceDTO(
        Integer       patientReferenceId,
        String        patientReferenceName,
        Integer       refUserId,
        Integer       deleteStatus,
        Integer       transactionId,
        LocalDateTime addedDate
    ) {
        this.patientReferenceId = patientReferenceId;
        this.patientReferenceName = patientReferenceName;
        this.refUserId = refUserId;
        this.deleteStatus = deleteStatus;
        this.transactionId = transactionId;
        this.addedDate = addedDate;
    }

    /**
     * Getter for <code>invopay.patient_reference.patient_reference_id</code>.
     */
    public Integer getPatientReferenceId() {
        return this.patientReferenceId;
    }

    /**
     * Setter for <code>invopay.patient_reference.patient_reference_id</code>.
     */
    public PatientReferenceDTO setPatientReferenceId(Integer patientReferenceId) {
        this.patientReferenceId = patientReferenceId;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_reference.patient_reference_name</code>. Patient Reference Name
     */
    public String getPatientReferenceName() {
        return this.patientReferenceName;
    }

    /**
     * Setter for <code>invopay.patient_reference.patient_reference_name</code>. Patient Reference Name
     */
    public PatientReferenceDTO setPatientReferenceName(String patientReferenceName) {
        this.patientReferenceName = patientReferenceName;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_reference.ref_user_id</code>.
     */
    public Integer getRefUserId() {
        return this.refUserId;
    }

    /**
     * Setter for <code>invopay.patient_reference.ref_user_id</code>.
     */
    public PatientReferenceDTO setRefUserId(Integer refUserId) {
        this.refUserId = refUserId;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_reference.delete_status</code>.
     */
    public Integer getDeleteStatus() {
        return this.deleteStatus;
    }

    /**
     * Setter for <code>invopay.patient_reference.delete_status</code>.
     */
    public PatientReferenceDTO setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_reference.transaction_id</code>.
     */
    public Integer getTransactionId() {
        return this.transactionId;
    }

    /**
     * Setter for <code>invopay.patient_reference.transaction_id</code>.
     */
    public PatientReferenceDTO setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_reference.added_date</code>.
     */
    public LocalDateTime getAddedDate() {
        return this.addedDate;
    }

    /**
     * Setter for <code>invopay.patient_reference.added_date</code>.
     */
    public PatientReferenceDTO setAddedDate(LocalDateTime addedDate) {
        this.addedDate = addedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PatientReferenceDTO other = (PatientReferenceDTO) obj;
        if (patientReferenceId == null) {
            if (other.patientReferenceId != null)
                return false;
        }
        else if (!patientReferenceId.equals(other.patientReferenceId))
            return false;
        if (patientReferenceName == null) {
            if (other.patientReferenceName != null)
                return false;
        }
        else if (!patientReferenceName.equals(other.patientReferenceName))
            return false;
        if (refUserId == null) {
            if (other.refUserId != null)
                return false;
        }
        else if (!refUserId.equals(other.refUserId))
            return false;
        if (deleteStatus == null) {
            if (other.deleteStatus != null)
                return false;
        }
        else if (!deleteStatus.equals(other.deleteStatus))
            return false;
        if (transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!transactionId.equals(other.transactionId))
            return false;
        if (addedDate == null) {
            if (other.addedDate != null)
                return false;
        }
        else if (!addedDate.equals(other.addedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.patientReferenceId == null) ? 0 : this.patientReferenceId.hashCode());
        result = prime * result + ((this.patientReferenceName == null) ? 0 : this.patientReferenceName.hashCode());
        result = prime * result + ((this.refUserId == null) ? 0 : this.refUserId.hashCode());
        result = prime * result + ((this.deleteStatus == null) ? 0 : this.deleteStatus.hashCode());
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.addedDate == null) ? 0 : this.addedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PatientReference (");

        sb.append(patientReferenceId);
        sb.append(", ").append(patientReferenceName);
        sb.append(", ").append(refUserId);
        sb.append(", ").append(deleteStatus);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(addedDate);

        sb.append(")");
        return sb.toString();
    }
}
