/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.DTO;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Patient_1DTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       patientId;
    private String        patientName;
    private String        profilePic;
    private String        email;
    private Long          mobile;
    private Integer       age;
    private Integer       weight;
    private String        gender;
    private String        patientAddressLine1;
    private String        patientAddressLine2;
    private String        patientAddressLine3;
    private Integer       refCountryId;
    private Integer       refStateId;
    private Integer       refDistrictId;
    private Integer       pincode;
    private Integer       refPatientReferenceId;
    private Integer       refUserId;
    private Integer       deleteStatus;
    private Integer       transactionId;
    private LocalDateTime addedDate;

    public Patient_1DTO() {}

    public Patient_1DTO(Patient_1DTO value) {
        this.patientId = value.patientId;
        this.patientName = value.patientName;
        this.profilePic = value.profilePic;
        this.email = value.email;
        this.mobile = value.mobile;
        this.age = value.age;
        this.weight = value.weight;
        this.gender = value.gender;
        this.patientAddressLine1 = value.patientAddressLine1;
        this.patientAddressLine2 = value.patientAddressLine2;
        this.patientAddressLine3 = value.patientAddressLine3;
        this.refCountryId = value.refCountryId;
        this.refStateId = value.refStateId;
        this.refDistrictId = value.refDistrictId;
        this.pincode = value.pincode;
        this.refPatientReferenceId = value.refPatientReferenceId;
        this.refUserId = value.refUserId;
        this.deleteStatus = value.deleteStatus;
        this.transactionId = value.transactionId;
        this.addedDate = value.addedDate;
    }

    public Patient_1DTO(
        Integer       patientId,
        String        patientName,
        String        profilePic,
        String        email,
        Long          mobile,
        Integer       age,
        Integer       weight,
        String        gender,
        String        patientAddressLine1,
        String        patientAddressLine2,
        String        patientAddressLine3,
        Integer       refCountryId,
        Integer       refStateId,
        Integer       refDistrictId,
        Integer       pincode,
        Integer       refPatientReferenceId,
        Integer       refUserId,
        Integer       deleteStatus,
        Integer       transactionId,
        LocalDateTime addedDate
    ) {
        this.patientId = patientId;
        this.patientName = patientName;
        this.profilePic = profilePic;
        this.email = email;
        this.mobile = mobile;
        this.age = age;
        this.weight = weight;
        this.gender = gender;
        this.patientAddressLine1 = patientAddressLine1;
        this.patientAddressLine2 = patientAddressLine2;
        this.patientAddressLine3 = patientAddressLine3;
        this.refCountryId = refCountryId;
        this.refStateId = refStateId;
        this.refDistrictId = refDistrictId;
        this.pincode = pincode;
        this.refPatientReferenceId = refPatientReferenceId;
        this.refUserId = refUserId;
        this.deleteStatus = deleteStatus;
        this.transactionId = transactionId;
        this.addedDate = addedDate;
    }

    /**
     * Getter for <code>invopay.patient_1.patient_id</code>.
     */
    public Integer getPatientId() {
        return this.patientId;
    }

    /**
     * Setter for <code>invopay.patient_1.patient_id</code>.
     */
    public Patient_1DTO setPatientId(Integer patientId) {
        this.patientId = patientId;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_1.patient_name</code>.
     */
    public String getPatientName() {
        return this.patientName;
    }

    /**
     * Setter for <code>invopay.patient_1.patient_name</code>.
     */
    public Patient_1DTO setPatientName(String patientName) {
        this.patientName = patientName;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_1.profile_pic</code>.
     */
    public String getProfilePic() {
        return this.profilePic;
    }

    /**
     * Setter for <code>invopay.patient_1.profile_pic</code>.
     */
    public Patient_1DTO setProfilePic(String profilePic) {
        this.profilePic = profilePic;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_1.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>invopay.patient_1.email</code>.
     */
    public Patient_1DTO setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_1.mobile</code>.
     */
    public Long getMobile() {
        return this.mobile;
    }

    /**
     * Setter for <code>invopay.patient_1.mobile</code>.
     */
    public Patient_1DTO setMobile(Long mobile) {
        this.mobile = mobile;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_1.age</code>.
     */
    public Integer getAge() {
        return this.age;
    }

    /**
     * Setter for <code>invopay.patient_1.age</code>.
     */
    public Patient_1DTO setAge(Integer age) {
        this.age = age;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_1.weight</code>.
     */
    public Integer getWeight() {
        return this.weight;
    }

    /**
     * Setter for <code>invopay.patient_1.weight</code>.
     */
    public Patient_1DTO setWeight(Integer weight) {
        this.weight = weight;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_1.gender</code>.
     */
    public String getGender() {
        return this.gender;
    }

    /**
     * Setter for <code>invopay.patient_1.gender</code>.
     */
    public Patient_1DTO setGender(String gender) {
        this.gender = gender;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_1.patient_address_line1</code>.
     */
    public String getPatientAddressLine1() {
        return this.patientAddressLine1;
    }

    /**
     * Setter for <code>invopay.patient_1.patient_address_line1</code>.
     */
    public Patient_1DTO setPatientAddressLine1(String patientAddressLine1) {
        this.patientAddressLine1 = patientAddressLine1;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_1.patient_address_line2</code>.
     */
    public String getPatientAddressLine2() {
        return this.patientAddressLine2;
    }

    /**
     * Setter for <code>invopay.patient_1.patient_address_line2</code>.
     */
    public Patient_1DTO setPatientAddressLine2(String patientAddressLine2) {
        this.patientAddressLine2 = patientAddressLine2;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_1.patient_address_line3</code>.
     */
    public String getPatientAddressLine3() {
        return this.patientAddressLine3;
    }

    /**
     * Setter for <code>invopay.patient_1.patient_address_line3</code>.
     */
    public Patient_1DTO setPatientAddressLine3(String patientAddressLine3) {
        this.patientAddressLine3 = patientAddressLine3;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_1.ref_country_id</code>.
     */
    public Integer getRefCountryId() {
        return this.refCountryId;
    }

    /**
     * Setter for <code>invopay.patient_1.ref_country_id</code>.
     */
    public Patient_1DTO setRefCountryId(Integer refCountryId) {
        this.refCountryId = refCountryId;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_1.ref_state_id</code>.
     */
    public Integer getRefStateId() {
        return this.refStateId;
    }

    /**
     * Setter for <code>invopay.patient_1.ref_state_id</code>.
     */
    public Patient_1DTO setRefStateId(Integer refStateId) {
        this.refStateId = refStateId;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_1.ref_district_id</code>.
     */
    public Integer getRefDistrictId() {
        return this.refDistrictId;
    }

    /**
     * Setter for <code>invopay.patient_1.ref_district_id</code>.
     */
    public Patient_1DTO setRefDistrictId(Integer refDistrictId) {
        this.refDistrictId = refDistrictId;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_1.pincode</code>.
     */
    public Integer getPincode() {
        return this.pincode;
    }

    /**
     * Setter for <code>invopay.patient_1.pincode</code>.
     */
    public Patient_1DTO setPincode(Integer pincode) {
        this.pincode = pincode;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_1.ref_patient_reference_id</code>.
     */
    public Integer getRefPatientReferenceId() {
        return this.refPatientReferenceId;
    }

    /**
     * Setter for <code>invopay.patient_1.ref_patient_reference_id</code>.
     */
    public Patient_1DTO setRefPatientReferenceId(Integer refPatientReferenceId) {
        this.refPatientReferenceId = refPatientReferenceId;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_1.ref_user_id</code>.
     */
    public Integer getRefUserId() {
        return this.refUserId;
    }

    /**
     * Setter for <code>invopay.patient_1.ref_user_id</code>.
     */
    public Patient_1DTO setRefUserId(Integer refUserId) {
        this.refUserId = refUserId;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_1.delete_status</code>.
     */
    public Integer getDeleteStatus() {
        return this.deleteStatus;
    }

    /**
     * Setter for <code>invopay.patient_1.delete_status</code>.
     */
    public Patient_1DTO setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_1.transaction_id</code>.
     */
    public Integer getTransactionId() {
        return this.transactionId;
    }

    /**
     * Setter for <code>invopay.patient_1.transaction_id</code>.
     */
    public Patient_1DTO setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_1.added_date</code>.
     */
    public LocalDateTime getAddedDate() {
        return this.addedDate;
    }

    /**
     * Setter for <code>invopay.patient_1.added_date</code>.
     */
    public Patient_1DTO setAddedDate(LocalDateTime addedDate) {
        this.addedDate = addedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Patient_1DTO other = (Patient_1DTO) obj;
        if (patientId == null) {
            if (other.patientId != null)
                return false;
        }
        else if (!patientId.equals(other.patientId))
            return false;
        if (patientName == null) {
            if (other.patientName != null)
                return false;
        }
        else if (!patientName.equals(other.patientName))
            return false;
        if (profilePic == null) {
            if (other.profilePic != null)
                return false;
        }
        else if (!profilePic.equals(other.profilePic))
            return false;
        if (email == null) {
            if (other.email != null)
                return false;
        }
        else if (!email.equals(other.email))
            return false;
        if (mobile == null) {
            if (other.mobile != null)
                return false;
        }
        else if (!mobile.equals(other.mobile))
            return false;
        if (age == null) {
            if (other.age != null)
                return false;
        }
        else if (!age.equals(other.age))
            return false;
        if (weight == null) {
            if (other.weight != null)
                return false;
        }
        else if (!weight.equals(other.weight))
            return false;
        if (gender == null) {
            if (other.gender != null)
                return false;
        }
        else if (!gender.equals(other.gender))
            return false;
        if (patientAddressLine1 == null) {
            if (other.patientAddressLine1 != null)
                return false;
        }
        else if (!patientAddressLine1.equals(other.patientAddressLine1))
            return false;
        if (patientAddressLine2 == null) {
            if (other.patientAddressLine2 != null)
                return false;
        }
        else if (!patientAddressLine2.equals(other.patientAddressLine2))
            return false;
        if (patientAddressLine3 == null) {
            if (other.patientAddressLine3 != null)
                return false;
        }
        else if (!patientAddressLine3.equals(other.patientAddressLine3))
            return false;
        if (refCountryId == null) {
            if (other.refCountryId != null)
                return false;
        }
        else if (!refCountryId.equals(other.refCountryId))
            return false;
        if (refStateId == null) {
            if (other.refStateId != null)
                return false;
        }
        else if (!refStateId.equals(other.refStateId))
            return false;
        if (refDistrictId == null) {
            if (other.refDistrictId != null)
                return false;
        }
        else if (!refDistrictId.equals(other.refDistrictId))
            return false;
        if (pincode == null) {
            if (other.pincode != null)
                return false;
        }
        else if (!pincode.equals(other.pincode))
            return false;
        if (refPatientReferenceId == null) {
            if (other.refPatientReferenceId != null)
                return false;
        }
        else if (!refPatientReferenceId.equals(other.refPatientReferenceId))
            return false;
        if (refUserId == null) {
            if (other.refUserId != null)
                return false;
        }
        else if (!refUserId.equals(other.refUserId))
            return false;
        if (deleteStatus == null) {
            if (other.deleteStatus != null)
                return false;
        }
        else if (!deleteStatus.equals(other.deleteStatus))
            return false;
        if (transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!transactionId.equals(other.transactionId))
            return false;
        if (addedDate == null) {
            if (other.addedDate != null)
                return false;
        }
        else if (!addedDate.equals(other.addedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.patientId == null) ? 0 : this.patientId.hashCode());
        result = prime * result + ((this.patientName == null) ? 0 : this.patientName.hashCode());
        result = prime * result + ((this.profilePic == null) ? 0 : this.profilePic.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.mobile == null) ? 0 : this.mobile.hashCode());
        result = prime * result + ((this.age == null) ? 0 : this.age.hashCode());
        result = prime * result + ((this.weight == null) ? 0 : this.weight.hashCode());
        result = prime * result + ((this.gender == null) ? 0 : this.gender.hashCode());
        result = prime * result + ((this.patientAddressLine1 == null) ? 0 : this.patientAddressLine1.hashCode());
        result = prime * result + ((this.patientAddressLine2 == null) ? 0 : this.patientAddressLine2.hashCode());
        result = prime * result + ((this.patientAddressLine3 == null) ? 0 : this.patientAddressLine3.hashCode());
        result = prime * result + ((this.refCountryId == null) ? 0 : this.refCountryId.hashCode());
        result = prime * result + ((this.refStateId == null) ? 0 : this.refStateId.hashCode());
        result = prime * result + ((this.refDistrictId == null) ? 0 : this.refDistrictId.hashCode());
        result = prime * result + ((this.pincode == null) ? 0 : this.pincode.hashCode());
        result = prime * result + ((this.refPatientReferenceId == null) ? 0 : this.refPatientReferenceId.hashCode());
        result = prime * result + ((this.refUserId == null) ? 0 : this.refUserId.hashCode());
        result = prime * result + ((this.deleteStatus == null) ? 0 : this.deleteStatus.hashCode());
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.addedDate == null) ? 0 : this.addedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Patient_1 (");

        sb.append(patientId);
        sb.append(", ").append(patientName);
        sb.append(", ").append(profilePic);
        sb.append(", ").append(email);
        sb.append(", ").append(mobile);
        sb.append(", ").append(age);
        sb.append(", ").append(weight);
        sb.append(", ").append(gender);
        sb.append(", ").append(patientAddressLine1);
        sb.append(", ").append(patientAddressLine2);
        sb.append(", ").append(patientAddressLine3);
        sb.append(", ").append(refCountryId);
        sb.append(", ").append(refStateId);
        sb.append(", ").append(refDistrictId);
        sb.append(", ").append(pincode);
        sb.append(", ").append(refPatientReferenceId);
        sb.append(", ").append(refUserId);
        sb.append(", ").append(deleteStatus);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(addedDate);

        sb.append(")");
        return sb.toString();
    }
}
