/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.DTO;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PatientPanchakarmaDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       patientPanchakarmaId;
    private Integer       refPanchakarmaId;
    private Integer       duration;
    private Integer       refPatientVisitId;
    private Integer       refUserId;
    private Integer       deleteStatus;
    private Integer       transactionId;
    private LocalDateTime addedDate;

    public PatientPanchakarmaDTO() {}

    public PatientPanchakarmaDTO(PatientPanchakarmaDTO value) {
        this.patientPanchakarmaId = value.patientPanchakarmaId;
        this.refPanchakarmaId = value.refPanchakarmaId;
        this.duration = value.duration;
        this.refPatientVisitId = value.refPatientVisitId;
        this.refUserId = value.refUserId;
        this.deleteStatus = value.deleteStatus;
        this.transactionId = value.transactionId;
        this.addedDate = value.addedDate;
    }

    public PatientPanchakarmaDTO(
        Integer       patientPanchakarmaId,
        Integer       refPanchakarmaId,
        Integer       duration,
        Integer       refPatientVisitId,
        Integer       refUserId,
        Integer       deleteStatus,
        Integer       transactionId,
        LocalDateTime addedDate
    ) {
        this.patientPanchakarmaId = patientPanchakarmaId;
        this.refPanchakarmaId = refPanchakarmaId;
        this.duration = duration;
        this.refPatientVisitId = refPatientVisitId;
        this.refUserId = refUserId;
        this.deleteStatus = deleteStatus;
        this.transactionId = transactionId;
        this.addedDate = addedDate;
    }

    /**
     * Getter for <code>invopay.patient_panchakarma.patient_panchakarma_id</code>.
     */
    public Integer getPatientPanchakarmaId() {
        return this.patientPanchakarmaId;
    }

    /**
     * Setter for <code>invopay.patient_panchakarma.patient_panchakarma_id</code>.
     */
    public PatientPanchakarmaDTO setPatientPanchakarmaId(Integer patientPanchakarmaId) {
        this.patientPanchakarmaId = patientPanchakarmaId;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_panchakarma.ref_panchakarma_id</code>.
     */
    public Integer getRefPanchakarmaId() {
        return this.refPanchakarmaId;
    }

    /**
     * Setter for <code>invopay.patient_panchakarma.ref_panchakarma_id</code>.
     */
    public PatientPanchakarmaDTO setRefPanchakarmaId(Integer refPanchakarmaId) {
        this.refPanchakarmaId = refPanchakarmaId;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_panchakarma.duration</code>.
     */
    public Integer getDuration() {
        return this.duration;
    }

    /**
     * Setter for <code>invopay.patient_panchakarma.duration</code>.
     */
    public PatientPanchakarmaDTO setDuration(Integer duration) {
        this.duration = duration;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_panchakarma.ref_patient_visit_id</code>.
     */
    public Integer getRefPatientVisitId() {
        return this.refPatientVisitId;
    }

    /**
     * Setter for <code>invopay.patient_panchakarma.ref_patient_visit_id</code>.
     */
    public PatientPanchakarmaDTO setRefPatientVisitId(Integer refPatientVisitId) {
        this.refPatientVisitId = refPatientVisitId;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_panchakarma.ref_user_id</code>.
     */
    public Integer getRefUserId() {
        return this.refUserId;
    }

    /**
     * Setter for <code>invopay.patient_panchakarma.ref_user_id</code>.
     */
    public PatientPanchakarmaDTO setRefUserId(Integer refUserId) {
        this.refUserId = refUserId;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_panchakarma.delete_status</code>.
     */
    public Integer getDeleteStatus() {
        return this.deleteStatus;
    }

    /**
     * Setter for <code>invopay.patient_panchakarma.delete_status</code>.
     */
    public PatientPanchakarmaDTO setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_panchakarma.transaction_id</code>.
     */
    public Integer getTransactionId() {
        return this.transactionId;
    }

    /**
     * Setter for <code>invopay.patient_panchakarma.transaction_id</code>.
     */
    public PatientPanchakarmaDTO setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
        return this;
    }

    /**
     * Getter for <code>invopay.patient_panchakarma.added_date</code>.
     */
    public LocalDateTime getAddedDate() {
        return this.addedDate;
    }

    /**
     * Setter for <code>invopay.patient_panchakarma.added_date</code>.
     */
    public PatientPanchakarmaDTO setAddedDate(LocalDateTime addedDate) {
        this.addedDate = addedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PatientPanchakarmaDTO other = (PatientPanchakarmaDTO) obj;
        if (patientPanchakarmaId == null) {
            if (other.patientPanchakarmaId != null)
                return false;
        }
        else if (!patientPanchakarmaId.equals(other.patientPanchakarmaId))
            return false;
        if (refPanchakarmaId == null) {
            if (other.refPanchakarmaId != null)
                return false;
        }
        else if (!refPanchakarmaId.equals(other.refPanchakarmaId))
            return false;
        if (duration == null) {
            if (other.duration != null)
                return false;
        }
        else if (!duration.equals(other.duration))
            return false;
        if (refPatientVisitId == null) {
            if (other.refPatientVisitId != null)
                return false;
        }
        else if (!refPatientVisitId.equals(other.refPatientVisitId))
            return false;
        if (refUserId == null) {
            if (other.refUserId != null)
                return false;
        }
        else if (!refUserId.equals(other.refUserId))
            return false;
        if (deleteStatus == null) {
            if (other.deleteStatus != null)
                return false;
        }
        else if (!deleteStatus.equals(other.deleteStatus))
            return false;
        if (transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!transactionId.equals(other.transactionId))
            return false;
        if (addedDate == null) {
            if (other.addedDate != null)
                return false;
        }
        else if (!addedDate.equals(other.addedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.patientPanchakarmaId == null) ? 0 : this.patientPanchakarmaId.hashCode());
        result = prime * result + ((this.refPanchakarmaId == null) ? 0 : this.refPanchakarmaId.hashCode());
        result = prime * result + ((this.duration == null) ? 0 : this.duration.hashCode());
        result = prime * result + ((this.refPatientVisitId == null) ? 0 : this.refPatientVisitId.hashCode());
        result = prime * result + ((this.refUserId == null) ? 0 : this.refUserId.hashCode());
        result = prime * result + ((this.deleteStatus == null) ? 0 : this.deleteStatus.hashCode());
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.addedDate == null) ? 0 : this.addedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PatientPanchakarma (");

        sb.append(patientPanchakarmaId);
        sb.append(", ").append(refPanchakarmaId);
        sb.append(", ").append(duration);
        sb.append(", ").append(refPatientVisitId);
        sb.append(", ").append(refUserId);
        sb.append(", ").append(deleteStatus);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(addedDate);

        sb.append(")");
        return sb.toString();
    }
}
