/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.DTO;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentTypeDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       paymentTypeId;
    private String        paymentTypeName;
    private Integer       refUserId;
    private Integer       deleteStatus;
    private Integer       transactionId;
    private LocalDateTime addedDate;

    public PaymentTypeDTO() {}

    public PaymentTypeDTO(PaymentTypeDTO value) {
        this.paymentTypeId = value.paymentTypeId;
        this.paymentTypeName = value.paymentTypeName;
        this.refUserId = value.refUserId;
        this.deleteStatus = value.deleteStatus;
        this.transactionId = value.transactionId;
        this.addedDate = value.addedDate;
    }

    public PaymentTypeDTO(
        Integer       paymentTypeId,
        String        paymentTypeName,
        Integer       refUserId,
        Integer       deleteStatus,
        Integer       transactionId,
        LocalDateTime addedDate
    ) {
        this.paymentTypeId = paymentTypeId;
        this.paymentTypeName = paymentTypeName;
        this.refUserId = refUserId;
        this.deleteStatus = deleteStatus;
        this.transactionId = transactionId;
        this.addedDate = addedDate;
    }

    /**
     * Getter for <code>invopay.payment_type.payment_type_id</code>.
     */
    public Integer getPaymentTypeId() {
        return this.paymentTypeId;
    }

    /**
     * Setter for <code>invopay.payment_type.payment_type_id</code>.
     */
    public PaymentTypeDTO setPaymentTypeId(Integer paymentTypeId) {
        this.paymentTypeId = paymentTypeId;
        return this;
    }

    /**
     * Getter for <code>invopay.payment_type.payment_type_name</code>.
     */
    public String getPaymentTypeName() {
        return this.paymentTypeName;
    }

    /**
     * Setter for <code>invopay.payment_type.payment_type_name</code>.
     */
    public PaymentTypeDTO setPaymentTypeName(String paymentTypeName) {
        this.paymentTypeName = paymentTypeName;
        return this;
    }

    /**
     * Getter for <code>invopay.payment_type.ref_user_id</code>.
     */
    public Integer getRefUserId() {
        return this.refUserId;
    }

    /**
     * Setter for <code>invopay.payment_type.ref_user_id</code>.
     */
    public PaymentTypeDTO setRefUserId(Integer refUserId) {
        this.refUserId = refUserId;
        return this;
    }

    /**
     * Getter for <code>invopay.payment_type.delete_status</code>.
     */
    public Integer getDeleteStatus() {
        return this.deleteStatus;
    }

    /**
     * Setter for <code>invopay.payment_type.delete_status</code>.
     */
    public PaymentTypeDTO setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.payment_type.transaction_id</code>.
     */
    public Integer getTransactionId() {
        return this.transactionId;
    }

    /**
     * Setter for <code>invopay.payment_type.transaction_id</code>.
     */
    public PaymentTypeDTO setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
        return this;
    }

    /**
     * Getter for <code>invopay.payment_type.added_date</code>.
     */
    public LocalDateTime getAddedDate() {
        return this.addedDate;
    }

    /**
     * Setter for <code>invopay.payment_type.added_date</code>.
     */
    public PaymentTypeDTO setAddedDate(LocalDateTime addedDate) {
        this.addedDate = addedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PaymentTypeDTO other = (PaymentTypeDTO) obj;
        if (paymentTypeId == null) {
            if (other.paymentTypeId != null)
                return false;
        }
        else if (!paymentTypeId.equals(other.paymentTypeId))
            return false;
        if (paymentTypeName == null) {
            if (other.paymentTypeName != null)
                return false;
        }
        else if (!paymentTypeName.equals(other.paymentTypeName))
            return false;
        if (refUserId == null) {
            if (other.refUserId != null)
                return false;
        }
        else if (!refUserId.equals(other.refUserId))
            return false;
        if (deleteStatus == null) {
            if (other.deleteStatus != null)
                return false;
        }
        else if (!deleteStatus.equals(other.deleteStatus))
            return false;
        if (transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!transactionId.equals(other.transactionId))
            return false;
        if (addedDate == null) {
            if (other.addedDate != null)
                return false;
        }
        else if (!addedDate.equals(other.addedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.paymentTypeId == null) ? 0 : this.paymentTypeId.hashCode());
        result = prime * result + ((this.paymentTypeName == null) ? 0 : this.paymentTypeName.hashCode());
        result = prime * result + ((this.refUserId == null) ? 0 : this.refUserId.hashCode());
        result = prime * result + ((this.deleteStatus == null) ? 0 : this.deleteStatus.hashCode());
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.addedDate == null) ? 0 : this.addedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PaymentType (");

        sb.append(paymentTypeId);
        sb.append(", ").append(paymentTypeName);
        sb.append(", ").append(refUserId);
        sb.append(", ").append(deleteStatus);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(addedDate);

        sb.append(")");
        return sb.toString();
    }
}
