/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.DTO;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Product1DTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       productId;
    private String        productName;
    private String        protocol;
    private String        manufacturer;
    private String        model;
    private String        buildMonthYear;
    private String        serialNumber;
    private String        denomination;
    private String        cabinetStyle;
    private String        screenSize;
    private String        linkReady;
    private String        titoBrand;
    private String        validatorBrand;
    private Double        price;
    private String        description;
    private Integer       displayHomepage;
    private Byte          activeStatus;
    private Integer       deleteStatus;
    private Integer       refUserId;
    private Integer       transactionId;
    private LocalDateTime addedDate;

    public Product1DTO() {}

    public Product1DTO(Product1DTO value) {
        this.productId = value.productId;
        this.productName = value.productName;
        this.protocol = value.protocol;
        this.manufacturer = value.manufacturer;
        this.model = value.model;
        this.buildMonthYear = value.buildMonthYear;
        this.serialNumber = value.serialNumber;
        this.denomination = value.denomination;
        this.cabinetStyle = value.cabinetStyle;
        this.screenSize = value.screenSize;
        this.linkReady = value.linkReady;
        this.titoBrand = value.titoBrand;
        this.validatorBrand = value.validatorBrand;
        this.price = value.price;
        this.description = value.description;
        this.displayHomepage = value.displayHomepage;
        this.activeStatus = value.activeStatus;
        this.deleteStatus = value.deleteStatus;
        this.refUserId = value.refUserId;
        this.transactionId = value.transactionId;
        this.addedDate = value.addedDate;
    }

    public Product1DTO(
        Integer       productId,
        String        productName,
        String        protocol,
        String        manufacturer,
        String        model,
        String        buildMonthYear,
        String        serialNumber,
        String        denomination,
        String        cabinetStyle,
        String        screenSize,
        String        linkReady,
        String        titoBrand,
        String        validatorBrand,
        Double        price,
        String        description,
        Integer       displayHomepage,
        Byte          activeStatus,
        Integer       deleteStatus,
        Integer       refUserId,
        Integer       transactionId,
        LocalDateTime addedDate
    ) {
        this.productId = productId;
        this.productName = productName;
        this.protocol = protocol;
        this.manufacturer = manufacturer;
        this.model = model;
        this.buildMonthYear = buildMonthYear;
        this.serialNumber = serialNumber;
        this.denomination = denomination;
        this.cabinetStyle = cabinetStyle;
        this.screenSize = screenSize;
        this.linkReady = linkReady;
        this.titoBrand = titoBrand;
        this.validatorBrand = validatorBrand;
        this.price = price;
        this.description = description;
        this.displayHomepage = displayHomepage;
        this.activeStatus = activeStatus;
        this.deleteStatus = deleteStatus;
        this.refUserId = refUserId;
        this.transactionId = transactionId;
        this.addedDate = addedDate;
    }

    /**
     * Getter for <code>invopay.product1.product_id</code>.
     */
    public Integer getProductId() {
        return this.productId;
    }

    /**
     * Setter for <code>invopay.product1.product_id</code>.
     */
    public Product1DTO setProductId(Integer productId) {
        this.productId = productId;
        return this;
    }

    /**
     * Getter for <code>invopay.product1.product_name</code>.
     */
    public String getProductName() {
        return this.productName;
    }

    /**
     * Setter for <code>invopay.product1.product_name</code>.
     */
    public Product1DTO setProductName(String productName) {
        this.productName = productName;
        return this;
    }

    /**
     * Getter for <code>invopay.product1.protocol</code>.
     */
    public String getProtocol() {
        return this.protocol;
    }

    /**
     * Setter for <code>invopay.product1.protocol</code>.
     */
    public Product1DTO setProtocol(String protocol) {
        this.protocol = protocol;
        return this;
    }

    /**
     * Getter for <code>invopay.product1.manufacturer</code>.
     */
    public String getManufacturer() {
        return this.manufacturer;
    }

    /**
     * Setter for <code>invopay.product1.manufacturer</code>.
     */
    public Product1DTO setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
        return this;
    }

    /**
     * Getter for <code>invopay.product1.model</code>.
     */
    public String getModel() {
        return this.model;
    }

    /**
     * Setter for <code>invopay.product1.model</code>.
     */
    public Product1DTO setModel(String model) {
        this.model = model;
        return this;
    }

    /**
     * Getter for <code>invopay.product1.build_month_year</code>.
     */
    public String getBuildMonthYear() {
        return this.buildMonthYear;
    }

    /**
     * Setter for <code>invopay.product1.build_month_year</code>.
     */
    public Product1DTO setBuildMonthYear(String buildMonthYear) {
        this.buildMonthYear = buildMonthYear;
        return this;
    }

    /**
     * Getter for <code>invopay.product1.serial_number</code>.
     */
    public String getSerialNumber() {
        return this.serialNumber;
    }

    /**
     * Setter for <code>invopay.product1.serial_number</code>.
     */
    public Product1DTO setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
        return this;
    }

    /**
     * Getter for <code>invopay.product1.denomination</code>.
     */
    public String getDenomination() {
        return this.denomination;
    }

    /**
     * Setter for <code>invopay.product1.denomination</code>.
     */
    public Product1DTO setDenomination(String denomination) {
        this.denomination = denomination;
        return this;
    }

    /**
     * Getter for <code>invopay.product1.cabinet_style</code>.
     */
    public String getCabinetStyle() {
        return this.cabinetStyle;
    }

    /**
     * Setter for <code>invopay.product1.cabinet_style</code>.
     */
    public Product1DTO setCabinetStyle(String cabinetStyle) {
        this.cabinetStyle = cabinetStyle;
        return this;
    }

    /**
     * Getter for <code>invopay.product1.screen_size</code>.
     */
    public String getScreenSize() {
        return this.screenSize;
    }

    /**
     * Setter for <code>invopay.product1.screen_size</code>.
     */
    public Product1DTO setScreenSize(String screenSize) {
        this.screenSize = screenSize;
        return this;
    }

    /**
     * Getter for <code>invopay.product1.link_ready</code>.
     */
    public String getLinkReady() {
        return this.linkReady;
    }

    /**
     * Setter for <code>invopay.product1.link_ready</code>.
     */
    public Product1DTO setLinkReady(String linkReady) {
        this.linkReady = linkReady;
        return this;
    }

    /**
     * Getter for <code>invopay.product1.tito_brand</code>.
     */
    public String getTitoBrand() {
        return this.titoBrand;
    }

    /**
     * Setter for <code>invopay.product1.tito_brand</code>.
     */
    public Product1DTO setTitoBrand(String titoBrand) {
        this.titoBrand = titoBrand;
        return this;
    }

    /**
     * Getter for <code>invopay.product1.validator_brand</code>.
     */
    public String getValidatorBrand() {
        return this.validatorBrand;
    }

    /**
     * Setter for <code>invopay.product1.validator_brand</code>.
     */
    public Product1DTO setValidatorBrand(String validatorBrand) {
        this.validatorBrand = validatorBrand;
        return this;
    }

    /**
     * Getter for <code>invopay.product1.price</code>.
     */
    public Double getPrice() {
        return this.price;
    }

    /**
     * Setter for <code>invopay.product1.price</code>.
     */
    public Product1DTO setPrice(Double price) {
        this.price = price;
        return this;
    }

    /**
     * Getter for <code>invopay.product1.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>invopay.product1.description</code>.
     */
    public Product1DTO setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Getter for <code>invopay.product1.display_homepage</code>.
     */
    public Integer getDisplayHomepage() {
        return this.displayHomepage;
    }

    /**
     * Setter for <code>invopay.product1.display_homepage</code>.
     */
    public Product1DTO setDisplayHomepage(Integer displayHomepage) {
        this.displayHomepage = displayHomepage;
        return this;
    }

    /**
     * Getter for <code>invopay.product1.active_status</code>.
     */
    public Byte getActiveStatus() {
        return this.activeStatus;
    }

    /**
     * Setter for <code>invopay.product1.active_status</code>.
     */
    public Product1DTO setActiveStatus(Byte activeStatus) {
        this.activeStatus = activeStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.product1.delete_status</code>.
     */
    public Integer getDeleteStatus() {
        return this.deleteStatus;
    }

    /**
     * Setter for <code>invopay.product1.delete_status</code>.
     */
    public Product1DTO setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.product1.ref_user_id</code>. User
     */
    public Integer getRefUserId() {
        return this.refUserId;
    }

    /**
     * Setter for <code>invopay.product1.ref_user_id</code>. User
     */
    public Product1DTO setRefUserId(Integer refUserId) {
        this.refUserId = refUserId;
        return this;
    }

    /**
     * Getter for <code>invopay.product1.transaction_id</code>.
     */
    public Integer getTransactionId() {
        return this.transactionId;
    }

    /**
     * Setter for <code>invopay.product1.transaction_id</code>.
     */
    public Product1DTO setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
        return this;
    }

    /**
     * Getter for <code>invopay.product1.added_date</code>. Added Date
     */
    public LocalDateTime getAddedDate() {
        return this.addedDate;
    }

    /**
     * Setter for <code>invopay.product1.added_date</code>. Added Date
     */
    public Product1DTO setAddedDate(LocalDateTime addedDate) {
        this.addedDate = addedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Product1DTO other = (Product1DTO) obj;
        if (productId == null) {
            if (other.productId != null)
                return false;
        }
        else if (!productId.equals(other.productId))
            return false;
        if (productName == null) {
            if (other.productName != null)
                return false;
        }
        else if (!productName.equals(other.productName))
            return false;
        if (protocol == null) {
            if (other.protocol != null)
                return false;
        }
        else if (!protocol.equals(other.protocol))
            return false;
        if (manufacturer == null) {
            if (other.manufacturer != null)
                return false;
        }
        else if (!manufacturer.equals(other.manufacturer))
            return false;
        if (model == null) {
            if (other.model != null)
                return false;
        }
        else if (!model.equals(other.model))
            return false;
        if (buildMonthYear == null) {
            if (other.buildMonthYear != null)
                return false;
        }
        else if (!buildMonthYear.equals(other.buildMonthYear))
            return false;
        if (serialNumber == null) {
            if (other.serialNumber != null)
                return false;
        }
        else if (!serialNumber.equals(other.serialNumber))
            return false;
        if (denomination == null) {
            if (other.denomination != null)
                return false;
        }
        else if (!denomination.equals(other.denomination))
            return false;
        if (cabinetStyle == null) {
            if (other.cabinetStyle != null)
                return false;
        }
        else if (!cabinetStyle.equals(other.cabinetStyle))
            return false;
        if (screenSize == null) {
            if (other.screenSize != null)
                return false;
        }
        else if (!screenSize.equals(other.screenSize))
            return false;
        if (linkReady == null) {
            if (other.linkReady != null)
                return false;
        }
        else if (!linkReady.equals(other.linkReady))
            return false;
        if (titoBrand == null) {
            if (other.titoBrand != null)
                return false;
        }
        else if (!titoBrand.equals(other.titoBrand))
            return false;
        if (validatorBrand == null) {
            if (other.validatorBrand != null)
                return false;
        }
        else if (!validatorBrand.equals(other.validatorBrand))
            return false;
        if (price == null) {
            if (other.price != null)
                return false;
        }
        else if (!price.equals(other.price))
            return false;
        if (description == null) {
            if (other.description != null)
                return false;
        }
        else if (!description.equals(other.description))
            return false;
        if (displayHomepage == null) {
            if (other.displayHomepage != null)
                return false;
        }
        else if (!displayHomepage.equals(other.displayHomepage))
            return false;
        if (activeStatus == null) {
            if (other.activeStatus != null)
                return false;
        }
        else if (!activeStatus.equals(other.activeStatus))
            return false;
        if (deleteStatus == null) {
            if (other.deleteStatus != null)
                return false;
        }
        else if (!deleteStatus.equals(other.deleteStatus))
            return false;
        if (refUserId == null) {
            if (other.refUserId != null)
                return false;
        }
        else if (!refUserId.equals(other.refUserId))
            return false;
        if (transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!transactionId.equals(other.transactionId))
            return false;
        if (addedDate == null) {
            if (other.addedDate != null)
                return false;
        }
        else if (!addedDate.equals(other.addedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.productId == null) ? 0 : this.productId.hashCode());
        result = prime * result + ((this.productName == null) ? 0 : this.productName.hashCode());
        result = prime * result + ((this.protocol == null) ? 0 : this.protocol.hashCode());
        result = prime * result + ((this.manufacturer == null) ? 0 : this.manufacturer.hashCode());
        result = prime * result + ((this.model == null) ? 0 : this.model.hashCode());
        result = prime * result + ((this.buildMonthYear == null) ? 0 : this.buildMonthYear.hashCode());
        result = prime * result + ((this.serialNumber == null) ? 0 : this.serialNumber.hashCode());
        result = prime * result + ((this.denomination == null) ? 0 : this.denomination.hashCode());
        result = prime * result + ((this.cabinetStyle == null) ? 0 : this.cabinetStyle.hashCode());
        result = prime * result + ((this.screenSize == null) ? 0 : this.screenSize.hashCode());
        result = prime * result + ((this.linkReady == null) ? 0 : this.linkReady.hashCode());
        result = prime * result + ((this.titoBrand == null) ? 0 : this.titoBrand.hashCode());
        result = prime * result + ((this.validatorBrand == null) ? 0 : this.validatorBrand.hashCode());
        result = prime * result + ((this.price == null) ? 0 : this.price.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.displayHomepage == null) ? 0 : this.displayHomepage.hashCode());
        result = prime * result + ((this.activeStatus == null) ? 0 : this.activeStatus.hashCode());
        result = prime * result + ((this.deleteStatus == null) ? 0 : this.deleteStatus.hashCode());
        result = prime * result + ((this.refUserId == null) ? 0 : this.refUserId.hashCode());
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.addedDate == null) ? 0 : this.addedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Product1 (");

        sb.append(productId);
        sb.append(", ").append(productName);
        sb.append(", ").append(protocol);
        sb.append(", ").append(manufacturer);
        sb.append(", ").append(model);
        sb.append(", ").append(buildMonthYear);
        sb.append(", ").append(serialNumber);
        sb.append(", ").append(denomination);
        sb.append(", ").append(cabinetStyle);
        sb.append(", ").append(screenSize);
        sb.append(", ").append(linkReady);
        sb.append(", ").append(titoBrand);
        sb.append(", ").append(validatorBrand);
        sb.append(", ").append(price);
        sb.append(", ").append(description);
        sb.append(", ").append(displayHomepage);
        sb.append(", ").append(activeStatus);
        sb.append(", ").append(deleteStatus);
        sb.append(", ").append(refUserId);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(addedDate);

        sb.append(")");
        return sb.toString();
    }
}
