/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.DTO;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       productId;
    private Integer       sellerId;
    private Integer       refSupplierId;
    private String        productName;
    private Double        price;
    private String        stipepriceid;
    private Integer       refQuantityTypeId;
    private String        description;
    private Integer       displayHomepage;
    private Byte          activeStatus;
    private Integer       deleteStatus;
    private Integer       refUserId;
    private Integer       transactionId;
    private LocalDateTime addedDate;

    public ProductDTO() {}

    public ProductDTO(ProductDTO value) {
        this.productId = value.productId;
        this.sellerId = value.sellerId;
        this.refSupplierId = value.refSupplierId;
        this.productName = value.productName;
        this.price = value.price;
        this.stipepriceid = value.stipepriceid;
        this.refQuantityTypeId = value.refQuantityTypeId;
        this.description = value.description;
        this.displayHomepage = value.displayHomepage;
        this.activeStatus = value.activeStatus;
        this.deleteStatus = value.deleteStatus;
        this.refUserId = value.refUserId;
        this.transactionId = value.transactionId;
        this.addedDate = value.addedDate;
    }

    public ProductDTO(
        Integer       productId,
        Integer       sellerId,
        Integer       refSupplierId,
        String        productName,
        Double        price,
        String        stipepriceid,
        Integer       refQuantityTypeId,
        String        description,
        Integer       displayHomepage,
        Byte          activeStatus,
        Integer       deleteStatus,
        Integer       refUserId,
        Integer       transactionId,
        LocalDateTime addedDate
    ) {
        this.productId = productId;
        this.sellerId = sellerId;
        this.refSupplierId = refSupplierId;
        this.productName = productName;
        this.price = price;
        this.stipepriceid = stipepriceid;
        this.refQuantityTypeId = refQuantityTypeId;
        this.description = description;
        this.displayHomepage = displayHomepage;
        this.activeStatus = activeStatus;
        this.deleteStatus = deleteStatus;
        this.refUserId = refUserId;
        this.transactionId = transactionId;
        this.addedDate = addedDate;
    }

    /**
     * Getter for <code>invopay.product.product_id</code>.
     */
    public Integer getProductId() {
        return this.productId;
    }

    /**
     * Setter for <code>invopay.product.product_id</code>.
     */
    public ProductDTO setProductId(Integer productId) {
        this.productId = productId;
        return this;
    }

    /**
     * Getter for <code>invopay.product.seller_id</code>.
     */
    public Integer getSellerId() {
        return this.sellerId;
    }

    /**
     * Setter for <code>invopay.product.seller_id</code>.
     */
    public ProductDTO setSellerId(Integer sellerId) {
        this.sellerId = sellerId;
        return this;
    }

    /**
     * Getter for <code>invopay.product.ref_supplier_id</code>.
     */
    public Integer getRefSupplierId() {
        return this.refSupplierId;
    }

    /**
     * Setter for <code>invopay.product.ref_supplier_id</code>.
     */
    public ProductDTO setRefSupplierId(Integer refSupplierId) {
        this.refSupplierId = refSupplierId;
        return this;
    }

    /**
     * Getter for <code>invopay.product.product_name</code>.
     */
    public String getProductName() {
        return this.productName;
    }

    /**
     * Setter for <code>invopay.product.product_name</code>.
     */
    public ProductDTO setProductName(String productName) {
        this.productName = productName;
        return this;
    }

    /**
     * Getter for <code>invopay.product.price</code>.
     */
    public Double getPrice() {
        return this.price;
    }

    /**
     * Setter for <code>invopay.product.price</code>.
     */
    public ProductDTO setPrice(Double price) {
        this.price = price;
        return this;
    }

    /**
     * Getter for <code>invopay.product.stipepriceID</code>.
     */
    public String getStipepriceid() {
        return this.stipepriceid;
    }

    /**
     * Setter for <code>invopay.product.stipepriceID</code>.
     */
    public ProductDTO setStipepriceid(String stipepriceid) {
        this.stipepriceid = stipepriceid;
        return this;
    }

    /**
     * Getter for <code>invopay.product.ref_quantity_type_id</code>.
     */
    public Integer getRefQuantityTypeId() {
        return this.refQuantityTypeId;
    }

    /**
     * Setter for <code>invopay.product.ref_quantity_type_id</code>.
     */
    public ProductDTO setRefQuantityTypeId(Integer refQuantityTypeId) {
        this.refQuantityTypeId = refQuantityTypeId;
        return this;
    }

    /**
     * Getter for <code>invopay.product.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>invopay.product.description</code>.
     */
    public ProductDTO setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Getter for <code>invopay.product.display_homepage</code>.
     */
    public Integer getDisplayHomepage() {
        return this.displayHomepage;
    }

    /**
     * Setter for <code>invopay.product.display_homepage</code>.
     */
    public ProductDTO setDisplayHomepage(Integer displayHomepage) {
        this.displayHomepage = displayHomepage;
        return this;
    }

    /**
     * Getter for <code>invopay.product.active_status</code>.
     */
    public Byte getActiveStatus() {
        return this.activeStatus;
    }

    /**
     * Setter for <code>invopay.product.active_status</code>.
     */
    public ProductDTO setActiveStatus(Byte activeStatus) {
        this.activeStatus = activeStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.product.delete_status</code>.
     */
    public Integer getDeleteStatus() {
        return this.deleteStatus;
    }

    /**
     * Setter for <code>invopay.product.delete_status</code>.
     */
    public ProductDTO setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.product.ref_user_id</code>. User
     */
    public Integer getRefUserId() {
        return this.refUserId;
    }

    /**
     * Setter for <code>invopay.product.ref_user_id</code>. User
     */
    public ProductDTO setRefUserId(Integer refUserId) {
        this.refUserId = refUserId;
        return this;
    }

    /**
     * Getter for <code>invopay.product.transaction_id</code>.
     */
    public Integer getTransactionId() {
        return this.transactionId;
    }

    /**
     * Setter for <code>invopay.product.transaction_id</code>.
     */
    public ProductDTO setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
        return this;
    }

    /**
     * Getter for <code>invopay.product.added_date</code>. Added Date
     */
    public LocalDateTime getAddedDate() {
        return this.addedDate;
    }

    /**
     * Setter for <code>invopay.product.added_date</code>. Added Date
     */
    public ProductDTO setAddedDate(LocalDateTime addedDate) {
        this.addedDate = addedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ProductDTO other = (ProductDTO) obj;
        if (productId == null) {
            if (other.productId != null)
                return false;
        }
        else if (!productId.equals(other.productId))
            return false;
        if (sellerId == null) {
            if (other.sellerId != null)
                return false;
        }
        else if (!sellerId.equals(other.sellerId))
            return false;
        if (refSupplierId == null) {
            if (other.refSupplierId != null)
                return false;
        }
        else if (!refSupplierId.equals(other.refSupplierId))
            return false;
        if (productName == null) {
            if (other.productName != null)
                return false;
        }
        else if (!productName.equals(other.productName))
            return false;
        if (price == null) {
            if (other.price != null)
                return false;
        }
        else if (!price.equals(other.price))
            return false;
        if (stipepriceid == null) {
            if (other.stipepriceid != null)
                return false;
        }
        else if (!stipepriceid.equals(other.stipepriceid))
            return false;
        if (refQuantityTypeId == null) {
            if (other.refQuantityTypeId != null)
                return false;
        }
        else if (!refQuantityTypeId.equals(other.refQuantityTypeId))
            return false;
        if (description == null) {
            if (other.description != null)
                return false;
        }
        else if (!description.equals(other.description))
            return false;
        if (displayHomepage == null) {
            if (other.displayHomepage != null)
                return false;
        }
        else if (!displayHomepage.equals(other.displayHomepage))
            return false;
        if (activeStatus == null) {
            if (other.activeStatus != null)
                return false;
        }
        else if (!activeStatus.equals(other.activeStatus))
            return false;
        if (deleteStatus == null) {
            if (other.deleteStatus != null)
                return false;
        }
        else if (!deleteStatus.equals(other.deleteStatus))
            return false;
        if (refUserId == null) {
            if (other.refUserId != null)
                return false;
        }
        else if (!refUserId.equals(other.refUserId))
            return false;
        if (transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!transactionId.equals(other.transactionId))
            return false;
        if (addedDate == null) {
            if (other.addedDate != null)
                return false;
        }
        else if (!addedDate.equals(other.addedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.productId == null) ? 0 : this.productId.hashCode());
        result = prime * result + ((this.sellerId == null) ? 0 : this.sellerId.hashCode());
        result = prime * result + ((this.refSupplierId == null) ? 0 : this.refSupplierId.hashCode());
        result = prime * result + ((this.productName == null) ? 0 : this.productName.hashCode());
        result = prime * result + ((this.price == null) ? 0 : this.price.hashCode());
        result = prime * result + ((this.stipepriceid == null) ? 0 : this.stipepriceid.hashCode());
        result = prime * result + ((this.refQuantityTypeId == null) ? 0 : this.refQuantityTypeId.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.displayHomepage == null) ? 0 : this.displayHomepage.hashCode());
        result = prime * result + ((this.activeStatus == null) ? 0 : this.activeStatus.hashCode());
        result = prime * result + ((this.deleteStatus == null) ? 0 : this.deleteStatus.hashCode());
        result = prime * result + ((this.refUserId == null) ? 0 : this.refUserId.hashCode());
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.addedDate == null) ? 0 : this.addedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Product (");

        sb.append(productId);
        sb.append(", ").append(sellerId);
        sb.append(", ").append(refSupplierId);
        sb.append(", ").append(productName);
        sb.append(", ").append(price);
        sb.append(", ").append(stipepriceid);
        sb.append(", ").append(refQuantityTypeId);
        sb.append(", ").append(description);
        sb.append(", ").append(displayHomepage);
        sb.append(", ").append(activeStatus);
        sb.append(", ").append(deleteStatus);
        sb.append(", ").append(refUserId);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(addedDate);

        sb.append(")");
        return sb.toString();
    }
}
