/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.DTO;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductRequestDocumentDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       productRequestDocumentId;
    private Integer       refProductSampleRequestId;
    private String        productRequestDocumentName;
    private String        productRequestDocumentFile;
    private Integer       refUserId;
    private Integer       deleteStatus;
    private Integer       transactionId;
    private LocalDateTime addedDate;

    public ProductRequestDocumentDTO() {}

    public ProductRequestDocumentDTO(ProductRequestDocumentDTO value) {
        this.productRequestDocumentId = value.productRequestDocumentId;
        this.refProductSampleRequestId = value.refProductSampleRequestId;
        this.productRequestDocumentName = value.productRequestDocumentName;
        this.productRequestDocumentFile = value.productRequestDocumentFile;
        this.refUserId = value.refUserId;
        this.deleteStatus = value.deleteStatus;
        this.transactionId = value.transactionId;
        this.addedDate = value.addedDate;
    }

    public ProductRequestDocumentDTO(
        Integer       productRequestDocumentId,
        Integer       refProductSampleRequestId,
        String        productRequestDocumentName,
        String        productRequestDocumentFile,
        Integer       refUserId,
        Integer       deleteStatus,
        Integer       transactionId,
        LocalDateTime addedDate
    ) {
        this.productRequestDocumentId = productRequestDocumentId;
        this.refProductSampleRequestId = refProductSampleRequestId;
        this.productRequestDocumentName = productRequestDocumentName;
        this.productRequestDocumentFile = productRequestDocumentFile;
        this.refUserId = refUserId;
        this.deleteStatus = deleteStatus;
        this.transactionId = transactionId;
        this.addedDate = addedDate;
    }

    /**
     * Getter for <code>invopay.product_request_document.product_request_document_id</code>.
     */
    public Integer getProductRequestDocumentId() {
        return this.productRequestDocumentId;
    }

    /**
     * Setter for <code>invopay.product_request_document.product_request_document_id</code>.
     */
    public ProductRequestDocumentDTO setProductRequestDocumentId(Integer productRequestDocumentId) {
        this.productRequestDocumentId = productRequestDocumentId;
        return this;
    }

    /**
     * Getter for <code>invopay.product_request_document.ref_product_sample_request_id</code>.
     */
    public Integer getRefProductSampleRequestId() {
        return this.refProductSampleRequestId;
    }

    /**
     * Setter for <code>invopay.product_request_document.ref_product_sample_request_id</code>.
     */
    public ProductRequestDocumentDTO setRefProductSampleRequestId(Integer refProductSampleRequestId) {
        this.refProductSampleRequestId = refProductSampleRequestId;
        return this;
    }

    /**
     * Getter for <code>invopay.product_request_document.product_request_document_name</code>.
     */
    public String getProductRequestDocumentName() {
        return this.productRequestDocumentName;
    }

    /**
     * Setter for <code>invopay.product_request_document.product_request_document_name</code>.
     */
    public ProductRequestDocumentDTO setProductRequestDocumentName(String productRequestDocumentName) {
        this.productRequestDocumentName = productRequestDocumentName;
        return this;
    }

    /**
     * Getter for <code>invopay.product_request_document.product_request_document_file</code>.
     */
    public String getProductRequestDocumentFile() {
        return this.productRequestDocumentFile;
    }

    /**
     * Setter for <code>invopay.product_request_document.product_request_document_file</code>.
     */
    public ProductRequestDocumentDTO setProductRequestDocumentFile(String productRequestDocumentFile) {
        this.productRequestDocumentFile = productRequestDocumentFile;
        return this;
    }

    /**
     * Getter for <code>invopay.product_request_document.ref_user_id</code>.
     */
    public Integer getRefUserId() {
        return this.refUserId;
    }

    /**
     * Setter for <code>invopay.product_request_document.ref_user_id</code>.
     */
    public ProductRequestDocumentDTO setRefUserId(Integer refUserId) {
        this.refUserId = refUserId;
        return this;
    }

    /**
     * Getter for <code>invopay.product_request_document.delete_status</code>.
     */
    public Integer getDeleteStatus() {
        return this.deleteStatus;
    }

    /**
     * Setter for <code>invopay.product_request_document.delete_status</code>.
     */
    public ProductRequestDocumentDTO setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.product_request_document.transaction_id</code>.
     */
    public Integer getTransactionId() {
        return this.transactionId;
    }

    /**
     * Setter for <code>invopay.product_request_document.transaction_id</code>.
     */
    public ProductRequestDocumentDTO setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
        return this;
    }

    /**
     * Getter for <code>invopay.product_request_document.added_date</code>.
     */
    public LocalDateTime getAddedDate() {
        return this.addedDate;
    }

    /**
     * Setter for <code>invopay.product_request_document.added_date</code>.
     */
    public ProductRequestDocumentDTO setAddedDate(LocalDateTime addedDate) {
        this.addedDate = addedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ProductRequestDocumentDTO other = (ProductRequestDocumentDTO) obj;
        if (productRequestDocumentId == null) {
            if (other.productRequestDocumentId != null)
                return false;
        }
        else if (!productRequestDocumentId.equals(other.productRequestDocumentId))
            return false;
        if (refProductSampleRequestId == null) {
            if (other.refProductSampleRequestId != null)
                return false;
        }
        else if (!refProductSampleRequestId.equals(other.refProductSampleRequestId))
            return false;
        if (productRequestDocumentName == null) {
            if (other.productRequestDocumentName != null)
                return false;
        }
        else if (!productRequestDocumentName.equals(other.productRequestDocumentName))
            return false;
        if (productRequestDocumentFile == null) {
            if (other.productRequestDocumentFile != null)
                return false;
        }
        else if (!productRequestDocumentFile.equals(other.productRequestDocumentFile))
            return false;
        if (refUserId == null) {
            if (other.refUserId != null)
                return false;
        }
        else if (!refUserId.equals(other.refUserId))
            return false;
        if (deleteStatus == null) {
            if (other.deleteStatus != null)
                return false;
        }
        else if (!deleteStatus.equals(other.deleteStatus))
            return false;
        if (transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!transactionId.equals(other.transactionId))
            return false;
        if (addedDate == null) {
            if (other.addedDate != null)
                return false;
        }
        else if (!addedDate.equals(other.addedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.productRequestDocumentId == null) ? 0 : this.productRequestDocumentId.hashCode());
        result = prime * result + ((this.refProductSampleRequestId == null) ? 0 : this.refProductSampleRequestId.hashCode());
        result = prime * result + ((this.productRequestDocumentName == null) ? 0 : this.productRequestDocumentName.hashCode());
        result = prime * result + ((this.productRequestDocumentFile == null) ? 0 : this.productRequestDocumentFile.hashCode());
        result = prime * result + ((this.refUserId == null) ? 0 : this.refUserId.hashCode());
        result = prime * result + ((this.deleteStatus == null) ? 0 : this.deleteStatus.hashCode());
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.addedDate == null) ? 0 : this.addedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProductRequestDocument (");

        sb.append(productRequestDocumentId);
        sb.append(", ").append(refProductSampleRequestId);
        sb.append(", ").append(productRequestDocumentName);
        sb.append(", ").append(productRequestDocumentFile);
        sb.append(", ").append(refUserId);
        sb.append(", ").append(deleteStatus);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(addedDate);

        sb.append(")");
        return sb.toString();
    }
}
