/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.DTO;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResetPasswordDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       resetPasswordId;
    private Integer       refUserId;
    private String        hashKey;
    private Integer       resetPasswordStatus;
    private Integer       deleteStatus;
    private Integer       transactionId;
    private LocalDateTime addedDate;

    public ResetPasswordDTO() {}

    public ResetPasswordDTO(ResetPasswordDTO value) {
        this.resetPasswordId = value.resetPasswordId;
        this.refUserId = value.refUserId;
        this.hashKey = value.hashKey;
        this.resetPasswordStatus = value.resetPasswordStatus;
        this.deleteStatus = value.deleteStatus;
        this.transactionId = value.transactionId;
        this.addedDate = value.addedDate;
    }

    public ResetPasswordDTO(
        Integer       resetPasswordId,
        Integer       refUserId,
        String        hashKey,
        Integer       resetPasswordStatus,
        Integer       deleteStatus,
        Integer       transactionId,
        LocalDateTime addedDate
    ) {
        this.resetPasswordId = resetPasswordId;
        this.refUserId = refUserId;
        this.hashKey = hashKey;
        this.resetPasswordStatus = resetPasswordStatus;
        this.deleteStatus = deleteStatus;
        this.transactionId = transactionId;
        this.addedDate = addedDate;
    }

    /**
     * Getter for <code>invopay.reset_password.reset_password_id</code>.
     */
    public Integer getResetPasswordId() {
        return this.resetPasswordId;
    }

    /**
     * Setter for <code>invopay.reset_password.reset_password_id</code>.
     */
    public ResetPasswordDTO setResetPasswordId(Integer resetPasswordId) {
        this.resetPasswordId = resetPasswordId;
        return this;
    }

    /**
     * Getter for <code>invopay.reset_password.ref_user_id</code>.
     */
    public Integer getRefUserId() {
        return this.refUserId;
    }

    /**
     * Setter for <code>invopay.reset_password.ref_user_id</code>.
     */
    public ResetPasswordDTO setRefUserId(Integer refUserId) {
        this.refUserId = refUserId;
        return this;
    }

    /**
     * Getter for <code>invopay.reset_password.hash_key</code>.
     */
    public String getHashKey() {
        return this.hashKey;
    }

    /**
     * Setter for <code>invopay.reset_password.hash_key</code>.
     */
    public ResetPasswordDTO setHashKey(String hashKey) {
        this.hashKey = hashKey;
        return this;
    }

    /**
     * Getter for <code>invopay.reset_password.reset_password_status</code>.
     */
    public Integer getResetPasswordStatus() {
        return this.resetPasswordStatus;
    }

    /**
     * Setter for <code>invopay.reset_password.reset_password_status</code>.
     */
    public ResetPasswordDTO setResetPasswordStatus(Integer resetPasswordStatus) {
        this.resetPasswordStatus = resetPasswordStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.reset_password.delete_status</code>.
     */
    public Integer getDeleteStatus() {
        return this.deleteStatus;
    }

    /**
     * Setter for <code>invopay.reset_password.delete_status</code>.
     */
    public ResetPasswordDTO setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.reset_password.transaction_id</code>.
     */
    public Integer getTransactionId() {
        return this.transactionId;
    }

    /**
     * Setter for <code>invopay.reset_password.transaction_id</code>.
     */
    public ResetPasswordDTO setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
        return this;
    }

    /**
     * Getter for <code>invopay.reset_password.added_date</code>.
     */
    public LocalDateTime getAddedDate() {
        return this.addedDate;
    }

    /**
     * Setter for <code>invopay.reset_password.added_date</code>.
     */
    public ResetPasswordDTO setAddedDate(LocalDateTime addedDate) {
        this.addedDate = addedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ResetPasswordDTO other = (ResetPasswordDTO) obj;
        if (resetPasswordId == null) {
            if (other.resetPasswordId != null)
                return false;
        }
        else if (!resetPasswordId.equals(other.resetPasswordId))
            return false;
        if (refUserId == null) {
            if (other.refUserId != null)
                return false;
        }
        else if (!refUserId.equals(other.refUserId))
            return false;
        if (hashKey == null) {
            if (other.hashKey != null)
                return false;
        }
        else if (!hashKey.equals(other.hashKey))
            return false;
        if (resetPasswordStatus == null) {
            if (other.resetPasswordStatus != null)
                return false;
        }
        else if (!resetPasswordStatus.equals(other.resetPasswordStatus))
            return false;
        if (deleteStatus == null) {
            if (other.deleteStatus != null)
                return false;
        }
        else if (!deleteStatus.equals(other.deleteStatus))
            return false;
        if (transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!transactionId.equals(other.transactionId))
            return false;
        if (addedDate == null) {
            if (other.addedDate != null)
                return false;
        }
        else if (!addedDate.equals(other.addedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.resetPasswordId == null) ? 0 : this.resetPasswordId.hashCode());
        result = prime * result + ((this.refUserId == null) ? 0 : this.refUserId.hashCode());
        result = prime * result + ((this.hashKey == null) ? 0 : this.hashKey.hashCode());
        result = prime * result + ((this.resetPasswordStatus == null) ? 0 : this.resetPasswordStatus.hashCode());
        result = prime * result + ((this.deleteStatus == null) ? 0 : this.deleteStatus.hashCode());
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.addedDate == null) ? 0 : this.addedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ResetPassword (");

        sb.append(resetPasswordId);
        sb.append(", ").append(refUserId);
        sb.append(", ").append(hashKey);
        sb.append(", ").append(resetPasswordStatus);
        sb.append(", ").append(deleteStatus);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(addedDate);

        sb.append(")");
        return sb.toString();
    }
}
