/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.DTO;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SalutationDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       salutationId;
    private String        salutationName;
    private Integer       deleteStatus;
    private Integer       userId;
    private Integer       transactionId;
    private LocalDateTime addedDate;

    public SalutationDTO() {}

    public SalutationDTO(SalutationDTO value) {
        this.salutationId = value.salutationId;
        this.salutationName = value.salutationName;
        this.deleteStatus = value.deleteStatus;
        this.userId = value.userId;
        this.transactionId = value.transactionId;
        this.addedDate = value.addedDate;
    }

    public SalutationDTO(
        Integer       salutationId,
        String        salutationName,
        Integer       deleteStatus,
        Integer       userId,
        Integer       transactionId,
        LocalDateTime addedDate
    ) {
        this.salutationId = salutationId;
        this.salutationName = salutationName;
        this.deleteStatus = deleteStatus;
        this.userId = userId;
        this.transactionId = transactionId;
        this.addedDate = addedDate;
    }

    /**
     * Getter for <code>invopay.salutation.salutation_id</code>.
     */
    public Integer getSalutationId() {
        return this.salutationId;
    }

    /**
     * Setter for <code>invopay.salutation.salutation_id</code>.
     */
    public SalutationDTO setSalutationId(Integer salutationId) {
        this.salutationId = salutationId;
        return this;
    }

    /**
     * Getter for <code>invopay.salutation.salutation_name</code>.
     */
    public String getSalutationName() {
        return this.salutationName;
    }

    /**
     * Setter for <code>invopay.salutation.salutation_name</code>.
     */
    public SalutationDTO setSalutationName(String salutationName) {
        this.salutationName = salutationName;
        return this;
    }

    /**
     * Getter for <code>invopay.salutation.delete_status</code>.
     */
    public Integer getDeleteStatus() {
        return this.deleteStatus;
    }

    /**
     * Setter for <code>invopay.salutation.delete_status</code>.
     */
    public SalutationDTO setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.salutation.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>invopay.salutation.user_id</code>.
     */
    public SalutationDTO setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>invopay.salutation.transaction_id</code>.
     */
    public Integer getTransactionId() {
        return this.transactionId;
    }

    /**
     * Setter for <code>invopay.salutation.transaction_id</code>.
     */
    public SalutationDTO setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
        return this;
    }

    /**
     * Getter for <code>invopay.salutation.added_date</code>.
     */
    public LocalDateTime getAddedDate() {
        return this.addedDate;
    }

    /**
     * Setter for <code>invopay.salutation.added_date</code>.
     */
    public SalutationDTO setAddedDate(LocalDateTime addedDate) {
        this.addedDate = addedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final SalutationDTO other = (SalutationDTO) obj;
        if (salutationId == null) {
            if (other.salutationId != null)
                return false;
        }
        else if (!salutationId.equals(other.salutationId))
            return false;
        if (salutationName == null) {
            if (other.salutationName != null)
                return false;
        }
        else if (!salutationName.equals(other.salutationName))
            return false;
        if (deleteStatus == null) {
            if (other.deleteStatus != null)
                return false;
        }
        else if (!deleteStatus.equals(other.deleteStatus))
            return false;
        if (userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!userId.equals(other.userId))
            return false;
        if (transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!transactionId.equals(other.transactionId))
            return false;
        if (addedDate == null) {
            if (other.addedDate != null)
                return false;
        }
        else if (!addedDate.equals(other.addedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.salutationId == null) ? 0 : this.salutationId.hashCode());
        result = prime * result + ((this.salutationName == null) ? 0 : this.salutationName.hashCode());
        result = prime * result + ((this.deleteStatus == null) ? 0 : this.deleteStatus.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.addedDate == null) ? 0 : this.addedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Salutation (");

        sb.append(salutationId);
        sb.append(", ").append(salutationName);
        sb.append(", ").append(deleteStatus);
        sb.append(", ").append(userId);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(addedDate);

        sb.append(")");
        return sb.toString();
    }
}
