/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.DTO;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StateDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       stateId;
    private Integer       refCountryId;
    private String        stateName;
    private String        code;
    private Byte          status;
    private Integer       deleteStatus;
    private Integer       userId;
    private Integer       transactionId;
    private LocalDateTime addedDate;

    public StateDTO() {}

    public StateDTO(StateDTO value) {
        this.stateId = value.stateId;
        this.refCountryId = value.refCountryId;
        this.stateName = value.stateName;
        this.code = value.code;
        this.status = value.status;
        this.deleteStatus = value.deleteStatus;
        this.userId = value.userId;
        this.transactionId = value.transactionId;
        this.addedDate = value.addedDate;
    }

    public StateDTO(
        Integer       stateId,
        Integer       refCountryId,
        String        stateName,
        String        code,
        Byte          status,
        Integer       deleteStatus,
        Integer       userId,
        Integer       transactionId,
        LocalDateTime addedDate
    ) {
        this.stateId = stateId;
        this.refCountryId = refCountryId;
        this.stateName = stateName;
        this.code = code;
        this.status = status;
        this.deleteStatus = deleteStatus;
        this.userId = userId;
        this.transactionId = transactionId;
        this.addedDate = addedDate;
    }

    /**
     * Getter for <code>invopay.state.state_id</code>.
     */
    public Integer getStateId() {
        return this.stateId;
    }

    /**
     * Setter for <code>invopay.state.state_id</code>.
     */
    public StateDTO setStateId(Integer stateId) {
        this.stateId = stateId;
        return this;
    }

    /**
     * Getter for <code>invopay.state.ref_country_id</code>.
     */
    public Integer getRefCountryId() {
        return this.refCountryId;
    }

    /**
     * Setter for <code>invopay.state.ref_country_id</code>.
     */
    public StateDTO setRefCountryId(Integer refCountryId) {
        this.refCountryId = refCountryId;
        return this;
    }

    /**
     * Getter for <code>invopay.state.state_name</code>.
     */
    public String getStateName() {
        return this.stateName;
    }

    /**
     * Setter for <code>invopay.state.state_name</code>.
     */
    public StateDTO setStateName(String stateName) {
        this.stateName = stateName;
        return this;
    }

    /**
     * Getter for <code>invopay.state.code</code>.
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Setter for <code>invopay.state.code</code>.
     */
    public StateDTO setCode(String code) {
        this.code = code;
        return this;
    }

    /**
     * Getter for <code>invopay.state.status</code>.
     */
    public Byte getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>invopay.state.status</code>.
     */
    public StateDTO setStatus(Byte status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>invopay.state.delete_status</code>.
     */
    public Integer getDeleteStatus() {
        return this.deleteStatus;
    }

    /**
     * Setter for <code>invopay.state.delete_status</code>.
     */
    public StateDTO setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.state.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>invopay.state.user_id</code>.
     */
    public StateDTO setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>invopay.state.transaction_id</code>.
     */
    public Integer getTransactionId() {
        return this.transactionId;
    }

    /**
     * Setter for <code>invopay.state.transaction_id</code>.
     */
    public StateDTO setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
        return this;
    }

    /**
     * Getter for <code>invopay.state.added_date</code>.
     */
    public LocalDateTime getAddedDate() {
        return this.addedDate;
    }

    /**
     * Setter for <code>invopay.state.added_date</code>.
     */
    public StateDTO setAddedDate(LocalDateTime addedDate) {
        this.addedDate = addedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final StateDTO other = (StateDTO) obj;
        if (stateId == null) {
            if (other.stateId != null)
                return false;
        }
        else if (!stateId.equals(other.stateId))
            return false;
        if (refCountryId == null) {
            if (other.refCountryId != null)
                return false;
        }
        else if (!refCountryId.equals(other.refCountryId))
            return false;
        if (stateName == null) {
            if (other.stateName != null)
                return false;
        }
        else if (!stateName.equals(other.stateName))
            return false;
        if (code == null) {
            if (other.code != null)
                return false;
        }
        else if (!code.equals(other.code))
            return false;
        if (status == null) {
            if (other.status != null)
                return false;
        }
        else if (!status.equals(other.status))
            return false;
        if (deleteStatus == null) {
            if (other.deleteStatus != null)
                return false;
        }
        else if (!deleteStatus.equals(other.deleteStatus))
            return false;
        if (userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!userId.equals(other.userId))
            return false;
        if (transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!transactionId.equals(other.transactionId))
            return false;
        if (addedDate == null) {
            if (other.addedDate != null)
                return false;
        }
        else if (!addedDate.equals(other.addedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.stateId == null) ? 0 : this.stateId.hashCode());
        result = prime * result + ((this.refCountryId == null) ? 0 : this.refCountryId.hashCode());
        result = prime * result + ((this.stateName == null) ? 0 : this.stateName.hashCode());
        result = prime * result + ((this.code == null) ? 0 : this.code.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.deleteStatus == null) ? 0 : this.deleteStatus.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.addedDate == null) ? 0 : this.addedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("State (");

        sb.append(stateId);
        sb.append(", ").append(refCountryId);
        sb.append(", ").append(stateName);
        sb.append(", ").append(code);
        sb.append(", ").append(status);
        sb.append(", ").append(deleteStatus);
        sb.append(", ").append(userId);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(addedDate);

        sb.append(")");
        return sb.toString();
    }
}
