/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.DTO;


import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VehicleDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       vehicleId;
    private Integer       refCustomerId;
    private Integer       refVehicleTypeId;
    private String        vehicleImageFile;
    private String        vehicleRegNo;
    private String        vehicleMake;
    private String        vehicleModel;
    private Integer       noOfSeats;
    private Integer       availableSeats;
    private String        insurnaceFile;
    private LocalDate     insurnaceExpiryDate;
    private Integer       refUserId;
    private LocalDateTime addedDate;
    private Integer       transactionId;
    private Integer       deleteStatus;

    public VehicleDTO() {}

    public VehicleDTO(VehicleDTO value) {
        this.vehicleId = value.vehicleId;
        this.refCustomerId = value.refCustomerId;
        this.refVehicleTypeId = value.refVehicleTypeId;
        this.vehicleImageFile = value.vehicleImageFile;
        this.vehicleRegNo = value.vehicleRegNo;
        this.vehicleMake = value.vehicleMake;
        this.vehicleModel = value.vehicleModel;
        this.noOfSeats = value.noOfSeats;
        this.availableSeats = value.availableSeats;
        this.insurnaceFile = value.insurnaceFile;
        this.insurnaceExpiryDate = value.insurnaceExpiryDate;
        this.refUserId = value.refUserId;
        this.addedDate = value.addedDate;
        this.transactionId = value.transactionId;
        this.deleteStatus = value.deleteStatus;
    }

    public VehicleDTO(
        Integer       vehicleId,
        Integer       refCustomerId,
        Integer       refVehicleTypeId,
        String        vehicleImageFile,
        String        vehicleRegNo,
        String        vehicleMake,
        String        vehicleModel,
        Integer       noOfSeats,
        Integer       availableSeats,
        String        insurnaceFile,
        LocalDate     insurnaceExpiryDate,
        Integer       refUserId,
        LocalDateTime addedDate,
        Integer       transactionId,
        Integer       deleteStatus
    ) {
        this.vehicleId = vehicleId;
        this.refCustomerId = refCustomerId;
        this.refVehicleTypeId = refVehicleTypeId;
        this.vehicleImageFile = vehicleImageFile;
        this.vehicleRegNo = vehicleRegNo;
        this.vehicleMake = vehicleMake;
        this.vehicleModel = vehicleModel;
        this.noOfSeats = noOfSeats;
        this.availableSeats = availableSeats;
        this.insurnaceFile = insurnaceFile;
        this.insurnaceExpiryDate = insurnaceExpiryDate;
        this.refUserId = refUserId;
        this.addedDate = addedDate;
        this.transactionId = transactionId;
        this.deleteStatus = deleteStatus;
    }

    /**
     * Getter for <code>invopay.vehicle.vehicle_id</code>.
     */
    public Integer getVehicleId() {
        return this.vehicleId;
    }

    /**
     * Setter for <code>invopay.vehicle.vehicle_id</code>.
     */
    public VehicleDTO setVehicleId(Integer vehicleId) {
        this.vehicleId = vehicleId;
        return this;
    }

    /**
     * Getter for <code>invopay.vehicle.ref_customer_id</code>.
     */
    public Integer getRefCustomerId() {
        return this.refCustomerId;
    }

    /**
     * Setter for <code>invopay.vehicle.ref_customer_id</code>.
     */
    public VehicleDTO setRefCustomerId(Integer refCustomerId) {
        this.refCustomerId = refCustomerId;
        return this;
    }

    /**
     * Getter for <code>invopay.vehicle.ref_vehicle_type_id</code>.
     */
    public Integer getRefVehicleTypeId() {
        return this.refVehicleTypeId;
    }

    /**
     * Setter for <code>invopay.vehicle.ref_vehicle_type_id</code>.
     */
    public VehicleDTO setRefVehicleTypeId(Integer refVehicleTypeId) {
        this.refVehicleTypeId = refVehicleTypeId;
        return this;
    }

    /**
     * Getter for <code>invopay.vehicle.vehicle_image_file</code>.
     */
    public String getVehicleImageFile() {
        return this.vehicleImageFile;
    }

    /**
     * Setter for <code>invopay.vehicle.vehicle_image_file</code>.
     */
    public VehicleDTO setVehicleImageFile(String vehicleImageFile) {
        this.vehicleImageFile = vehicleImageFile;
        return this;
    }

    /**
     * Getter for <code>invopay.vehicle.vehicle_reg_no</code>.
     */
    public String getVehicleRegNo() {
        return this.vehicleRegNo;
    }

    /**
     * Setter for <code>invopay.vehicle.vehicle_reg_no</code>.
     */
    public VehicleDTO setVehicleRegNo(String vehicleRegNo) {
        this.vehicleRegNo = vehicleRegNo;
        return this;
    }

    /**
     * Getter for <code>invopay.vehicle.vehicle_make</code>.
     */
    public String getVehicleMake() {
        return this.vehicleMake;
    }

    /**
     * Setter for <code>invopay.vehicle.vehicle_make</code>.
     */
    public VehicleDTO setVehicleMake(String vehicleMake) {
        this.vehicleMake = vehicleMake;
        return this;
    }

    /**
     * Getter for <code>invopay.vehicle.vehicle_model</code>.
     */
    public String getVehicleModel() {
        return this.vehicleModel;
    }

    /**
     * Setter for <code>invopay.vehicle.vehicle_model</code>.
     */
    public VehicleDTO setVehicleModel(String vehicleModel) {
        this.vehicleModel = vehicleModel;
        return this;
    }

    /**
     * Getter for <code>invopay.vehicle.no_of_seats</code>.
     */
    public Integer getNoOfSeats() {
        return this.noOfSeats;
    }

    /**
     * Setter for <code>invopay.vehicle.no_of_seats</code>.
     */
    public VehicleDTO setNoOfSeats(Integer noOfSeats) {
        this.noOfSeats = noOfSeats;
        return this;
    }

    /**
     * Getter for <code>invopay.vehicle.available_seats</code>.
     */
    public Integer getAvailableSeats() {
        return this.availableSeats;
    }

    /**
     * Setter for <code>invopay.vehicle.available_seats</code>.
     */
    public VehicleDTO setAvailableSeats(Integer availableSeats) {
        this.availableSeats = availableSeats;
        return this;
    }

    /**
     * Getter for <code>invopay.vehicle.insurnace_file</code>.
     */
    public String getInsurnaceFile() {
        return this.insurnaceFile;
    }

    /**
     * Setter for <code>invopay.vehicle.insurnace_file</code>.
     */
    public VehicleDTO setInsurnaceFile(String insurnaceFile) {
        this.insurnaceFile = insurnaceFile;
        return this;
    }

    /**
     * Getter for <code>invopay.vehicle.insurnace_expiry_date</code>.
     */
    public LocalDate getInsurnaceExpiryDate() {
        return this.insurnaceExpiryDate;
    }

    /**
     * Setter for <code>invopay.vehicle.insurnace_expiry_date</code>.
     */
    public VehicleDTO setInsurnaceExpiryDate(LocalDate insurnaceExpiryDate) {
        this.insurnaceExpiryDate = insurnaceExpiryDate;
        return this;
    }

    /**
     * Getter for <code>invopay.vehicle.ref_user_id</code>.
     */
    public Integer getRefUserId() {
        return this.refUserId;
    }

    /**
     * Setter for <code>invopay.vehicle.ref_user_id</code>.
     */
    public VehicleDTO setRefUserId(Integer refUserId) {
        this.refUserId = refUserId;
        return this;
    }

    /**
     * Getter for <code>invopay.vehicle.added_date</code>.
     */
    public LocalDateTime getAddedDate() {
        return this.addedDate;
    }

    /**
     * Setter for <code>invopay.vehicle.added_date</code>.
     */
    public VehicleDTO setAddedDate(LocalDateTime addedDate) {
        this.addedDate = addedDate;
        return this;
    }

    /**
     * Getter for <code>invopay.vehicle.transaction_id</code>.
     */
    public Integer getTransactionId() {
        return this.transactionId;
    }

    /**
     * Setter for <code>invopay.vehicle.transaction_id</code>.
     */
    public VehicleDTO setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
        return this;
    }

    /**
     * Getter for <code>invopay.vehicle.delete_status</code>.
     */
    public Integer getDeleteStatus() {
        return this.deleteStatus;
    }

    /**
     * Setter for <code>invopay.vehicle.delete_status</code>.
     */
    public VehicleDTO setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final VehicleDTO other = (VehicleDTO) obj;
        if (vehicleId == null) {
            if (other.vehicleId != null)
                return false;
        }
        else if (!vehicleId.equals(other.vehicleId))
            return false;
        if (refCustomerId == null) {
            if (other.refCustomerId != null)
                return false;
        }
        else if (!refCustomerId.equals(other.refCustomerId))
            return false;
        if (refVehicleTypeId == null) {
            if (other.refVehicleTypeId != null)
                return false;
        }
        else if (!refVehicleTypeId.equals(other.refVehicleTypeId))
            return false;
        if (vehicleImageFile == null) {
            if (other.vehicleImageFile != null)
                return false;
        }
        else if (!vehicleImageFile.equals(other.vehicleImageFile))
            return false;
        if (vehicleRegNo == null) {
            if (other.vehicleRegNo != null)
                return false;
        }
        else if (!vehicleRegNo.equals(other.vehicleRegNo))
            return false;
        if (vehicleMake == null) {
            if (other.vehicleMake != null)
                return false;
        }
        else if (!vehicleMake.equals(other.vehicleMake))
            return false;
        if (vehicleModel == null) {
            if (other.vehicleModel != null)
                return false;
        }
        else if (!vehicleModel.equals(other.vehicleModel))
            return false;
        if (noOfSeats == null) {
            if (other.noOfSeats != null)
                return false;
        }
        else if (!noOfSeats.equals(other.noOfSeats))
            return false;
        if (availableSeats == null) {
            if (other.availableSeats != null)
                return false;
        }
        else if (!availableSeats.equals(other.availableSeats))
            return false;
        if (insurnaceFile == null) {
            if (other.insurnaceFile != null)
                return false;
        }
        else if (!insurnaceFile.equals(other.insurnaceFile))
            return false;
        if (insurnaceExpiryDate == null) {
            if (other.insurnaceExpiryDate != null)
                return false;
        }
        else if (!insurnaceExpiryDate.equals(other.insurnaceExpiryDate))
            return false;
        if (refUserId == null) {
            if (other.refUserId != null)
                return false;
        }
        else if (!refUserId.equals(other.refUserId))
            return false;
        if (addedDate == null) {
            if (other.addedDate != null)
                return false;
        }
        else if (!addedDate.equals(other.addedDate))
            return false;
        if (transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!transactionId.equals(other.transactionId))
            return false;
        if (deleteStatus == null) {
            if (other.deleteStatus != null)
                return false;
        }
        else if (!deleteStatus.equals(other.deleteStatus))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.vehicleId == null) ? 0 : this.vehicleId.hashCode());
        result = prime * result + ((this.refCustomerId == null) ? 0 : this.refCustomerId.hashCode());
        result = prime * result + ((this.refVehicleTypeId == null) ? 0 : this.refVehicleTypeId.hashCode());
        result = prime * result + ((this.vehicleImageFile == null) ? 0 : this.vehicleImageFile.hashCode());
        result = prime * result + ((this.vehicleRegNo == null) ? 0 : this.vehicleRegNo.hashCode());
        result = prime * result + ((this.vehicleMake == null) ? 0 : this.vehicleMake.hashCode());
        result = prime * result + ((this.vehicleModel == null) ? 0 : this.vehicleModel.hashCode());
        result = prime * result + ((this.noOfSeats == null) ? 0 : this.noOfSeats.hashCode());
        result = prime * result + ((this.availableSeats == null) ? 0 : this.availableSeats.hashCode());
        result = prime * result + ((this.insurnaceFile == null) ? 0 : this.insurnaceFile.hashCode());
        result = prime * result + ((this.insurnaceExpiryDate == null) ? 0 : this.insurnaceExpiryDate.hashCode());
        result = prime * result + ((this.refUserId == null) ? 0 : this.refUserId.hashCode());
        result = prime * result + ((this.addedDate == null) ? 0 : this.addedDate.hashCode());
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.deleteStatus == null) ? 0 : this.deleteStatus.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Vehicle (");

        sb.append(vehicleId);
        sb.append(", ").append(refCustomerId);
        sb.append(", ").append(refVehicleTypeId);
        sb.append(", ").append(vehicleImageFile);
        sb.append(", ").append(vehicleRegNo);
        sb.append(", ").append(vehicleMake);
        sb.append(", ").append(vehicleModel);
        sb.append(", ").append(noOfSeats);
        sb.append(", ").append(availableSeats);
        sb.append(", ").append(insurnaceFile);
        sb.append(", ").append(insurnaceExpiryDate);
        sb.append(", ").append(refUserId);
        sb.append(", ").append(addedDate);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(deleteStatus);

        sb.append(")");
        return sb.toString();
    }
}
