/*
 * This file is generated by jOOQ.
 */
package com.commons.invopayWebServices.DTO;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VehicleTypeDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       vehicleTypeId;
    private String        vehicleTypeName;
    private Integer       sortOrder;
    private Integer       refUserId;
    private LocalDateTime addedDate;
    private Integer       transactionId;
    private Integer       deleteStatus;
    private String        vehicleTypeImage;

    public VehicleTypeDTO() {}

    public VehicleTypeDTO(VehicleTypeDTO value) {
        this.vehicleTypeId = value.vehicleTypeId;
        this.vehicleTypeName = value.vehicleTypeName;
        this.sortOrder = value.sortOrder;
        this.refUserId = value.refUserId;
        this.addedDate = value.addedDate;
        this.transactionId = value.transactionId;
        this.deleteStatus = value.deleteStatus;
        this.vehicleTypeImage = value.vehicleTypeImage;
    }

    public VehicleTypeDTO(
        Integer       vehicleTypeId,
        String        vehicleTypeName,
        Integer       sortOrder,
        Integer       refUserId,
        LocalDateTime addedDate,
        Integer       transactionId,
        Integer       deleteStatus,
        String        vehicleTypeImage
    ) {
        this.vehicleTypeId = vehicleTypeId;
        this.vehicleTypeName = vehicleTypeName;
        this.sortOrder = sortOrder;
        this.refUserId = refUserId;
        this.addedDate = addedDate;
        this.transactionId = transactionId;
        this.deleteStatus = deleteStatus;
        this.vehicleTypeImage = vehicleTypeImage;
    }

    /**
     * Getter for <code>invopay.vehicle_type.vehicle_type_id</code>.
     */
    public Integer getVehicleTypeId() {
        return this.vehicleTypeId;
    }

    /**
     * Setter for <code>invopay.vehicle_type.vehicle_type_id</code>.
     */
    public VehicleTypeDTO setVehicleTypeId(Integer vehicleTypeId) {
        this.vehicleTypeId = vehicleTypeId;
        return this;
    }

    /**
     * Getter for <code>invopay.vehicle_type.vehicle_type_name</code>.
     */
    public String getVehicleTypeName() {
        return this.vehicleTypeName;
    }

    /**
     * Setter for <code>invopay.vehicle_type.vehicle_type_name</code>.
     */
    public VehicleTypeDTO setVehicleTypeName(String vehicleTypeName) {
        this.vehicleTypeName = vehicleTypeName;
        return this;
    }

    /**
     * Getter for <code>invopay.vehicle_type.sort_order</code>.
     */
    public Integer getSortOrder() {
        return this.sortOrder;
    }

    /**
     * Setter for <code>invopay.vehicle_type.sort_order</code>.
     */
    public VehicleTypeDTO setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
        return this;
    }

    /**
     * Getter for <code>invopay.vehicle_type.ref_user_id</code>.
     */
    public Integer getRefUserId() {
        return this.refUserId;
    }

    /**
     * Setter for <code>invopay.vehicle_type.ref_user_id</code>.
     */
    public VehicleTypeDTO setRefUserId(Integer refUserId) {
        this.refUserId = refUserId;
        return this;
    }

    /**
     * Getter for <code>invopay.vehicle_type.added_date</code>.
     */
    public LocalDateTime getAddedDate() {
        return this.addedDate;
    }

    /**
     * Setter for <code>invopay.vehicle_type.added_date</code>.
     */
    public VehicleTypeDTO setAddedDate(LocalDateTime addedDate) {
        this.addedDate = addedDate;
        return this;
    }

    /**
     * Getter for <code>invopay.vehicle_type.transaction_id</code>.
     */
    public Integer getTransactionId() {
        return this.transactionId;
    }

    /**
     * Setter for <code>invopay.vehicle_type.transaction_id</code>.
     */
    public VehicleTypeDTO setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
        return this;
    }

    /**
     * Getter for <code>invopay.vehicle_type.delete_status</code>.
     */
    public Integer getDeleteStatus() {
        return this.deleteStatus;
    }

    /**
     * Setter for <code>invopay.vehicle_type.delete_status</code>.
     */
    public VehicleTypeDTO setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
        return this;
    }

    /**
     * Getter for <code>invopay.vehicle_type.vehicle_type_image</code>.
     */
    public String getVehicleTypeImage() {
        return this.vehicleTypeImage;
    }

    /**
     * Setter for <code>invopay.vehicle_type.vehicle_type_image</code>.
     */
    public VehicleTypeDTO setVehicleTypeImage(String vehicleTypeImage) {
        this.vehicleTypeImage = vehicleTypeImage;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final VehicleTypeDTO other = (VehicleTypeDTO) obj;
        if (vehicleTypeId == null) {
            if (other.vehicleTypeId != null)
                return false;
        }
        else if (!vehicleTypeId.equals(other.vehicleTypeId))
            return false;
        if (vehicleTypeName == null) {
            if (other.vehicleTypeName != null)
                return false;
        }
        else if (!vehicleTypeName.equals(other.vehicleTypeName))
            return false;
        if (sortOrder == null) {
            if (other.sortOrder != null)
                return false;
        }
        else if (!sortOrder.equals(other.sortOrder))
            return false;
        if (refUserId == null) {
            if (other.refUserId != null)
                return false;
        }
        else if (!refUserId.equals(other.refUserId))
            return false;
        if (addedDate == null) {
            if (other.addedDate != null)
                return false;
        }
        else if (!addedDate.equals(other.addedDate))
            return false;
        if (transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!transactionId.equals(other.transactionId))
            return false;
        if (deleteStatus == null) {
            if (other.deleteStatus != null)
                return false;
        }
        else if (!deleteStatus.equals(other.deleteStatus))
            return false;
        if (vehicleTypeImage == null) {
            if (other.vehicleTypeImage != null)
                return false;
        }
        else if (!vehicleTypeImage.equals(other.vehicleTypeImage))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.vehicleTypeId == null) ? 0 : this.vehicleTypeId.hashCode());
        result = prime * result + ((this.vehicleTypeName == null) ? 0 : this.vehicleTypeName.hashCode());
        result = prime * result + ((this.sortOrder == null) ? 0 : this.sortOrder.hashCode());
        result = prime * result + ((this.refUserId == null) ? 0 : this.refUserId.hashCode());
        result = prime * result + ((this.addedDate == null) ? 0 : this.addedDate.hashCode());
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.deleteStatus == null) ? 0 : this.deleteStatus.hashCode());
        result = prime * result + ((this.vehicleTypeImage == null) ? 0 : this.vehicleTypeImage.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VehicleType (");

        sb.append(vehicleTypeId);
        sb.append(", ").append(vehicleTypeName);
        sb.append(", ").append(sortOrder);
        sb.append(", ").append(refUserId);
        sb.append(", ").append(addedDate);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(deleteStatus);
        sb.append(", ").append(vehicleTypeImage);

        sb.append(")");
        return sb.toString();
    }
}
